export const simulatedCustomers = [
  "Ngọc Trinh", "Vũ Hoàng My", "Đặng Lê Nguyên", "Phan Hoàng Yến", "Trịnh Thảo Chi",
  "Trần Văn Hưng", "Lê Thanh Phong", "Phạm Quốc Bảo", "Nguyễn Minh Tuấn", "Đỗ Hải",
  "Mai Phương", "Hoàng Kim", "Hồ Ngọc Hà", "Thanh Hằng", "Hương Giang",
  "Võ Hoàng Yến", "Minh Tú", "Lan Khuê", "Phạm Hương", "H'Hen Niê"
];

export const simulatedAvatars = [
  "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80",
  "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80",
  "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
  "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80",
  "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80"
];

// Mảng 100 câu hỏi thực tế được phân loại theo Intent
export const simulatedQuestions = [
  // HỎI SẢN PHẨM / CHẤT LIỆU (product_info)
  { text: "Áo blazer này chất vải gì vậy shop?", intent: "question" },
  { text: "Đầm dự tiệc màu đỏ lụa tơ tằm hay umi thế em?", intent: "question" },
  { text: "Váy hè lụa mặc có mát không shop?", intent: "question" },
  { text: "Chất liệu áo này có dễ nhăn không?", intent: "question" },
  { text: "Tư vấn cho mình đầm này nha", intent: "question" },
  { text: "Blazer màu be còn không shop?", intent: "question" },
  { text: "Có áo khoác nào hợp mặc đi làm không shop ơi", intent: "question" },
  { text: "Mình muốn xem đầm đỏ quay kỹ hơn được không?", intent: "question" },
  { text: "Váy lụa hàn có dễ rách không em?", intent: "question" },
  { text: "Đầm V-line eo co giãn không shop?", intent: "question" },
  { text: "Áo blazer có lót trong không vậy ạ", intent: "question" },
  { text: "Đầm đỏ này giặt máy được không?", intent: "question" },
  { text: "Giới thiệu lại mẫu váy lụa giúp mình nha", intent: "question" },
  { text: "Sản phẩm Blazer có đệm vai không em ơi?", intent: "question" },
  { text: "Đầm đỏ mặc đi tiệc cưới hợp không shop?", intent: "question" },
  { text: "Blazer mặc mùa hè có nóng không?", intent: "question" },
  { text: "Form đầm dạ hội này có che bụng không?", intent: "question" },
  { text: "Váy lụa có lớp lót không, sợ lộ đồ lót", intent: "question" },
  { text: "Sản phẩm áo khoác dáng dài hay ngắn vậy?", intent: "question" },
  { text: "Đầm V-line có xẻ tà không?", intent: "question" },

  // HỎI SIZE / TƯ VẤN (size_consult)
  { text: "Mình cao 1m62 nặng 52kg mặc size gì?", intent: "question" },
  { text: "55kg mặc vừa size M đầm đỏ không em?", intent: "question" },
  { text: "60kg thì mặc blazer size L hay XL shop?", intent: "question" },
  { text: "Tư vấn size váy lụa cho người 1m50 nặng 45kg nha", intent: "question" },
  { text: "Đầm này có size cho người béo không?", intent: "question" },
  { text: "Ngực 90 eo 75 mặc đầm V-line size nào?", intent: "question" },
  { text: "Vai to mặc áo blazer có bị thô không shop?", intent: "question" },
  { text: "Váy này dáng suông hay ôm vậy?", intent: "question" },
  { text: "1m7 mặc váy này dài tới đâu em?", intent: "question" },
  { text: "Bầu 5 tháng mặc vừa đầm lụa không shop?", intent: "question" },
  { text: "Blazer này size to nhất là bao nhiêu ký?", intent: "question" },
  { text: "Form áo này form rộng hay form vừa ạ?", intent: "question" },
  { text: "Tư vấn size giúp mình nhé", intent: "question" },
  { text: "Eo 80 thì có mặc vừa đầm dự tiệc này không?", intent: "question" },
  { text: "Mình hay mặc size L thì đầm này có chuẩn size không?", intent: "question" },
  { text: "48kg mặc M có bị rộng không em?", intent: "question" },
  { text: "Áo này tay áo có bị dài quá không, tay mình ngắn", intent: "question" },
  { text: "Đùi to mặc đầm V-line che được không shop?", intent: "question" },
  { text: "Shop tư vấn size blazer cho nam được không?", intent: "question" },
  { text: "Có bảng size không gửi mình xem với", intent: "question" },

  // HỎI DỊCH VỤ / ĐỊA CHỈ / VẬN CHUYỂN (service_info)
  { text: "Shop ở đâu vậy?", intent: "question" },
  { text: "Địa chỉ cửa hàng mình ở quận mấy shop ơi?", intent: "question" },
  { text: "Có cho kiểm tra hàng trước khi thanh toán không?", intent: "question" },
  { text: "Ship về Hà Nội mất bao lâu em?", intent: "question" },
  { text: "Có được đổi trả nếu mặc không vừa size không shop ơi?", intent: "question" },
  { text: "Tiền ship về Đà Nẵng là bao nhiêu?", intent: "question" },
  { text: "Mua 2 cái có được freeship không?", intent: "question" },
  { text: "Xin số điện thoại shop để liên hệ sỉ", intent: "question" },
  { text: "Bên mình có chính sách bảo hành không?", intent: "question" },
  { text: "Hôm nay đặt thì ngày mai nhận được luôn không?", intent: "question" },
  { text: "Cho mình xin địa chỉ qua thử trực tiếp nhé", intent: "question" },
  { text: "Mình muốn làm CTV thì liên hệ hotline nào?", intent: "question" },
  { text: "Mua sỉ có được chiết khấu không shop?", intent: "question" },
  { text: "Lỗi do nhà sản xuất thì bao lâu được đổi?", intent: "question" },
  { text: "Giao hỏa tốc trong TPHCM được không?", intent: "question" },
  { text: "Shop có bán trên Shopee không cho xin link", intent: "question" },
  { text: "Lấy hàng tại kho có được giảm giá không?", intent: "question" },
  { text: "Hỗ trợ đổi màu khác được không em?", intent: "question" },
  { text: "Bên mình có chi nhánh ở Cần Thơ không?", intent: "question" },
  { text: "Khách VIP có mã giảm giá riêng không shop?", intent: "question" },

  // MUA HÀNG / CHỐT ĐƠN (buy)
  { text: "CHỐT 1 COMBO ĐẦM DỰ TIỆC V-LINE SĐT 0912345678 SHIP HÀ NỘI", intent: "buy" },
  { text: "Chốt áo blazer be size L nha shop", intent: "buy" },
  { text: "Cho mình 1 váy lụa hàn SĐT 0988111222", intent: "buy" },
  { text: "Đã dán voucher GIAM50K rồi nha shop, chuẩn bị đóng hàng giúp mình nha!", intent: "buy" },
  { text: "Chốt đầm đỏ SĐT 0909123123", intent: "buy" },
  { text: "Mình đặt 2 blazer xanh và đen size M nhé 0977888999", intent: "buy" },
  { text: "Chốt combo váy lụa giao về quận 1", intent: "buy" },
  { text: "Lên đơn cho mình đầm dự tiệc nha SĐT 0966...", intent: "buy" },
  { text: "Đặt hàng ở đâu vậy shop, lên đơn giúp mình", intent: "buy" },
  { text: "CHỐT váy lụa size S nha", intent: "buy" },
  { text: "Mình lấy blazer be size XL 0944555666", intent: "buy" },
  { text: "Cho 3 đầm V-line 3 màu khác nhau nha shop", intent: "buy" },
  { text: "Chốt đơn áo khoác!", intent: "buy" },
  { text: "Đã đặt mua thành công, shop giao sớm nhé", intent: "buy" },
  { text: "Lên cho mình 1 đơn đầm đỏ về Bắc Ninh sđt 0989...", intent: "buy" },
  { text: "Chốt lẹ giúp chị nha 0933444555", intent: "buy" },
  { text: "Mua luôn 2 cái blazer cho lẹ", intent: "buy" },
  { text: "Chốt đầm đỏ đi tiệc size L", intent: "buy" },
  { text: "Vừa đặt váy lụa xong, kiểm tra bill nha shop", intent: "buy" },
  { text: "CHỐT CHỐT CHỐT 0908777666", intent: "buy" },
  
  // VIP TƯƠNG TÁC (vip)
  { text: "Livestream sắc nét quá! Đã ủng hộ shop 3 đơn hàng hôm nay rồi nha.", intent: "vip" },
  { text: "Mẫu nào shop bán cũng đẹp, mua quen rồi yên tâm", intent: "vip" },
  { text: "Hôm qua mới nhận hàng xong ưng lắm, nay lên mua tiếp", intent: "vip" },
  { text: "Khách VIP đây, nay có mã giảm giá nào xịn không em?", intent: "vip" },
  { text: "Chào shop nha, lâu không lên xem live", intent: "vip" },
  { text: "Mấy nay toàn cháy túi vì shop, đồ xịn quá", intent: "vip" },
  { text: "Hello em gái, hóng mẫu mới", intent: "vip" },
  { text: "Mua đồ bên này 2 năm rồi chưa chê bao giờ", intent: "vip" },
  { text: "Nay live sớm vậy shop?", intent: "vip" },
  { text: "Tặng tym cho shop nè ❤️❤️❤️", intent: "vip" },
  { text: "Đầm hôm trước chị mặc ai cũng khen", intent: "vip" },
  { text: "Nay không có mẫu áo thun à shop ơi?", intent: "vip" },
  { text: "Like share mạnh cho shop lên xu hướng nào", intent: "vip" },
  { text: "Mua nhiều thành fan cứng luôn rồi", intent: "vip" },
  { text: "Lên tiếp mẫu VIP đi em ơi", intent: "vip" },
  { text: "Có quà cho khách cũ không shop?", intent: "vip" },
  { text: "Vẫn ủng hộ shop như mọi ngày", intent: "vip" },
  { text: "Đỉnh quá shop ơi!", intent: "vip" },
  { text: "Chất lượng khỏi bàn cãi nha mọi người", intent: "vip" },
  { text: "Vào chào shop một tiếng rồi đi làm", intent: "vip" }
];
