// BỘ 140 CÂU TỪ KHÓA & PHẢN HỒI MẪU CHUẨN CHO LIVESTREAM BÁN HÀNG & TƯƠNG TÁC AVA LIVE
export const DEFAULT_140_KEYWORD_RULES = [
  {
    "id": "kw_140_1",
    "name": "Xin chào",
    "keywords": [
      "xin chào",
      "chào bạn",
      "hello",
      "hi",
      "chào shop",
      "chào anh chị",
      "chào ad",
      "chào admin",
      "chào shop ạ",
      "chào page",
      "hello shop",
      "hi shop",
      "helo",
      "hii",
      "hí shop",
      "chào mn",
      "chào mọi người",
      "em chào shop",
      "cho em hỏi",
      "ad ơi",
      "shop ơi",
      "xin chao",
      "chao ban"
    ],
    "replyText": "Dạ hello cả nhà nha! 👋 Ghé live là em vui rồi đó 😄 Cứ comment điều mình muốn hỏi, em bắt sóng liền ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_2",
    "name": "Chào buổi sáng",
    "keywords": [
      "chào buổi sáng",
      "chào ngày mới",
      "buổi sáng vui vẻ",
      "sáng nha",
      "sáng tốt lành",
      "good morning",
      "gm",
      "morning shop",
      "chúc shop buổi sáng",
      "sáng vui vẻ",
      "chao buoi sang",
      "chao ngay moi",
      "buoi sang vui ve"
    ],
    "replyText": "Buổi sáng cả nhà ghé live là có tín hiệu vui rồi nha 😄 Chúc mình một ngày thật nhiều năng lượng, cần gì cứ gọi em ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_3",
    "name": "Chào buổi trưa",
    "keywords": [
      "chào buổi trưa",
      "buổi trưa vui vẻ",
      "trưa nha",
      "trưa vui vẻ",
      "good afternoon",
      "afternoon shop",
      "chúc shop buổi trưa",
      "chao buoi trua",
      "buoi trua vui ve"
    ],
    "replyText": "Trưa rồi mà cả nhà vẫn ghé chơi, thương quá nha 😄 Mình vừa nghỉ ngơi vừa giao lưu, có gì cứ hỏi em ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_4",
    "name": "Chào buổi tối",
    "keywords": [
      "chào buổi tối",
      "buổi tối vui vẻ",
      "tối nha",
      "tối vui vẻ",
      "good evening",
      "good night",
      "gn",
      "tối nay shop live không",
      "chao buoi toi",
      "buoi toi vui ve"
    ],
    "replyText": "Tối rồi cả nhà ơi 😄 Ghé chơi một chút cho vui nha! Cần hỏi gì cứ comment, em hỗ trợ ngay ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_5",
    "name": "Cảm ơn",
    "keywords": [
      "cảm ơn",
      "thanks",
      "thank you",
      "cảm ơn em",
      "dạ cảm ơn",
      "thank",
      "thanks shop",
      "thanks ad",
      "tks",
      "thks",
      "cam on",
      "cám ơn",
      "cảm ơn shop",
      "cảm ơn ad",
      "cảm ơn nhiều",
      "ok cảm ơn",
      "thanks em",
      "cam on em"
    ],
    "replyText": "Dạ cảm ơn cả nhà nha ❤️ Một câu cảm ơn thôi mà em vui nguyên buổi luôn á 😄 Cần gì cứ gọi em ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_6",
    "name": "Tuyệt vời",
    "keywords": [
      "tuyệt vời",
      "hay quá",
      "hữu ích",
      "đẹp quá",
      "thích quá",
      "tuyệt",
      "đỉnh",
      "xịn",
      "xịn quá",
      "hay ghê",
      "quá hay",
      "quá đẹp",
      "ưng quá",
      "mê quá",
      "thích ghê",
      "10 điểm",
      "ok quá",
      "chuẩn quá",
      "tuyet voi",
      "hay qua",
      "huu ich",
      "dep qua"
    ],
    "replyText": "Ui được khen là em có thêm pin liền đó nha 😄 Cảm ơn cả nhà nhiều lắm, mình giao lưu tiếp cho vui ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_7",
    "name": "Giá bao nhiêu",
    "keywords": [
      "giá bao nhiêu",
      "xin giá",
      "bao nhiêu tiền",
      "giá sản phẩm",
      "giá nhiêu",
      "bn tiền",
      "bn vậy",
      "bao nhiêu k",
      "bao nhiu",
      "bnh",
      "b.nhiêu",
      "ib giá",
      "ib xin giá",
      "inbox giá",
      "check giá",
      "xin giá shop",
      "giá ib",
      "giá ib mình",
      "giá sp",
      "giá sx",
      "price",
      "pri",
      "bao giá",
      "giá sao",
      "gia bao nhieu",
      "xin gia",
      "bao nhieu tien",
      "gia san pham"
    ],
    "replyText": "Dạ giá thì mình hỏi thẳng luôn nha 😄 Anh chị gửi tên hoặc mã sản phẩm, em kiểm tra đúng mẫu rồi báo thông tin hiện tại ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_8",
    "name": "Giá hiện tại",
    "keywords": [
      "giá hiện tại",
      "giá hôm nay",
      "giá mới nhất",
      "giá bao nhiêu vậy",
      "giá nhiêu",
      "bn tiền",
      "bn vậy",
      "bao nhiêu k",
      "bao nhiu",
      "bnh",
      "b.nhiêu",
      "ib giá",
      "ib xin giá",
      "inbox giá",
      "check giá",
      "xin giá shop",
      "giá ib",
      "giá ib mình",
      "giá sp",
      "giá sx",
      "price",
      "pri",
      "bao giá",
      "giá sao",
      "giá nay",
      "giá hn",
      "giá hiện giờ",
      "giá mới",
      "giá update",
      "giá live hôm nay",
      "giá chốt hôm nay",
      "giá sau sale",
      "giá sau mã",
      "gia hien tai",
      "gia hom nay",
      "gia moi nhat",
      "gia bao nhieu vay"
    ],
    "replyText": "Giá hiện tại mình kiểm tra cho chuẩn nha, khỏi đoán mò 😄 Anh chị gửi tên/mã sản phẩm, em xem đúng phiên bản và thông tin đang áp dụng ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_9",
    "name": "Còn hàng không",
    "keywords": [
      "còn hàng không",
      "có hàng không",
      "hết hàng chưa",
      "còn không",
      "còn sp ko",
      "còn ko shop",
      "còn hàng k",
      "còn hàng khum",
      "còn mẫu ko",
      "còn mẫu k",
      "còn size không",
      "còn màu không",
      "available không",
      "có sẵn ko",
      "stock không",
      "check tồn",
      "check kho",
      "out",
      "out hàng",
      "outstock",
      "hết sp",
      "hết mẫu",
      "cháy hàng",
      "sold out",
      "sold",
      "hết size",
      "hết màu",
      "bao giờ restock",
      "restock khi nào",
      "nhập lại chưa",
      "con hang khong",
      "co hang khong",
      "het hang chua",
      "con khong"
    ],
    "replyText": "Để em ngó kho cho mình nha 😄 Gửi tên/mẫu, màu hoặc size cần tìm, em kiểm tra đúng phiên bản ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_10",
    "name": "Hết hàng",
    "keywords": [
      "hết hàng",
      "out stock",
      "hết rồi à",
      "khi nào có lại",
      "out",
      "out hàng",
      "outstock",
      "hết sp",
      "hết mẫu",
      "cháy hàng",
      "sold out",
      "sold",
      "hết size",
      "hết màu",
      "bao giờ restock",
      "restock khi nào",
      "nhập lại chưa",
      "het hang",
      "het roi a",
      "khi nao co lai"
    ],
    "replyText": "Nếu mẫu mình thích đang tạm hết thì tiếc một xíu thật 😭 Anh chị gửi tên/mã sản phẩm, em kiểm tra tình trạng và thông tin hàng lại cho mình nha!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_11",
    "name": "Màu gì",
    "keywords": [
      "màu gì",
      "có màu nào",
      "màu sắc",
      "màu nào đẹp",
      "có màu khác không",
      "màu nào",
      "màu gì vậy",
      "màu nào có",
      "có màu khác k",
      "có màu khác ko",
      "màu còn lại",
      "màu đang có",
      "list màu",
      "bảng màu",
      "màu thực tế",
      "màu ngoài đời",
      "mau gi",
      "co mau nao",
      "mau sac",
      "mau nao dep"
    ],
    "replyText": "Màu thì mình chọn theo gu nha 😄 Anh chị gửi mẫu đang xem, em kiểm tra các màu hiện có để mình lựa cho dễ ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_12",
    "name": "Size",
    "keywords": [
      "size",
      "kích thước",
      "chọn size",
      "size nào",
      "size bao nhiêu",
      "sz",
      "sz nào",
      "chọn sz",
      "size gì",
      "size có những gì",
      "bảng size",
      "size chart",
      "size chuẩn không",
      "size có rộng không",
      "size có chật không",
      "kich thuoc",
      "chon size",
      "size nao"
    ],
    "replyText": "Size phải vừa mới vui nha 😄 Anh chị gửi mẫu và thông tin cần thiết, em hỗ trợ đối chiếu theo bảng size của sản phẩm ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_13",
    "name": "Size lớn",
    "keywords": [
      "size lớn",
      "size nhỏ",
      "có size xl không",
      "có size 2xl không",
      "sz",
      "size nào",
      "sz nào",
      "chọn sz",
      "size gì",
      "size bao nhiêu",
      "size có những gì",
      "bảng size",
      "size chart",
      "size chuẩn không",
      "size có rộng không",
      "size có chật không",
      "size lon",
      "size nho",
      "co size xl khong",
      "co size 2xl khong"
    ],
    "replyText": "Size lớn có hay không còn tùy mẫu nha 😄 Gửi em tên/mã sản phẩm, em kiểm tra đúng size đang có ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_14",
    "name": "Chất liệu",
    "keywords": [
      "chất liệu",
      "làm bằng gì",
      "vật liệu",
      "vải gì",
      "chất gì",
      "material",
      "vải gì vậy",
      "chất vải",
      "chất liệu gì",
      "làm từ gì",
      "có mềm không",
      "có co giãn không",
      "có dày không",
      "có mỏng không",
      "chat lieu",
      "lam bang gi",
      "vat lieu",
      "vai gi"
    ],
    "replyText": "Chất liệu thì mình nói cho rõ, không để cả nhà đoán hình đoán chữ nha 😄 Gửi tên/mã sản phẩm, em kiểm tra thông tin chính xác ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_15",
    "name": "Nguồn gốc",
    "keywords": [
      "nguồn gốc",
      "xuất xứ",
      "sản xuất ở đâu",
      "hàng nước nào",
      "xuất xứ đâu",
      "origin",
      "made in",
      "made in đâu",
      "hàng ở đâu",
      "nhập từ đâu",
      "nhập khẩu không",
      "hàng nội địa",
      "hàng ngoại",
      "nguồn hàng",
      "nguon goc",
      "xuat xu",
      "san xuat o dau",
      "hang nuoc nao"
    ],
    "replyText": "Xuất xứ là câu hỏi rất đáng hỏi nha 😄 Anh chị gửi tên/mã sản phẩm, em kiểm tra thông tin nguồn gốc được công bố ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_16",
    "name": "Cách sử dụng",
    "keywords": [
      "cách sử dụng",
      "dùng như thế nào",
      "hướng dẫn sử dụng",
      "sử dụng ra sao",
      "xài sao",
      "xài thế nào",
      "dùng sao",
      "dùng kiểu gì",
      "cách xài",
      "hướng dẫn xài",
      "hd sử dụng",
      "how to use",
      "dùng bao lâu",
      "dùng mấy lần",
      "cach su dung",
      "dung nhu the nao",
      "huong dan su dung",
      "su dung ra sao"
    ],
    "replyText": "Cách dùng thì hỏi thoải mái nha 😄 Anh chị gửi sản phẩm đang quan tâm, em hướng dẫn từng bước cho dễ làm theo ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_17",
    "name": "Phù hợp với ai",
    "keywords": [
      "phù hợp với ai",
      "có phù hợp không",
      "dùng cho ai",
      "hợp không",
      "hợp ai",
      "dành cho ai",
      "ai dùng được",
      "nam dùng được không",
      "nữ dùng được không",
      "người lớn dùng được không",
      "trẻ em dùng được không",
      "phù hợp nhu cầu nào",
      "có hợp không",
      "phu hop voi ai",
      "co phu hop khong",
      "dung cho ai",
      "hop khong"
    ],
    "replyText": "Phù hợp hay không còn tùy nhu cầu nha 😄 Anh chị nói mình mua để làm gì, em hỗ trợ đối chiếu thông tin cho sát hơn ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_18",
    "name": "So sánh",
    "keywords": [
      "so sánh",
      "khác gì",
      "nên chọn mẫu nào",
      "khác nhau thế nào",
      "so với mẫu kia",
      "mẫu A hay B",
      "A với B khác gì",
      "khác nhau chỗ nào",
      "khác nhau sao",
      "mẫu nào hơn",
      "mẫu nào phù hợp",
      "nên lấy mẫu nào",
      "chọn cái nào",
      "compare",
      "so sánh giúp",
      "so sanh",
      "khac gi",
      "nen chon mau nao",
      "khac nhau the nao"
    ],
    "replyText": "Muốn so sánh thì mình so cho ra ngô ra khoai luôn 😄 Gửi 2 mẫu đang cân nhắc, em giúp đối chiếu các điểm khác nhau ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_19",
    "name": "Ưu điểm",
    "keywords": [
      "ưu điểm",
      "điểm mạnh",
      "có gì nổi bật",
      "nổi bật gì",
      "uu diem",
      "diem manh",
      "co gi noi bat",
      "noi bat gi"
    ],
    "replyText": "Muốn soi điểm nổi bật thì mình soi kỹ nha 😄 Gửi tên/mã sản phẩm, em tổng hợp các thông tin nổi bật đã được công bố ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_20",
    "name": "Nhược điểm",
    "keywords": [
      "nhược điểm",
      "hạn chế",
      "có điểm trừ không",
      "nhuoc diem",
      "han che",
      "co diem tru khong"
    ],
    "replyText": "Hỏi cả nhược điểm mới là người mua tỉnh táo nha 😄 Em sẽ nói cả điểm cần lưu ý để anh chị có thông tin đầy đủ trước khi quyết định ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_21",
    "name": "Bền không",
    "keywords": [
      "bền không",
      "dùng được lâu không",
      "độ bền",
      "có tốt không",
      "ben khong",
      "dung duoc lau khong",
      "do ben",
      "co tot khong"
    ],
    "replyText": "Độ bền thì mình đừng chỉ nghe mỗi chữ “bền” nha 😄 Em kiểm tra theo chất liệu, thiết kế và thông tin sản phẩm được công bố ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_22",
    "name": "Có chính hãng không",
    "keywords": [
      "có chính hãng không",
      "hàng chính hãng",
      "auth",
      "chính hãng à",
      "co chinh hang khong",
      "hang chinh hang",
      "chinh hang a"
    ],
    "replyText": "Chính hãng hay không thì mình phải có thông tin rõ ràng nha 😄 Gửi tên/mã sản phẩm, em hỗ trợ kiểm tra nguồn hàng và thông tin xác thực ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_23",
    "name": "Hàng mới không",
    "keywords": [
      "hàng mới không",
      "hàng mới",
      "sản xuất năm nào",
      "date",
      "hang moi khong",
      "hang moi",
      "san xuat nam nao"
    ],
    "replyText": "Hàng mới hay lô trước mình kiểm tra cho chắc nha 😄 Gửi tên/mã sản phẩm, em xem thông tin lô hàng hiện có ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_24",
    "name": "Đặt hàng",
    "keywords": [
      "đặt hàng",
      "mua hàng",
      "muốn mua",
      "mua như nào",
      "đặt sao",
      "mua sao",
      "mua kiểu gì",
      "đặt kiểu gì",
      "đặt như nào",
      "order sao",
      "order kiểu gì",
      "ord",
      "đặt ạ",
      "chốt mua",
      "lên đơn",
      "lên bill",
      "tạo đơn",
      "dat hang",
      "mua hang",
      "muon mua",
      "mua nhu nao"
    ],
    "replyText": "Đặt hàng thì mình làm từng bước cho chắc cú nha 😄 Gửi sản phẩm, phân loại và số lượng, em hướng dẫn đặt qua kênh chính thức ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_25",
    "name": "Chốt đơn",
    "keywords": [
      "chốt đơn",
      "chốt giúp",
      "lấy đơn này",
      "chốt cho anh chị",
      "chốt nha",
      "chốt ạ",
      "chốt giúp mình",
      "chốt đơn giúp",
      "lên đơn giúp",
      "em lấy",
      "mình lấy",
      "tôi lấy",
      "lấy mẫu này",
      "lấy cái này",
      "chốt mẫu này",
      "chốt ngay",
      "chốt luôn",
      "chot don",
      "chot giup",
      "lay don nay",
      "chot cho anh chi"
    ],
    "replyText": "Chốt đơn được nha 😄 Anh chị xác nhận sản phẩm, phân loại, số lượng và kênh đặt hàng, mình làm từng bước cho chuẩn ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_26",
    "name": "Đặt 1 cái",
    "keywords": [
      "đặt 1 cái",
      "lấy 1",
      "mua một cái",
      "dat 1 cai",
      "lay 1",
      "mua mot cai"
    ],
    "replyText": "Một cái cũng được nha, đâu cần mua cả thế giới 😄 Gửi mẫu, màu/size nếu có, em hướng dẫn đặt 1 sản phẩm ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_27",
    "name": "Mua nhiều",
    "keywords": [
      "mua nhiều",
      "số lượng lớn",
      "mua sỉ",
      "đại lý",
      "nhập sỉ",
      "lấy số lượng",
      "lấy nhiều",
      "mua số lượng lớn",
      "mua theo lô",
      "đơn số lượng lớn",
      "nhập hàng",
      "nhập số lượng",
      "lấy sỉ",
      "sỉ số lượng",
      "mua nhieu",
      "so luong lon",
      "mua si",
      "dai ly"
    ],
    "replyText": "Mua nhiều thì mình kiểm tra chính sách số lượng cho rõ nha 😄 Anh chị cho em sản phẩm và số lượng dự kiến, em hỗ trợ thông tin hiện có ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_28",
    "name": "Giá sỉ",
    "keywords": [
      "giá sỉ",
      "bảng giá sỉ",
      "chiết khấu sỉ",
      "giá đại lý",
      "giá sỉ bn",
      "sỉ bao nhiêu",
      "sỉ từ bao nhiêu",
      "mức sỉ",
      "bảng sỉ",
      "list giá sỉ",
      "giá nhập",
      "chiết khấu đại lý",
      "ck sỉ",
      "ck đại lý",
      "gia si",
      "bang gia si",
      "chiet khau si",
      "gia dai ly"
    ],
    "replyText": "Giá sỉ thì mình xem theo sản phẩm và số lượng nha 😄 Gửi mã hàng + số lượng dự kiến, em hỗ trợ kiểm tra chính sách phù hợp ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_29",
    "name": "Làm đại lý",
    "keywords": [
      "làm đại lý",
      "đăng ký đại lý",
      "cộng tác viên",
      "ctv",
      "lam dai ly",
      "dang ky dai ly",
      "cong tac vien"
    ],
    "replyText": "Muốn làm đại lý thì mình tìm hiểu chính sách trước cho chắc nha 😄 Anh chị cho em biết nhóm sản phẩm, em hướng dẫn thông tin đang được công bố ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_30",
    "name": "Voucher",
    "keywords": [
      "voucher",
      "mã giảm giá",
      "mã ưu đãi",
      "khuyến mãi",
      "sale",
      "vc",
      "vch",
      "mã vc",
      "mã voucher",
      "code giảm",
      "code sale",
      "coupon",
      "mã coupon",
      "mã giảm",
      "voucher live",
      "voucher shop",
      "voucher tiktok",
      "voucher shopee",
      "ma giam gia",
      "ma uu dai",
      "khuyen mai"
    ],
    "replyText": "Voucher nghe là thấy vui rồi đó 😄 Gửi mã voucher hoặc sản phẩm đang mua, em hỗ trợ kiểm tra điều kiện áp dụng nha!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_31",
    "name": "Mã giảm không dùng được",
    "keywords": [
      "mã giảm không dùng được",
      "voucher lỗi",
      "voucher không áp dụng",
      "vc",
      "vch",
      "mã vc",
      "mã voucher",
      "code giảm",
      "code sale",
      "coupon",
      "mã coupon",
      "mã ưu đãi",
      "mã giảm",
      "voucher live",
      "voucher shop",
      "voucher tiktok",
      "voucher shopee",
      "vc không dùng",
      "vc lỗi",
      "code lỗi",
      "mã lỗi",
      "không áp mã được",
      "áp mã không được",
      "mã bị báo lỗi",
      "voucher không nhận",
      "coupon không chạy",
      "ma giam khong dung duoc",
      "voucher loi",
      "voucher khong ap dung"
    ],
    "replyText": "Mã giảm chưa chạy thì khoan bấm tới bấm lui cho mỏi tay nha 😄 Gửi mã voucher và sản phẩm, em hướng dẫn kiểm tra điều kiện ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_32",
    "name": "Sale bao nhiêu",
    "keywords": [
      "sale bao nhiêu",
      "giảm bao nhiêu",
      "đang sale không",
      "sale ko",
      "có sale k",
      "đang sale à",
      "giảm giá không",
      "deal không",
      "deal gì",
      "deal live",
      "giá deal",
      "flash sale",
      "f-sale",
      "sale off",
      "sale bao nhieu",
      "giam bao nhieu",
      "dang sale khong"
    ],
    "replyText": "Sale bao nhiêu thì mình xem đúng chương trình đang áp dụng nha 😄 Gửi sản phẩm hoặc mã chương trình, em kiểm tra thông tin cho mình ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_33",
    "name": "Freeship",
    "keywords": [
      "freeship",
      "miễn phí ship",
      "có freeship không",
      "fs",
      "fship",
      "free ship",
      "free-ship",
      "miễn ship",
      "ship 0đ",
      "ship 0 đồng",
      "freeship đơn",
      "free ship đơn",
      "ship bn",
      "ship bao nhiêu",
      "ship bao nhiêu k",
      "tiền ship",
      "phí giao",
      "phí vc",
      "phí vận chuyển bn",
      "cước ship",
      "mien phi ship",
      "co freeship khong"
    ],
    "replyText": "Freeship thì còn tùy điều kiện đơn và khu vực nha 😄 Gửi sản phẩm + khu vực nhận hàng, em hỗ trợ kiểm tra thông tin hiện có ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_34",
    "name": "Phí ship",
    "keywords": [
      "phí ship",
      "phí vận chuyển",
      "tiền giao hàng",
      "ship bao nhiêu",
      "ship bn",
      "ship bao nhiêu k",
      "tiền ship",
      "phí giao",
      "phí vc",
      "phí vận chuyển bn",
      "cước ship",
      "phi ship",
      "phi van chuyen",
      "tien giao hang",
      "ship bao nhieu"
    ],
    "replyText": "Phí ship để em kiểm tra cho, mình khỏi ngồi đoán 😄 Anh chị cho em khu vực nhận và sản phẩm cần đặt nha!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_35",
    "name": "Bao lâu nhận được",
    "keywords": [
      "bao lâu nhận được",
      "khi nào giao",
      "thời gian giao",
      "mấy ngày tới",
      "khi nào tới",
      "bao giờ tới",
      "bao giờ nhận",
      "nhận ngày nào",
      "ETA",
      "dự kiến tới",
      "giao dự kiến",
      "ship mấy ngày",
      "đi mấy ngày",
      "bao lau nhan duoc",
      "khi nao giao",
      "thoi gian giao",
      "may ngay toi"
    ],
    "replyText": "Thời gian nhận hàng còn tùy khu vực và đơn vị vận chuyển nha 😄 Cho em khu vực nhận, em hỗ trợ kiểm tra thời gian dự kiến ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_36",
    "name": "Giao hỏa tốc",
    "keywords": [
      "giao hỏa tốc",
      "giao nhanh",
      "ship nhanh",
      "giao trong ngày",
      "hỏa tốc",
      "hoa toc",
      "HT",
      "same day",
      "giao 2h",
      "giao 4h",
      "ship gấp",
      "giao gấp",
      "giao hoa toc",
      "giao trong ngay"
    ],
    "replyText": "Hỏa tốc thì để em kiểm tra khả năng giao nhanh theo khu vực nha 😄 Gửi khu vực nhận + sản phẩm cần đặt ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_37",
    "name": "Theo dõi đơn",
    "keywords": [
      "theo dõi đơn",
      "tra cứu đơn",
      "đơn đang ở đâu",
      "kiểm tra đơn",
      "check đơn",
      "check order",
      "tra đơn",
      "tra cứu order",
      "đơn đâu rồi",
      "order đâu",
      "đơn tới đâu",
      "check vận đơn",
      "check trạng thái đơn",
      "theo doi don",
      "tra cuu don",
      "don dang o dau",
      "kiem tra don"
    ],
    "replyText": "Muốn soi hành trình đơn thì cần mã đơn nha 😄 Gửi mã qua kênh hỗ trợ chính thức, em hướng dẫn kiểm tra trạng thái ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_38",
    "name": "Mã vận đơn",
    "keywords": [
      "mã vận đơn",
      "tracking",
      "tra vận đơn",
      "mã đơn hàng",
      "mã vd",
      "mvd",
      "mã vận chuyển",
      "tracking number",
      "tracking no",
      "track đơn",
      "track order",
      "mã tracking",
      "mã ship",
      "ma van don",
      "tra van don",
      "ma don hang"
    ],
    "replyText": "Mã vận đơn chính là “chìa khóa” để soi hành trình đơn đó 😄 Gửi mã đơn/vận đơn, em hướng dẫn kiểm tra nha!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_39",
    "name": "Đơn chưa giao",
    "keywords": [
      "đơn chưa giao",
      "giao chậm",
      "shipper chưa giao",
      "chờ đơn",
      "chưa tới",
      "chưa nhận",
      "chưa giao",
      "giao lâu",
      "ship lâu",
      "trễ đơn",
      "trễ giao",
      "đơn đứng im",
      "đơn chưa chạy",
      "don chua giao",
      "giao cham",
      "shipper chua giao",
      "cho don"
    ],
    "replyText": "Đơn đi hơi lâu thì mình đừng sốt ruột một mình nha 😅 Gửi mã đơn và khu vực nhận, em hướng dẫn kiểm tra trạng thái ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_40",
    "name": "Hủy đơn",
    "keywords": [
      "hủy đơn",
      "muốn hủy",
      "hủy hàng",
      "hủy giúp",
      "huỷ đơn",
      "hủy order",
      "huỷ order",
      "cancel đơn",
      "cancel order",
      "bỏ đơn",
      "không lấy nữa",
      "không mua nữa",
      "huy don",
      "muon huy",
      "huy hang",
      "huy giup"
    ],
    "replyText": "Hủy đơn thì còn tùy trạng thái đơn nha 😄 Gửi mã đơn, em hướng dẫn kiểm tra điều kiện và cách xử lý theo kênh chính thức ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_41",
    "name": "Đổi hàng",
    "keywords": [
      "đổi hàng",
      "đổi sản phẩm",
      "đổi size",
      "đổi màu",
      "sz",
      "size nào",
      "sz nào",
      "chọn sz",
      "size gì",
      "size bao nhiêu",
      "size có những gì",
      "bảng size",
      "size chart",
      "size chuẩn không",
      "size có rộng không",
      "size có chật không",
      "đổi sp",
      "đổi mẫu",
      "đổi sz",
      "đổi hàng được không",
      "đổi sang mẫu khác",
      "doi hang",
      "doi san pham",
      "doi size",
      "doi mau"
    ],
    "replyText": "Muốn đổi hàng thì mình kiểm tra điều kiện trước nha 😄 Gửi mã đơn và tình trạng sản phẩm, em hướng dẫn quy trình ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_42",
    "name": "Trả hàng",
    "keywords": [
      "trả hàng",
      "trả sản phẩm",
      "muốn trả",
      "trả đơn",
      "trả sp",
      "trả hàng được không",
      "return",
      "return hàng",
      "hoàn trả",
      "gửi trả",
      "không nhận hàng có trả được không",
      "tra hang",
      "tra san pham",
      "muon tra",
      "tra don"
    ],
    "replyText": "Nếu cần trả hàng thì mình xử lý đúng quy trình cho gọn nha 😄 Gửi mã đơn và lý do cần trả, em hướng dẫn theo chính sách ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_43",
    "name": "Hoàn tiền",
    "keywords": [
      "hoàn tiền",
      "bao lâu hoàn tiền",
      "chưa hoàn tiền",
      "refund",
      "hoàn tiền chưa",
      "tiền hoàn đâu",
      "bao giờ hoàn",
      "khi nào hoàn",
      "chưa thấy tiền",
      "tiền về chưa",
      "hoan tien",
      "bao lau hoan tien",
      "chua hoan tien"
    ],
    "replyText": "Hoàn tiền thì mình kiểm tra theo mã đơn cho chính xác nha 😄 Gửi mã đơn qua kênh hỗ trợ chính thức để được hướng dẫn ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_44",
    "name": "Hàng lỗi",
    "keywords": [
      "hàng lỗi",
      "sản phẩm hỏng",
      "lỗi sản phẩm",
      "hàng bị lỗi",
      "lỗi sp",
      "sp lỗi",
      "hàng hư",
      "hàng hỏng",
      "lỗi kỹ thuật",
      "bị lỗi rồi",
      "không hoạt động",
      "hang loi",
      "san pham hong",
      "loi san pham",
      "hang bi loi"
    ],
    "replyText": "Hàng lỗi thì đừng tự xử lý lung tung nha 😄 Gửi mã đơn và hình ảnh/tình trạng sản phẩm qua kênh hỗ trợ, em hướng dẫn tiếp ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_45",
    "name": "Thiếu hàng",
    "keywords": [
      "thiếu hàng",
      "giao thiếu",
      "thiếu sản phẩm",
      "thiếu phụ kiện",
      "thiếu sp",
      "thiếu món",
      "thiếu đồ",
      "thiếu 1 món",
      "thiếu hàng trong đơn",
      "thieu hang",
      "giao thieu",
      "thieu san pham",
      "thieu phu kien"
    ],
    "replyText": "Thiếu hàng thì mình kiểm tra lại đơn cho rõ nha 😄 Gửi mã đơn và phần còn thiếu, em hướng dẫn cách báo hỗ trợ ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_46",
    "name": "Giao sai hàng",
    "keywords": [
      "giao sai hàng",
      "nhầm hàng",
      "sai màu",
      "sai size",
      "sz",
      "size nào",
      "sz nào",
      "chọn sz",
      "size gì",
      "size bao nhiêu",
      "size có những gì",
      "bảng size",
      "size chart",
      "size chuẩn không",
      "size có rộng không",
      "size có chật không",
      "sai sp",
      "nhầm sp",
      "nhầm mẫu",
      "nhầm màu",
      "nhầm size",
      "giao nhầm",
      "giao sai",
      "không đúng mẫu",
      "giao sai hang",
      "nham hang",
      "sai mau"
    ],
    "replyText": "Nhận sai hàng thì mình khoan dùng sản phẩm nha 😄 Gửi mã đơn và hình ảnh kiện hàng/sản phẩm, em hướng dẫn xử lý theo chính sách ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_47",
    "name": "Bảo hành",
    "keywords": [
      "bảo hành",
      "thời hạn bảo hành",
      "chính sách bảo hành",
      "bh",
      "b.hành",
      "warranty",
      "bảo hành bao lâu",
      "có bh không",
      "bh mấy tháng",
      "bh mấy năm",
      "bảo hành ở đâu",
      "bao hanh",
      "thoi han bao hanh",
      "chinh sach bao hanh"
    ],
    "replyText": "Bảo hành thì mình kiểm tra đúng mẫu cho khỏi nhầm nha 😄 Gửi tên/mã sản phẩm, em hỗ trợ thông tin thời hạn và điều kiện ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_48",
    "name": "Bảo hành ở đâu",
    "keywords": [
      "bảo hành ở đâu",
      "gửi bảo hành",
      "bảo hành thế nào",
      "bh",
      "b.hành",
      "warranty",
      "bảo hành bao lâu",
      "có bh không",
      "bh mấy tháng",
      "bh mấy năm",
      "bao hanh o dau",
      "gui bao hanh",
      "bao hanh the nao"
    ],
    "replyText": "Cần bảo hành ở đâu thì em hướng dẫn đúng kênh nha 😄 Gửi tên/mã sản phẩm và tình trạng cần hỗ trợ ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_49",
    "name": "Thanh toán",
    "keywords": [
      "thanh toán",
      "chuyển khoản",
      "thanh toán khi nhận",
      "cod",
      "tt",
      "thanh toán sao",
      "trả tiền sao",
      "pay sao",
      "thanh toán kiểu gì",
      "có chuyển khoản không",
      "ck được không",
      "thẻ được không",
      "thanh toan",
      "chuyen khoan",
      "thanh toan khi nhan"
    ],
    "replyText": "Thanh toán thì mình chọn phương thức thuận tiện nha 😄 Cho em biết nền tảng và sản phẩm, em hướng dẫn các phương thức đang áp dụng ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_50",
    "name": "Có cod không",
    "keywords": [
      "có cod không",
      "được kiểm tra hàng không",
      "xem hàng trước khi nhận",
      "COD",
      "cod không",
      "thanh toán khi nhận",
      "trả khi nhận",
      "nhận hàng trả tiền",
      "ship cod",
      "thu hộ",
      "cash on delivery",
      "co cod khong",
      "duoc kiem tra hang khong",
      "xem hang truoc khi nhan"
    ],
    "replyText": "COD có hay không còn tùy kênh và khu vực nha 😄 Gửi sản phẩm + khu vực nhận, em hỗ trợ kiểm tra thông tin hiện có ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_51",
    "name": "Inbox",
    "keywords": [
      "inbox",
      "ib",
      "nhắn riêng",
      "tư vấn riêng",
      "inb",
      "nhắn ib",
      "ib mình",
      "ib shop",
      "inbox shop",
      "pm",
      "pm shop",
      "nhắn tin riêng",
      "nhan rieng",
      "tu van rieng"
    ],
    "replyText": "Inbox được nha 😄 Mình ưu tiên kênh liên hệ chính thức để thông tin rõ ràng và tránh nhầm kênh ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_52",
    "name": "Follow",
    "keywords": [
      "follow",
      "theo dõi",
      "đã follow",
      "follow rồi",
      "fl",
      "fol",
      "fllow",
      "follow shop",
      "theo dõi shop",
      "ấn follow",
      "bấm follow",
      "đã fl",
      "fl rồi",
      "theo doi",
      "da follow",
      "follow roi"
    ],
    "replyText": "Cảm ơn anh chị đã follow nha ❤️ Ghé lại live chơi thường xuyên, có nội dung mới mình cùng xem cho vui ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_53",
    "name": "Share",
    "keywords": [
      "share",
      "chia sẻ",
      "đã chia sẻ",
      "share rồi",
      "sh",
      "share bài",
      "share live",
      "đã share",
      "chia sẻ live",
      "chia sẻ video",
      "share giúp",
      "share hộ",
      "chia se",
      "da chia se",
      "share roi"
    ],
    "replyText": "Anh chị share là em vui như được cộng thêm pin vậy đó 😄 Cảm ơn cả nhà đã lan tỏa nội dung nha!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_54",
    "name": "Tag bạn",
    "keywords": [
      "tag bạn",
      "tag người cần",
      "rủ bạn bè",
      "tag bạn bè",
      "tag",
      "tag người thân",
      "rủ bạn",
      "gắn thẻ",
      "tag hộ",
      "tag mn",
      "tag ban",
      "tag nguoi can",
      "ru ban be",
      "tag ban be"
    ],
    "replyText": "Tag bạn bè vào chơi chung cho vui nha 😄 Biết đâu người bạn ấy cũng đang quan tâm đúng nội dung này ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_55",
    "name": "Tim",
    "keywords": [
      "tim",
      "thả tim",
      "like",
      "đã like",
      "tym",
      "thả tym",
      "like rồi",
      "like live",
      "like video",
      "bấm tim",
      "tha tim",
      "da like"
    ],
    "replyText": "Tim đã nhận đủ nha ❤️ Cả nhà thả tim vui tay, em có thêm năng lượng nói chuyện tiếp nè 😄",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_56",
    "name": "Đăng ký kênh",
    "keywords": [
      "đăng ký kênh",
      "subscribe",
      "sub",
      "đã đăng ký",
      "subs",
      "đăng ký yt",
      "đk kênh",
      "đk shop",
      "đăng ký rồi",
      "bấm đăng ký",
      "dang ky kenh",
      "da dang ky"
    ],
    "replyText": "Cảm ơn anh chị đã đăng ký kênh nha ❤️ Bật thông báo nếu muốn tiện theo dõi những buổi live tiếp theo ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_57",
    "name": "Tiktok shop",
    "keywords": [
      "tiktok shop",
      "mua trên tiktok",
      "link tiktok shop",
      "tiktok",
      "ttshop",
      "TT Shop",
      "shop tt",
      "mua trên TT",
      "link TT",
      "link tiktok",
      "gian hàng TT",
      "mua tren tiktok"
    ],
    "replyText": "Muốn tìm sản phẩm trên TikTok Shop thì mình vào đúng gian hàng/kênh chính thức nha 😄 Gửi tên sản phẩm, em hướng dẫn tìm cho nhanh ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_58",
    "name": "Shopee",
    "keywords": [
      "shopee",
      "mua trên shopee",
      "link shopee",
      "gian hàng shopee",
      "shope",
      "shopee shop",
      "SP",
      "shop shopee",
      "link SP",
      "mua SP",
      "gian hàng SP",
      "mua tren shopee",
      "gian hang shopee"
    ],
    "replyText": "Muốn tìm trên Shopee thì mình kiểm tra đúng gian hàng nha 😄 Gửi tên/mã sản phẩm, em hướng dẫn cách tìm trên kênh chính thức ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_59",
    "name": "Youtube",
    "keywords": [
      "youtube",
      "video youtube",
      "kênh youtube",
      "xem youtube",
      "yt",
      "YTB",
      "youtube shop",
      "video yt",
      "link yt",
      "kênh yt",
      "xem yt",
      "subscribe yt",
      "kenh youtube"
    ],
    "replyText": "Muốn tìm video/kênh YouTube thì cho em biết tên nội dung nha 😄 Em hướng dẫn mình tìm đúng kênh để khỏi lạc giữa “rừng video” ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_60",
    "name": "Facebook",
    "keywords": [
      "facebook",
      "fanpage",
      "page",
      "xem trên facebook",
      "fb",
      "face",
      "facebook page",
      "page fb",
      "link fb",
      "trang fb",
      "inbox fb",
      "xem tren facebook"
    ],
    "replyText": "Muốn tìm Facebook thì cho em tên trang/nội dung nha 😄 Em hướng dẫn mình tìm đúng trang chính thức ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_61",
    "name": "Livestream",
    "keywords": [
      "livestream",
      "live bán hàng",
      "đang live",
      "live không",
      "live",
      "liv",
      "lives",
      "đang livestream",
      "phát live",
      "bật live",
      "live shop",
      "live ở đâu",
      "live ban hang",
      "dang live",
      "live khong"
    ],
    "replyText": "Đang live thì cả nhà cứ mạnh dạn hỏi nha 😄 Giá, mẫu, cách dùng hay thông tin sản phẩm cứ comment, em hỗ trợ từng câu ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_62",
    "name": "Mấy giờ live",
    "keywords": [
      "mấy giờ live",
      "lịch livestream",
      "khi nào live",
      "lịch live",
      "live",
      "liv",
      "lives",
      "đang live",
      "đang livestream",
      "phát live",
      "bật live",
      "live bán hàng",
      "live shop",
      "live ở đâu",
      "giờ live",
      "time live",
      "live lúc mấy",
      "live mấy giờ",
      "bao giờ live",
      "tối nay live không",
      "mai live không",
      "ngày nào live",
      "may gio live",
      "lich livestream",
      "khi nao live",
      "lich live"
    ],
    "replyText": "Lịch live thì mình xem đúng thông báo của kênh nha 😄 Anh chị muốn biết buổi nào thì cho em biết, em hỗ trợ kiểm tra thông tin đã công bố ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_63",
    "name": "Có livestream không",
    "keywords": [
      "có livestream không",
      "xem live ở đâu",
      "link live",
      "live",
      "liv",
      "lives",
      "đang live",
      "đang livestream",
      "phát live",
      "bật live",
      "live bán hàng",
      "live shop",
      "live ở đâu",
      "có live không",
      "vào live kiểu gì",
      "join live",
      "tham gia live",
      "live trên nền tảng nào",
      "co livestream khong",
      "xem live o dau"
    ],
    "replyText": "Có live hay không thì mình theo dõi lịch chính thức nha 😄 Cho em biết nền tảng đang xem để em hướng dẫn tìm đúng kênh ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_64",
    "name": "Ghim bình luận",
    "keywords": [
      "ghim bình luận",
      "ghim comment",
      "pin comment",
      "pin cmt",
      "ghim cmt",
      "pinned comment",
      "pin cmt sao",
      "ghim cmt sao",
      "ghim binh luan"
    ],
    "replyText": "Ghim comment thì làm được nha 😄 Cho em biết đang live trên nền tảng nào, em hướng dẫn đúng thao tác cho khỏi bấm nhầm ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_65",
    "name": "Không nghe tiếng",
    "keywords": [
      "không nghe tiếng",
      "mất tiếng",
      "âm thanh nhỏ",
      "live không có tiếng",
      "mất âm",
      "mất audio",
      "audio không nghe",
      "không có audio",
      "mic mất tiếng",
      "không nghe được",
      "live im re",
      "live không âm thanh",
      "khong nghe tieng",
      "mat tieng",
      "am thanh nho",
      "live khong co tieng"
    ],
    "replyText": "Không nghe tiếng thì bình tĩnh nha 😄 Mình kiểm tra âm lượng, quyền micro/tai nghe và kết nối trước; vẫn chưa được thì gửi em tình trạng cụ thể ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_66",
    "name": "Mic không lên",
    "keywords": [
      "mic không lên",
      "micro không hoạt động",
      "lỗi mic",
      "không nhận mic",
      "mic",
      "micro",
      "mic lỗi",
      "mic ko lên",
      "micro ko nhận",
      "mic không hoạt động",
      "mic bị tắt",
      "mic khong len",
      "micro khong hoat dong",
      "loi mic",
      "khong nhan mic"
    ],
    "replyText": "Mic không lên thì mình “gọi” em kiểm tra cùng nha 😄 Kiểm tra quyền micro, thiết bị đầu vào rồi thử kết nối lại trước khi live ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_67",
    "name": "Không thấy hình",
    "keywords": [
      "không thấy hình",
      "màn hình đen",
      "video bị đen",
      "camera không lên",
      "mất hình",
      "không có hình",
      "đen màn hình",
      "cam không lên",
      "camera lỗi",
      "video đen",
      "khong thay hinh",
      "man hinh den",
      "video bi den",
      "camera khong len"
    ],
    "replyText": "Màn hình đen thì khoan hoảng nha 😄 Kiểm tra quyền camera, nguồn camera, ánh sáng và mạng; cần thì khởi động lại ứng dụng ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_68",
    "name": "Live bị lag",
    "keywords": [
      "live bị lag",
      "livestream giật",
      "live bị đứng",
      "hình bị giật",
      "live",
      "liv",
      "lives",
      "đang live",
      "đang livestream",
      "phát live",
      "bật live",
      "live bán hàng",
      "live shop",
      "live ở đâu",
      "lag",
      "lắc",
      "giật lag",
      "delay",
      "trễ hình",
      "đứng hình",
      "buffer",
      "loading",
      "live chậm",
      "live giật",
      "live bi lag",
      "livestream giat",
      "live bi dung",
      "hinh bi giat"
    ],
    "replyText": "Live lag là cảm giác hơi “đứng hình mất 5 giây” đó nha 😅 Anh chị thử kiểm tra mạng, ứng dụng chạy nền và chất lượng phát trước ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_69",
    "name": "Mạng yếu",
    "keywords": [
      "mạng yếu",
      "mạng chập chờn",
      "wifi yếu",
      "mạng lag",
      "4G yếu",
      "5G yếu",
      "mất mạng",
      "rớt mạng",
      "ping cao",
      "internet yếu",
      "mang yeu",
      "mang chap chon",
      "wifi yeu",
      "mang lag"
    ],
    "replyText": "Mạng yếu thì live cũng dễ “đi chậm hơn cảm xúc” lắm nha 😄 Thử đổi sang kết nối ổn định hơn và giảm thiết bị dùng chung mạng ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_70",
    "name": "Không vào được live",
    "keywords": [
      "không vào được live",
      "không xem được live",
      "lỗi vào live",
      "không join được",
      "không mở live",
      "live không vào",
      "vào live lỗi",
      "không xem live được",
      "không truy cập live",
      "khong vao duoc live",
      "khong xem duoc live",
      "loi vao live"
    ],
    "replyText": "Không vào được live thì mình kiểm tra từng bước nha 😄 Cho em nền tảng, thiết bị và thông báo lỗi nếu có, em hướng dẫn tiếp ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_71",
    "name": "Live bị out",
    "keywords": [
      "live bị out",
      "bị văng live",
      "mất kết nối live",
      "văng live",
      "out live",
      "bị đá ra",
      "bị thoát live",
      "rớt live",
      "dis live",
      "mất live",
      "live tự tắt",
      "live bi out",
      "bi vang live",
      "mat ket noi live"
    ],
    "replyText": "Live bị out thì hơi tụt mood thật 😅 Kiểm tra mạng, nguồn điện và ứng dụng rồi thử vào lại; nếu còn lỗi gửi em thông tin cụ thể nha!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_72",
    "name": "Ít người xem",
    "keywords": [
      "ít người xem",
      "view thấp",
      "không có người xem",
      "ít view",
      "tụt view",
      "0 view",
      "no view",
      "không có view",
      "view lẹt đẹt",
      "view ít quá",
      "it nguoi xem",
      "view thap",
      "khong co nguoi xem",
      "it view"
    ],
    "replyText": "View thấp thì khoan tự trách mình nha 😄 Mình có thể rà lại phần mở đầu, chủ đề, tiêu đề, thời điểm live và cách tạo tương tác để cải thiện ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_73",
    "name": "Nhiều view ít comment",
    "keywords": [
      "nhiều view ít comment",
      "ít tương tác",
      "khách không hỏi",
      "view nhiều cmt ít",
      "view cao không comment",
      "ít cmt",
      "cmt ít",
      "không ai cmt",
      "tương tác thấp",
      "engagement thấp",
      "nhieu view it comment",
      "it tuong tac",
      "khach khong hoi"
    ],
    "replyText": "Nhiều view mà ít comment thì khán giả đang “ngồi xem trong im lặng” đó 😄 Thử đặt câu hỏi thật dễ trả lời và gắn với nội dung đang nói ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_74",
    "name": "Không ai nói gì",
    "keywords": [
      "không ai nói gì",
      "phòng live im lặng",
      "không có tương tác",
      "phòng live im",
      "im re",
      "không ai chat",
      "không ai tương tác",
      "live vắng",
      "phòng vắng",
      "khách im",
      "khách không nói",
      "khong ai noi gi",
      "phong live im lang",
      "khong co tuong tac"
    ],
    "replyText": "Phòng live im re thì mình chủ động phá băng nha 😄 Đặt câu hỏi dễ trả lời, chia sẻ mẹo ngắn hoặc mời giao lưu tự nhiên ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_75",
    "name": "Khách vào rồi ra",
    "keywords": [
      "khách vào rồi ra",
      "người xem thoát",
      "tụt view",
      "vào ra liên tục",
      "khách thoát",
      "viewer thoát",
      "tụt người xem",
      "rớt viewer",
      "khách vào rồi out",
      "người xem bỏ đi",
      "khach vao roi ra",
      "nguoi xem thoat",
      "tut view"
    ],
    "replyText": "Khách vừa vào đã ra thì mình xem lại 5–10 giây đầu nha 😄 Nói ngay mình đang chia sẻ gì và người xem nhận được gì để họ dễ quyết định ở lại ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_76",
    "name": "Khách hỏi xong im",
    "keywords": [
      "khách hỏi xong im",
      "seen không trả lời",
      "khách mất hút",
      "seen rồi im",
      "seen không rep",
      "khách im luôn",
      "hỏi xong mất",
      "không phản hồi",
      "không trả lời",
      "khách bặt vô âm tín",
      "khach hoi xong im",
      "seen khong tra loi",
      "khach mat hut"
    ],
    "replyText": "Khách hỏi xong im thì đừng “réo” liên tục nha 😄 Trả lời ngắn, đúng nhu cầu rồi để khách có thời gian cân nhắc ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_77",
    "name": "Khách đang phân vân",
    "keywords": [
      "khách đang phân vân",
      "để suy nghĩ",
      "chưa quyết định",
      "suy nghĩ thêm",
      "cân nhắc",
      "để xem đã",
      "tham khảo thêm",
      "chưa chốt",
      "chưa quyết",
      "phân vân quá",
      "khach dang phan van",
      "de suy nghi",
      "chua quyet dinh"
    ],
    "replyText": "Phân vân là bình thường nha 😄 Mình hỏi nhẹ xem còn băn khoăn về giá, nhu cầu hay thông tin nào rồi hỗ trợ đúng điểm đó ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_78",
    "name": "Khách chê đắt",
    "keywords": [
      "khách chê đắt",
      "giá cao quá",
      "mắc quá",
      "đắt vậy",
      "mắc",
      "đắt quá",
      "giá cao",
      "cao quá",
      "hơi cao",
      "giá mắc",
      "khach che dat",
      "gia cao qua",
      "mac qua",
      "dat vay"
    ],
    "replyText": "Chê đắt thì mình đừng đôi co nha 😄 Hỏi nhu cầu và ngân sách, rồi cung cấp thông tin sản phẩm/ưu đãi hiện có để khách tự cân nhắc ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_79",
    "name": "Có bớt không",
    "keywords": [
      "có bớt không",
      "giảm thêm không",
      "xin giá tốt",
      "bớt giá",
      "bớt không",
      "giảm thêm",
      "giảm nữa",
      "fix giá",
      "fix thêm",
      "deal thêm",
      "xin deal",
      "giá mềm hơn không",
      "chốt giá tốt",
      "co bot khong",
      "giam them khong",
      "xin gia tot",
      "bot gia"
    ],
    "replyText": "Muốn bớt thêm thì để em kiểm tra chính sách trước nha 😄 Cho em sản phẩm và số lượng, em xem ưu đãi hiện có ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_80",
    "name": "Đắt hơn chỗ khác",
    "keywords": [
      "đắt hơn chỗ khác",
      "bên kia rẻ hơn",
      "chỗ khác rẻ",
      "shop khác rẻ",
      "chỗ khác rẻ hơn",
      "giá đối thủ",
      "so giá",
      "giá bên khác",
      "nơi khác rẻ",
      "dat hon cho khac",
      "ben kia re hon",
      "cho khac re"
    ],
    "replyText": "So giá chỗ khác là chuyện bình thường nha 😄 Gửi hai mẫu đang so, mình đối chiếu cùng phiên bản, thông tin và chính sách cho rõ ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_81",
    "name": "Có quà tặng không",
    "keywords": [
      "có quà tặng không",
      "tặng gì",
      "được tặng không",
      "quà gì",
      "có quà không",
      "được tặng gì",
      "free quà",
      "quà kèm",
      "gift",
      "tặng kèm",
      "co qua tang khong",
      "tang gi",
      "duoc tang khong"
    ],
    "replyText": "Quà tặng thì mình kiểm tra đúng chương trình nha 😄 Gửi sản phẩm đang quan tâm, em xem điều kiện và quà tặng hiện có ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_82",
    "name": "Combo",
    "keywords": [
      "combo",
      "mua combo",
      "set",
      "bộ sản phẩm",
      "combo gì",
      "set gì",
      "mua set",
      "combo giá",
      "set giá",
      "mua bộ",
      "combo tiết kiệm",
      "bo san pham"
    ],
    "replyText": "Combo là kiểu “đi cùng nhau cho vui” đó 😄 Cho em biết nhu cầu, em hỗ trợ xem các bộ/combo đang có để mình dễ so sánh ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_83",
    "name": "Mua 2 cái",
    "keywords": [
      "mua 2 cái",
      "mua 3 cái",
      "mua nhiều có giảm không",
      "lấy số lượng",
      "lấy nhiều",
      "mua số lượng lớn",
      "mua theo lô",
      "đơn số lượng lớn",
      "nhập hàng",
      "nhập số lượng",
      "nhập sỉ",
      "lấy sỉ",
      "sỉ số lượng",
      "mua 2",
      "lấy 2",
      "2 sp",
      "2 cái",
      "mua 3",
      "lấy 3",
      "mua nhiều có giảm",
      "số lượng có ưu đãi",
      "mua 2 cai",
      "mua 3 cai",
      "mua nhieu co giam khong"
    ],
    "replyText": "Mua 2–3 cái thì mình kiểm tra ưu đãi theo số lượng nha 😄 Nói sản phẩm và số lượng dự kiến, em hỗ trợ thông tin hiện có ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_84",
    "name": "Khách chỉ xem",
    "keywords": [
      "khách chỉ xem",
      "vào giao lưu",
      "không biết hỏi gì",
      "xem thôi",
      "ngồi xem",
      "chỉ xem",
      "ghé xem",
      "lướt qua",
      "vào xem",
      "đang xem live",
      "xem live thôi",
      "chưa biết hỏi",
      "không biết nói gì",
      "hỏi gì giờ",
      "nên hỏi gì",
      "có gì hỏi đâu",
      "khach chi xem",
      "vao giao luu",
      "khong biet hoi gi"
    ],
    "replyText": "Chỉ xem thôi cũng hoàn toàn được nha 😄 Cứ ngồi chơi, nghe thông tin, thấy gì cần hỏi thì comment; không cần ngại đâu ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_85",
    "name": "Mới vào live",
    "keywords": [
      "mới vào live",
      "mới vào",
      "vừa vào xem",
      "vừa vào",
      "new viewer",
      "mới ghé",
      "mới vô",
      "vừa vô live",
      "moi vao live",
      "moi vao",
      "vua vao xem"
    ],
    "replyText": "Mới vào là em chào cái đã nha 👋 Cả nhà cứ xem thoải mái, cần biết giá, mẫu hay cách đặt thì gọi em một tiếng!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_86",
    "name": "Đang xem",
    "keywords": [
      "đang xem",
      "xem thôi",
      "ngồi xem",
      "đang coi",
      "đang xem nè",
      "xem nè",
      "coi live",
      "coi thôi",
      "đang theo dõi",
      "dang xem",
      "xem thoi",
      "ngoi xem"
    ],
    "replyText": "Đang xem là tốt rồi nha 😄 Cứ thong thả theo dõi, có câu nào thắc mắc thì comment, em bắt sóng cho ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_87",
    "name": "Không biết hỏi gì",
    "keywords": [
      "không biết hỏi gì",
      "chỉ xem thôi",
      "ghé qua xem",
      "chưa biết hỏi",
      "không biết nói gì",
      "hỏi gì giờ",
      "nên hỏi gì",
      "có gì hỏi đâu",
      "khong biet hoi gi",
      "chi xem thoi",
      "ghe qua xem"
    ],
    "replyText": "Không biết hỏi gì thì cứ hỏi câu đơn giản nhất: “Mẫu này là gì vậy?” 😄 Từ đó em với cả nhà nói chuyện tiếp nha!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_88",
    "name": "Không biết nói gì khi live",
    "keywords": [
      "không biết nói gì khi live",
      "bí nội dung",
      "bí câu nói",
      "khong biet noi gi khi live",
      "bi noi dung",
      "bi cau noi"
    ],
    "replyText": "Bí lời khi live là chuyện rất hay gặp nha 😄 Cứ theo khung: chào → chủ đề → lợi ích → trả lời → tương tác; nói tự nhiên là được ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_89",
    "name": "Kịch bản livestream",
    "keywords": [
      "kịch bản livestream",
      "viết kịch bản live",
      "script live",
      "live",
      "liv",
      "lives",
      "đang live",
      "đang livestream",
      "phát live",
      "bật live",
      "live bán hàng",
      "live shop",
      "live ở đâu",
      "script livestream",
      "kịch bản bán hàng live",
      "mẫu kịch bản live",
      "content live",
      "nội dung live",
      "outline live",
      "kich ban livestream",
      "viet kich ban live"
    ],
    "replyText": "Cần kịch bản live thì mình chia từng đoạn cho dễ nói nha 😄 Mở đầu, nội dung chính, tương tác, xử lý câu hỏi và kết thúc đều có thể chuẩn bị trước ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_90",
    "name": "Câu mở đầu livestream",
    "keywords": [
      "câu mở đầu livestream",
      "hook livestream",
      "mở đầu live",
      "live",
      "liv",
      "lives",
      "đang live",
      "đang livestream",
      "phát live",
      "bật live",
      "live bán hàng",
      "live shop",
      "live ở đâu",
      "hook",
      "hook live",
      "mở hook",
      "câu hook",
      "mở đầu bán hàng",
      "câu mở đầu live",
      "intro live",
      "cau mo dau livestream",
      "mo dau live"
    ],
    "replyText": "Hook đầu live nên ngắn, rõ và có lý do để người xem ở lại nha 😄 Đừng vòng vo quá lâu, khán giả lướt nhanh lắm đó ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_91",
    "name": "Kêu gọi tương tác",
    "keywords": [
      "kêu gọi tương tác",
      "kêu gọi comment",
      "CTA",
      "gọi comment",
      "call to action",
      "kêu cmt",
      "gọi cmt",
      "mời comment",
      "mời tương tác",
      "nhắc khách cmt",
      "kêu like",
      "keu goi tuong tac",
      "keu goi comment",
      "goi comment"
    ],
    "replyText": "Kêu gọi comment thì hỏi câu dễ trả lời nha 😄 Ví dụ: “Ai muốn xem mẫu này comment 1”, miễn là đúng với nội dung đang chia sẻ ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_92",
    "name": "Câu hỏi tương tác",
    "keywords": [
      "câu hỏi tương tác",
      "hỏi khách trên live",
      "tạo comment",
      "câu hỏi live",
      "hỏi tương tác",
      "câu hỏi cho khách",
      "hỏi gì trên live",
      "câu hỏi kéo cmt",
      "câu hỏi khách hàng",
      "cau hoi tuong tac",
      "hoi khach tren live",
      "tao comment"
    ],
    "replyText": "Câu hỏi tương tác càng dễ trả lời càng tốt nha 😄 Có thể hỏi A/B, màu, mẫu hoặc nhu cầu để mọi người tham gia tự nhiên ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_93",
    "name": "Giữ chân người xem",
    "keywords": [
      "giữ chân người xem",
      "tăng thời gian xem",
      "giữ view",
      "giữ chân khách",
      "giữ viewer",
      "tăng watch time",
      "không để khách thoát",
      "giu chan nguoi xem",
      "tang thoi gian xem",
      "giu view"
    ],
    "replyText": "Muốn giữ chân người xem thì đừng để live chạy một mạch nha 😄 Chia thành phần nhỏ, có thông tin mới và báo trước sắp chia sẻ gì ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_94",
    "name": "Tăng comment",
    "keywords": [
      "tăng comment",
      "tăng tương tác",
      "kéo tương tác",
      "kéo cmt",
      "kéo comment",
      "tăng cmt",
      "tăng bình luận",
      "nhiều cmt",
      "tăng engagement",
      "tang comment",
      "tang tuong tac",
      "keo tuong tac"
    ],
    "replyText": "Muốn tăng comment thì tạo lý do để người ta muốn nói nha 😄 Hỏi ngắn, dễ trả lời, liên quan trực tiếp nội dung; đừng hỏi dồn dập quá ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_95",
    "name": "Chốt đơn trên live",
    "keywords": [
      "chốt đơn trên live",
      "khách muốn mua trong live",
      "chốt nha",
      "chốt ạ",
      "chốt giúp mình",
      "chốt đơn giúp",
      "lên đơn giúp",
      "em lấy",
      "mình lấy",
      "tôi lấy",
      "lấy mẫu này",
      "lấy cái này",
      "chốt mẫu này",
      "chốt ngay",
      "chốt luôn",
      "chốt live",
      "chốt ngay trên live",
      "order live",
      "đặt hàng trên live",
      "mua ngay live",
      "chốt đơn live",
      "chot don tren live",
      "khach muon mua trong live"
    ],
    "replyText": "Chốt đơn thì mình chốt rõ ràng, nhẹ nhàng nha 😄 Xác nhận sản phẩm, phân loại, số lượng và hướng dẫn đặt qua kênh chính thức là gọn nhất ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_96",
    "name": "Khách hỏi giá trên live",
    "keywords": [
      "khách hỏi giá trên live",
      "giá live",
      "giá trên livestream",
      "live",
      "liv",
      "lives",
      "đang live",
      "đang livestream",
      "phát live",
      "bật live",
      "live bán hàng",
      "live shop",
      "live ở đâu",
      "giá live bn",
      "live price",
      "giá trong live",
      "giá lúc live",
      "giá chốt live",
      "khach hoi gia tren live",
      "gia live",
      "gia tren livestream"
    ],
    "replyText": "Giá live thì cho em đúng mẫu/phân loại nha 😄 Em kiểm tra giá và ưu đãi đang áp dụng, mình khỏi đoán giá trong comment ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_97",
    "name": "Khách hỏi còn hàng trên live",
    "keywords": [
      "khách hỏi còn hàng trên live",
      "live còn hàng không",
      "còn sp ko",
      "còn ko shop",
      "còn hàng k",
      "còn hàng khum",
      "còn mẫu ko",
      "còn mẫu k",
      "còn size không",
      "còn màu không",
      "available không",
      "có sẵn ko",
      "stock không",
      "check tồn",
      "check kho",
      "còn mẫu live",
      "còn size live",
      "còn màu live",
      "check tồn live",
      "khach hoi con hang tren live",
      "live con hang khong"
    ],
    "replyText": "Còn hàng live thì để em kiểm tra đúng mẫu nha 😄 Gửi màu/size/phân loại cần tìm, em hỗ trợ thông tin hiện có ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_98",
    "name": "Khách hỏi ship trên live",
    "keywords": [
      "khách hỏi ship trên live",
      "ship live",
      "phí ship trên live",
      "ship bn",
      "ship bao nhiêu",
      "ship bao nhiêu k",
      "tiền ship",
      "phí giao",
      "phí vc",
      "phí vận chuyển bn",
      "cước ship",
      "phí ship live",
      "ship bao nhiêu live",
      "freeship live",
      "giao hàng live",
      "khach hoi ship tren live",
      "phi ship tren live"
    ],
    "replyText": "Phí ship trên live thì mình cần khu vực nhận nha 😄 Cho em khu vực + sản phẩm, em hỗ trợ kiểm tra thông tin vận chuyển ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_99",
    "name": "Khách hỏi nguồn gốc trên live",
    "keywords": [
      "khách hỏi nguồn gốc trên live",
      "xuất xứ trên live",
      "xuất xứ đâu",
      "origin",
      "made in",
      "made in đâu",
      "hàng ở đâu",
      "nhập từ đâu",
      "nhập khẩu không",
      "hàng nội địa",
      "hàng ngoại",
      "nguồn hàng",
      "xuất xứ live",
      "nguồn gốc live",
      "made in live",
      "hàng ở đâu live",
      "khach hoi nguon goc tren live",
      "xuat xu tren live"
    ],
    "replyText": "Muốn biết nguồn gốc trên live thì hỏi chuẩn luôn nha 😄 Gửi tên/mã sản phẩm, em kiểm tra thông tin xuất xứ được công bố ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_100",
    "name": "Khách hỏi chất liệu trên live",
    "keywords": [
      "khách hỏi chất liệu trên live",
      "vải gì trên live",
      "chất gì",
      "material",
      "vải gì",
      "vải gì vậy",
      "chất vải",
      "chất liệu gì",
      "làm từ gì",
      "có mềm không",
      "có co giãn không",
      "có dày không",
      "có mỏng không",
      "chất liệu live",
      "vải live",
      "chất vải live",
      "làm bằng gì live",
      "khach hoi chat lieu tren live",
      "vai gi tren live"
    ],
    "replyText": "Chất liệu thì mình nói cho rõ, không để cả nhà “đoán hình đoán chữ” nha 😄 Gửi mẫu/mã sản phẩm, em kiểm tra thông tin ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_101",
    "name": "Khách hỏi cách dùng trên live",
    "keywords": [
      "khách hỏi cách dùng trên live",
      "sử dụng thế nào trên live",
      "cách dùng live",
      "dùng sao live",
      "hướng dẫn live",
      "xài sao live",
      "khach hoi cach dung tren live",
      "su dung the nao tren live"
    ],
    "replyText": "Cách dùng thì em hướng dẫn ngay trong nội dung live được nha 😄 Nói sản phẩm nào, em trình bày từng bước cho dễ theo dõi ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_102",
    "name": "Khách hỏi có tốt không",
    "keywords": [
      "khách hỏi có tốt không",
      "dùng tốt không",
      "đáng mua không",
      "tốt không",
      "ok không",
      "ổn không",
      "xài ổn không",
      "có đáng không",
      "đáng tiền không",
      "có nên mua không",
      "khach hoi co tot khong",
      "dung tot khong",
      "dang mua khong"
    ],
    "replyText": "“Có tốt không?” là câu hỏi rất thực tế nha 😄 Em sẽ dựa vào nhu cầu và thông tin sản phẩm để anh chị tự đánh giá mức phù hợp ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_103",
    "name": "Khách hỏi bảo hành trên live",
    "keywords": [
      "khách hỏi bảo hành trên live",
      "bảo hành live",
      "bh",
      "b.hành",
      "warranty",
      "bảo hành bao lâu",
      "có bh không",
      "bh mấy tháng",
      "bh mấy năm",
      "bảo hành ở đâu",
      "bh live",
      "live có bh không",
      "bh mấy tháng live",
      "khach hoi bao hanh tren live",
      "bao hanh live"
    ],
    "replyText": "Bảo hành trên live thì mình kiểm tra đúng mẫu nha 😄 Gửi tên/mã sản phẩm, em hỗ trợ thông tin thời hạn và điều kiện được công bố ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_104",
    "name": "Khách hỏi đổi trả trên live",
    "keywords": [
      "khách hỏi đổi trả trên live",
      "đổi trả live",
      "return live",
      "đổi size live",
      "trả hàng live",
      "khach hoi doi tra tren live",
      "doi tra live"
    ],
    "replyText": "Đổi trả thì mình kiểm tra đúng điều kiện trước nha 😄 Gửi sản phẩm hoặc mã đơn, em hướng dẫn quy trình theo chính sách ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_105",
    "name": "Khách hỏi thanh toán trên live",
    "keywords": [
      "khách hỏi thanh toán trên live",
      "trả tiền thế nào",
      "tt",
      "thanh toán sao",
      "trả tiền sao",
      "pay sao",
      "thanh toán kiểu gì",
      "có chuyển khoản không",
      "ck được không",
      "thẻ được không",
      "tt live",
      "thanh toán live",
      "cod live",
      "ck live",
      "trả tiền live",
      "khach hoi thanh toan tren live",
      "tra tien the nao"
    ],
    "replyText": "Thanh toán thì mình chọn phương thức thuận tiện nha 😄 Cho em nền tảng và sản phẩm, em hướng dẫn đúng thao tác ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_106",
    "name": "Khách muốn link",
    "keywords": [
      "khách muốn link",
      "gửi link",
      "link sản phẩm",
      "link mua",
      "xin link",
      "link đâu",
      "link với",
      "link sp",
      "link mua hàng",
      "link đặt hàng",
      "cho xin link",
      "khach muon link",
      "gui link",
      "link san pham"
    ],
    "replyText": "Muốn link thì có hướng dẫn tìm nha 😄 Gửi tên/mã sản phẩm, em chỉ cách vào đúng sản phẩm trên kênh chính thức ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_107",
    "name": "Khách xin số điện thoại",
    "keywords": [
      "khách xin số điện thoại",
      "xin zalo",
      "xin liên hệ",
      "sđt",
      "sdt",
      "số đt",
      "xin số",
      "xin phone",
      "zalo không",
      "contact",
      "liên hệ",
      "khach xin so dien thoai",
      "xin lien he"
    ],
    "replyText": "Về số điện thoại/Zalo, mình ưu tiên thông tin liên hệ chính thức nha 😄 Xem phần thông tin được công bố trên gian hàng/trang chính thức để tránh nhầm kênh ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_108",
    "name": "Khách spam",
    "keywords": [
      "khách spam",
      "spam comment",
      "comment liên tục",
      "spam",
      "spam cmt",
      "spamm",
      "cmt liên tục",
      "bình luận liên tục",
      "flood cmt",
      "khach spam",
      "comment lien tuc"
    ],
    "replyText": "Comment nhiều quá thì em xin phép bắt từng câu nha 😄 Gửi một câu hỏi rõ nhất trước, em xử lý lần lượt để khỏi sót thông tin ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_109",
    "name": "Bình luận không liên quan",
    "keywords": [
      "bình luận không liên quan",
      "comment linh tinh",
      "nói chuyện ngoài lề",
      "off topic",
      "ngoài lề",
      "hỏi ngoài chủ đề",
      "comment ngoài chủ đề",
      "nói chuyện khác",
      "hỏi chuyện khác",
      "binh luan khong lien quan",
      "noi chuyen ngoai le"
    ],
    "replyText": "Nếu comment lệch chủ đề một chút thì mình kéo nhẹ về nội dung live nha 😄 Bên em ưu tiên câu hỏi liên quan để hỗ trợ mọi người nhanh hơn ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_110",
    "name": "Câu hỏi không rõ",
    "keywords": [
      "câu hỏi không rõ",
      "không hiểu khách hỏi gì",
      "hỏi gì vậy",
      "không hiểu",
      "ý gì",
      "ý là sao",
      "không rõ câu hỏi",
      "viết gì vậy",
      "khó hiểu",
      "cau hoi khong ro",
      "khong hieu khach hoi gi",
      "hoi gi vay"
    ],
    "replyText": "Em chưa bắt được ý câu này rồi 😄 Anh chị nói lại giúp em một chút: mình đang hỏi giá, mẫu, cách dùng hay đơn hàng ạ?",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_111",
    "name": "Khách hỏi liên tục",
    "keywords": [
      "khách hỏi liên tục",
      "nhiều câu hỏi",
      "hỏi nhiều quá",
      "hỏi nhiều",
      "hỏi liên tục",
      "hỏi dồn",
      "hỏi liền",
      "spam hỏi",
      "khach hoi lien tuc",
      "nhieu cau hoi",
      "hoi nhieu qua"
    ],
    "replyText": "Nhiều câu hỏi là em biết cả nhà đang rất quan tâm rồi đó 😄 Mình gửi lần lượt từng ý nha, em trả lời từng câu cho dễ theo dõi ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_112",
    "name": "Khách nóng ruột",
    "keywords": [
      "khách nóng ruột",
      "trả lời nhanh",
      "sao chưa trả lời",
      "rep nhanh",
      "sao chưa rep",
      "chưa trả lời",
      "rep đâu",
      "trả lời đi",
      "shop ơi rep",
      "khach nong ruot",
      "tra loi nhanh",
      "sao chua tra loi"
    ],
    "replyText": "Đợi lâu thì dễ sốt ruột thật nha 😅 Comment đang nhiều nên em có thể phản hồi chậm một chút. Gửi lại từ khóa chính, em bắt câu cho nhanh ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_113",
    "name": "Khách phàn nàn",
    "keywords": [
      "khách phàn nàn",
      "không hài lòng",
      "thất vọng",
      "khiếu nại",
      "complaint",
      "than phiền",
      "bực",
      "không vui",
      "tệ",
      "khach phan nan",
      "khong hai long",
      "that vong"
    ],
    "replyText": "Nếu trải nghiệm chưa ổn thì anh chị cứ nói thẳng vấn đề nha. Em sẽ hỗ trợ theo thông tin cụ thể, mình cùng xử lý từng bước ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_114",
    "name": "Khách khen shop",
    "keywords": [
      "khách khen shop",
      "shop uy tín",
      "shop nhiệt tình",
      "shop tốt",
      "shop dễ thương",
      "shop có tâm",
      "phục vụ tốt",
      "khach khen shop",
      "shop uy tin",
      "shop nhiet tinh"
    ],
    "replyText": "Ôi cảm ơn lời khen của cả nhà nha ❤️ Được gọi là dễ thương là em xin phép vui nhẹ một cái rồi làm việc tiếp ạ 😄",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_115",
    "name": "Khách khen sản phẩm",
    "keywords": [
      "khách khen sản phẩm",
      "sản phẩm đẹp",
      "hàng đẹp",
      "đẹp",
      "sp đẹp",
      "xịn sò",
      "ưng",
      "ưng bụng",
      "đẹp xỉu",
      "đẹp quá trời",
      "khach khen san pham",
      "san pham dep",
      "hang dep"
    ],
    "replyText": "Nghe “ưng” là em cũng thấy vui lây rồi nha 😄 Cần xem thêm mẫu, màu, size hay thông tin nào thì cứ hỏi tiếp ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_116",
    "name": "Khách hỏi có được xem thử không",
    "keywords": [
      "khách hỏi có được xem thử không",
      "demo",
      "xem mẫu",
      "khach hoi co duoc xem thu khong",
      "xem mau"
    ],
    "replyText": "Muốn xem thử/demo thì mình xem phần trình bày đang có trên live nha 😄 Nói rõ chi tiết muốn xem, em hỗ trợ đúng phần đó ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_117",
    "name": "Khách muốn tư vấn",
    "keywords": [
      "khách muốn tư vấn",
      "tư vấn sản phẩm",
      "tư vấn giúp",
      "tư vấn",
      "tv giúp",
      "tư vấn hộ",
      "tư vấn mình",
      "tư vấn với",
      "nhờ tư vấn",
      "xin tư vấn",
      "khach muon tu van",
      "tu van san pham",
      "tu van giup"
    ],
    "replyText": "Tư vấn thì cứ đưa nhu cầu cho em nha 😄 Nói mục đích sử dụng và khoảng ngân sách nếu có, em hỗ trợ đối chiếu các lựa chọn ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_118",
    "name": "Khách chưa biết chọn gì",
    "keywords": [
      "khách chưa biết chọn gì",
      "chọn giúp",
      "tư vấn chọn mẫu",
      "chọn hộ",
      "gợi ý mẫu",
      "gợi ý giúp",
      "nên mua gì",
      "mua mẫu nào",
      "không biết chọn",
      "khach chua biet chon gi",
      "chon giup",
      "tu van chon mau"
    ],
    "replyText": "Chưa biết chọn gì thì để em hỏi ngược một chút nha 😄 Ưu tiên nhu cầu nào, khoảng giá bao nhiêu, thích kiểu gì? Có thông tin là chọn dễ hơn liền ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_119",
    "name": "Ngân sách bao nhiêu",
    "keywords": [
      "ngân sách bao nhiêu",
      "tầm giá",
      "dưới 500k",
      "dưới 1 triệu",
      "budget",
      "ngân sách",
      "dưới 1tr",
      "tầm 1 triệu",
      "khoảng giá",
      "giá dưới",
      "ngan sach bao nhieu",
      "tam gia",
      "duoi 500k",
      "duoi 1 trieu"
    ],
    "replyText": "Ngân sách bao nhiêu cũng tư vấn được nha 😄 Cho em mức dự kiến và nhu cầu, em hỗ trợ tìm các lựa chọn nằm trong khoảng đó ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_120",
    "name": "Mua làm quà",
    "keywords": [
      "mua làm quà",
      "quà tặng",
      "tặng người thân",
      "tặng quà",
      "mua tặng",
      "làm quà",
      "quà sinh nhật",
      "quà kỷ niệm",
      "quà người yêu",
      "quà bố mẹ",
      "quà bạn",
      "mua lam qua",
      "qua tang",
      "tang nguoi than"
    ],
    "replyText": "Mua quà thì chọn đúng người nhận là quan trọng nha 😄 Cho em biết người nhận, dịp tặng và ngân sách, em hỗ trợ các lựa chọn phù hợp ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_121",
    "name": "Mua cho gia đình",
    "keywords": [
      "mua cho gia đình",
      "mua cho bố mẹ",
      "mua cho người thân",
      "mua cho nhà",
      "mua cho ba mẹ",
      "cả nhà dùng",
      "gia đình dùng",
      "mua cho gia dinh",
      "mua cho bo me",
      "mua cho nguoi than"
    ],
    "replyText": "Mua cho gia đình thì mình ưu tiên nhu cầu người dùng nha 😄 Cho em biết ai sử dụng và mục đích gì, em hỗ trợ thông tin phù hợp ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_122",
    "name": "Mua cho trẻ em",
    "keywords": [
      "mua cho trẻ em",
      "cho bé",
      "trẻ nhỏ",
      "cho trẻ",
      "bé dùng",
      "con dùng",
      "em bé",
      "kids",
      "kid",
      "mua cho tre em",
      "cho be",
      "tre nho"
    ],
    "replyText": "Nếu mua cho bé thì mình càng phải xem kỹ thông tin nha 😄 Cho em độ tuổi và nhu cầu sử dụng, em hỗ trợ kiểm tra mẫu phù hợp ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_123",
    "name": "Mua cho nam",
    "keywords": [
      "mua cho nam",
      "cho nữ",
      "nam nữ đều dùng",
      "nam dùng",
      "cho nam",
      "men",
      "male",
      "con trai dùng",
      "cho nu",
      "nam nu deu dung"
    ],
    "replyText": "Nam hay nữ thì mình xem theo mẫu và nhu cầu nha 😄 Cho em biết ai sử dụng và thích kiểu nào, em hỗ trợ lựa chọn dễ cân nhắc ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_124",
    "name": "Có nhiều mẫu không",
    "keywords": [
      "có nhiều mẫu không",
      "nhiều lựa chọn không",
      "mẫu nào có",
      "nhiều mẫu không",
      "có bao nhiêu mẫu",
      "list mẫu",
      "catalog",
      "catalogue",
      "mẫu nào đang có",
      "full mẫu",
      "co nhieu mau khong",
      "nhieu lua chon khong",
      "mau nao co"
    ],
    "replyText": "Nhiều mẫu thì tha hồ ngắm nha 😄 Cho em nhu cầu hoặc khoảng giá, em giúp lọc nhóm mẫu phù hợp để khỏi “lạc” giữa quá nhiều lựa chọn ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_125",
    "name": "Mẫu mới",
    "keywords": [
      "mẫu mới",
      "hàng mới về",
      "sản phẩm mới",
      "new mẫu",
      "mẫu mới về",
      "new arrival",
      "new",
      "hàng mới",
      "mẫu mới nhất",
      "mới ra",
      "mau moi",
      "hang moi ve",
      "san pham moi"
    ],
    "replyText": "Mẫu mới thì mình cập nhật cho nóng hổi nha 😄 Nói nhóm sản phẩm đang quan tâm, em hỗ trợ kiểm tra các mẫu mới được giới thiệu ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_126",
    "name": "Khi nào có mẫu mới",
    "keywords": [
      "khi nào có mẫu mới",
      "bao giờ restock",
      "khi nào nhập lại",
      "new mẫu",
      "mẫu mới về",
      "new arrival",
      "new",
      "hàng mới",
      "mẫu mới nhất",
      "mới ra",
      "bao giờ có mẫu mới",
      "khi nào restock",
      "restock",
      "nhập mẫu mới",
      "mẫu mới khi nào",
      "bao giờ về",
      "khi nao co mau moi",
      "bao gio restock",
      "khi nao nhap lai"
    ],
    "replyText": "Muốn biết khi nào có mẫu mới thì mình theo dõi thông tin cập nhật nha 😄 Gửi tên/mã mẫu đang chờ, em hỗ trợ kiểm tra thông tin hiện có ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_127",
    "name": "Đặt trước",
    "keywords": [
      "đặt trước",
      "pre-order",
      "hàng đặt trước",
      "preorder",
      "đặt pre",
      "order trước",
      "hàng pre",
      "đặt trước không",
      "dat truoc",
      "hang dat truoc"
    ],
    "replyText": "Đặt trước thì phải xem sản phẩm có áp dụng hay không nha 😄 Gửi tên/mã sản phẩm, em hướng dẫn điều kiện và thông tin thời gian nếu có ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_128",
    "name": "Có sẵn tại cửa hàng không",
    "keywords": [
      "có sẵn tại cửa hàng không",
      "mua trực tiếp",
      "đến shop mua",
      "có tại shop không",
      "có ở cửa hàng không",
      "lấy tại shop",
      "pickup",
      "pick up",
      "đến shop lấy",
      "co san tai cua hang khong",
      "mua truc tiep",
      "den shop mua"
    ],
    "replyText": "Muốn mua trực tiếp thì mình kiểm tra đúng cửa hàng và tình trạng hàng nha 😄 Cho em sản phẩm + khu vực, em hỗ trợ thông tin được công bố ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_129",
    "name": "Địa chỉ shop",
    "keywords": [
      "địa chỉ shop",
      "shop ở đâu",
      "cửa hàng ở đâu",
      "địa chỉ",
      "địa chỉ shop đâu",
      "map shop",
      "đường nào",
      "chi nhánh ở đâu",
      "dia chi shop",
      "shop o dau",
      "cua hang o dau"
    ],
    "replyText": "Địa chỉ shop thì mình lấy đúng thông tin chính thức nha 😄 Cho em tên cửa hàng hoặc khu vực, em hướng dẫn cách tìm địa chỉ ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_130",
    "name": "Giờ mở cửa",
    "keywords": [
      "giờ mở cửa",
      "shop mở mấy giờ",
      "đóng cửa mấy giờ",
      "mở cửa mấy giờ",
      "shop mở đến mấy giờ",
      "giờ hoạt động",
      "open mấy giờ",
      "close mấy giờ",
      "gio mo cua",
      "shop mo may gio",
      "dong cua may gio"
    ],
    "replyText": "Giờ mở cửa thì mình kiểm tra theo đúng cửa hàng nha 😄 Cho em địa điểm cụ thể, em hỗ trợ thông tin giờ hoạt động được công bố ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_131",
    "name": "Có ship tỉnh không",
    "keywords": [
      "có ship tỉnh không",
      "giao toàn quốc",
      "ship toàn quốc",
      "ship tỉnh",
      "giao tỉnh",
      "ship liên tỉnh",
      "tỉnh có giao không",
      "co ship tinh khong",
      "giao toan quoc",
      "ship toan quoc"
    ],
    "replyText": "Ship tỉnh thì mình kiểm tra theo khu vực nha 😄 Cho em tỉnh/thành nhận hàng, em hỗ trợ thông tin phạm vi giao hàng ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_132",
    "name": "Giao ngoại thành",
    "keywords": [
      "giao ngoại thành",
      "giao vùng xa",
      "huyện xã có giao không",
      "ngoại thành",
      "vùng xa",
      "huyện có giao không",
      "xã có giao không",
      "huyện xã",
      "vùng sâu",
      "địa chỉ xa",
      "giao ngoai thanh",
      "giao vung xa",
      "huyen xa co giao khong"
    ],
    "replyText": "Vùng xa hay huyện/xã thì mình kiểm tra cụ thể mới chuẩn nha 😄 Gửi tỉnh, thành phố và khu vực nhận hàng, em hỗ trợ kiểm tra ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_133",
    "name": "Không có đơn",
    "keywords": [
      "không có đơn",
      "live không ra đơn",
      "bán không được",
      "không ra đơn",
      "no order",
      "0 đơn",
      "ế đơn",
      "đơn ít",
      "không chốt được",
      "bán không ra",
      "khong co don",
      "live khong ra don",
      "ban khong duoc"
    ],
    "replyText": "Live chưa ra đơn thì đừng vội nản nha 😄 Mình rà lại sản phẩm, cách trình bày lợi ích, giá/ưu đãi, tương tác và bước đặt hàng để tìm chỗ cần cải thiện ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_134",
    "name": "Có view nhưng không ra đơn",
    "keywords": [
      "có view nhưng không ra đơn",
      "nhiều người xem không mua",
      "view có đơn không",
      "nhiều view không đơn",
      "view cao không chốt",
      "xem nhiều không mua",
      "co view nhung khong ra don",
      "nhieu nguoi xem khong mua"
    ],
    "replyText": "Có view mà chưa có đơn thì mình soi lại “đoạn cuối” nha 😄 Giá, lợi ích, thông tin sản phẩm và bước hành động cần thật rõ để người xem biết làm gì tiếp theo ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_135",
    "name": "Khách hỏi giá rồi không mua",
    "keywords": [
      "khách hỏi giá rồi không mua",
      "hỏi xong bỏ",
      "hỏi giá rồi mất",
      "hỏi giá xong im",
      "hỏi giá không chốt",
      "xin giá rồi bỏ",
      "hỏi giá rồi out",
      "khach hoi gia roi khong mua",
      "hoi xong bo"
    ],
    "replyText": "Khách hỏi giá rồi im cũng bình thường nha 😄 Mình hỏi nhẹ còn băn khoăn gì, rồi trả lời đúng điểm đó thay vì thúc liên tục ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_136",
    "name": "Khách nói để xem thêm",
    "keywords": [
      "khách nói để xem thêm",
      "xem thêm rồi mua",
      "xem thêm đã",
      "để tham khảo",
      "tham khảo rồi mua",
      "xem rồi quyết",
      "để coi thêm",
      "xem thêm mẫu",
      "khach noi de xem them",
      "xem them roi mua"
    ],
    "replyText": "Khách nói để xem thêm thì mình cứ để khách tham khảo nha 😄 Có thể hỏi họ muốn so sánh điểm nào để cung cấp thêm thông tin, không cần tạo áp lực ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_137",
    "name": "Khách hỏi có giảm nữa không rồi im",
    "keywords": [
      "khách hỏi có giảm nữa không rồi im",
      "xin giảm rồi im",
      "hỏi giảm rồi mất",
      "xin deal rồi im",
      "hỏi giá tốt rồi im",
      "khach hoi co giam nua khong roi im"
    ],
    "replyText": "Khách hỏi giảm rồi im thì mình phản hồi rõ mức ưu đãi hiện có, sau đó hỏi nhẹ nhu cầu nha 😄 Không cần nhắn dồn, để khách có thời gian cân nhắc ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_138",
    "name": "Khách nói mắc quá rồi bỏ",
    "keywords": [
      "khách nói mắc quá rồi bỏ",
      "chê mắc rồi out",
      "nói đắt rồi đi",
      "giá cao rồi bỏ",
      "mắc quá không mua",
      "khach noi mac qua roi bo"
    ],
    "replyText": "Khách nói mắc rồi out thì mình đừng đuổi theo nha 😄 Có thể hỏi ngân sách hoặc nhu cầu để đưa thông tin phù hợp nếu có; quyết định vẫn để khách tự cân nhắc ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_139",
    "name": "Khách muốn xem thêm mẫu",
    "keywords": [
      "khách muốn xem thêm mẫu",
      "gửi thêm mẫu",
      "cho xem thêm",
      "gửi mẫu khác",
      "thêm mẫu",
      "mẫu khác đâu",
      "còn mẫu nào nữa",
      "gửi thêm hình",
      "khach muon xem them mau",
      "gui them mau"
    ],
    "replyText": "Muốn xem thêm mẫu thì cứ nói nhu cầu nha 😄 Cho em màu, kiểu, khoảng giá hoặc mục đích sử dụng, em hỗ trợ lọc nhóm mẫu phù hợp ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  },
  {
    "id": "kw_140_140",
    "name": "Khách hỏi màu nào đẹp",
    "keywords": [
      "khách hỏi màu nào đẹp",
      "chọn màu giúp",
      "màu nào đẹp",
      "màu nào xinh",
      "màu nào dễ dùng",
      "màu nào dễ bán",
      "gợi ý màu",
      "khach hoi mau nao dep",
      "chon mau giup"
    ],
    "replyText": "Màu đẹp còn tùy gu mỗi người nha 😄 Thích nổi bật, nhẹ nhàng hay dễ phối? Nói gu cho em, mình chọn cho vui ạ!",
    "enabled": true,
    "cooldownSec": 3,
    "role": "assistant"
  }
];
