/**
 * 👑 MASTER DNA 50 GIỌNG NỮ VIỆT NAM ĐỘC BẢN TOÀN DIỆN (18 - 70+ TUỔI)
 * Thiết kế chuẩn xác 5 tầng DNA âm học:
 * 1. Acoustic DNA (F0, Pitch Range, Formant, Resonance, Brightness, Warmth, Texture)
 * 2. Breath DNA (Hơi thở tự nhiên, độ sâu, vị trí lấy hơi)
 * 3. Prosody DNA (Nhịp điệu, tốc độ WPM, ngắt nghỉ, cao trào, trọng âm)
 * 4. Emotion DNA (Tươi vui, ngọt ngào, tự tin, đồng cảm, quyến rũ, sang trọng)
 * 5. Performance DNA (Cách chốt đơn, đọc số, CTA, tư vấn chuẩn mực như Hoa hậu & MC Quốc Dân)
 */

export const MASTER_DNA_FEMALE_VIETNAMESE_50_VOICES = [
  // =========================================================================
  // 🌸 NHÓM 1: 15 GIỌNG NỮ TRẺ GEN Z, HOA HẬU & NGỌT NGÀO (18 - 24 TUỔI)
  // Tông giọng: Cực kỳ ngọt ngào, tươi sáng, cuốn hút, nghe là mê đắm ngay
  // =========================================================================
  {
    id: "vn_f_dna_01_liveselling_energy",
    name: "01. Thu Ngân 👑 (Nữ 22-28t - Liveselling Năng Lượng & Bán Hàng Viral [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "young",
    ageRange: "22-28",
    styleCategory: "banhang",
    category: "Liveselling Năng Lượng • Miền Bắc",
    pitch: 1.08,
    rate: 1.08,
    recommendedFor: "both",
    desc: "Giọng nữ livestream bán hàng năng lượng đỉnh cao, bật câu dứt khoát, nụ cười rạng rỡ trong từng thớ âm thanh, chốt đơn siêu cuốn hút.",
    sampleText: "Dạ em Thu Ngân xin chào cả nhà mình nha! Hôm nay em mang đến deal độc quyền giảm kịch sàn duy nhất trong phiên live này, các bác nhanh tay bấm ngay vào giỏ hàng kẻo lỡ nha!",
    edgePitch: "+16%",
    edgeRate: "+10%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 1.8,
      detune: 180,
      rate: 1.08,
      lowGain: 0.2,
      lowFreq: 240,
      midFreq: 1350,
      midGain: 2.8,
      presenceFreq: 3900,
      presenceGain: 5.2,
      highGain: 3.8,
      highFreq: 7500,
      reverb: 0.04,
      reverbDecay: 0.25,
      compressor: { threshold: -20, ratio: 4.0, attack: 0.005, release: 0.15 }
    },
    dna: {
      persona: { age: "22-28", personality: "tươi sáng, năng động, dứt khoát, nụ cười rạng rỡ" },
      acoustic: { f0: "205-245Hz", resonance: "face-mouth", brightness: 76, warmth: 62, articulation: 94 }
    }
  },
  {
    id: "vn_f_dna_02_sweet_girl",
    name: "02. Mỹ Duyên 👑 (Nữ 18-23t - Hoa Hậu Ngọt Ngào, Beauty & Thời Trang [Sài Gòn])",
    provider: "system",
    tier: "pro",
    badge: "👑 Hoa Hậu Model VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "young",
    ageRange: "18-23",
    styleCategory: "idol_genz",
    category: "Hoa Hậu Ngọt Ngào (18-23t) • Miền Nam",
    pitch: 1.14,
    rate: 1.02,
    recommendedFor: "idol",
    desc: "Giọng nữ người mẫu hoa hậu Sài Gòn ngọt như rót mật vào tai, trong trẻo, nũng nịu duyên dáng, chuyên livestream mỹ phẩm và thời trang cao cấp.",
    sampleText: "Dạ em Mỹ Duyên xin chào cả nhà iu nha! Set đầm hoa nhí này mặc lên tôn dáng xinh xỉu luôn á, mọi người thả tim và chấm nhẹ để em thấy tương tác nè!",
    edgePitch: "+24%",
    edgeRate: "+4%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 2.5,
      detune: 250,
      rate: 1.02,
      lowGain: -0.5,
      lowFreq: 220,
      midFreq: 1450,
      midGain: 3.2,
      presenceFreq: 4400,
      presenceGain: 6.0,
      highGain: 5.0,
      highFreq: 8000,
      reverb: 0.06,
      reverbDecay: 0.35,
      compressor: { threshold: -19, ratio: 3.8, attack: 0.006, release: 0.18 }
    },
    dna: {
      persona: { age: "18-23", personality: "ngọt ngào, quyến rũ, nũng nịu, thân thiện" },
      acoustic: { f0: "215-255Hz", resonance: "face-head", brightness: 70, warmth: 82, articulation: 92 }
    }
  },
  {
    id: "vn_f_dna_03_sharp_sales",
    name: "03. Kim Oanh 👑 (Nữ 25-32t - Chốt Sale Sắc Sảo & Quyết Đoán [TP.HCM])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "middle",
    ageRange: "25-32",
    styleCategory: "banhang",
    category: "Chốt Sale Sắc Sảo (25-32t) • Miền Nam",
    pitch: 1.03,
    rate: 1.08,
    recommendedFor: "manager",
    desc: "Giọng nữ chốt sale Sài Gòn sắc sảo, thông minh, đẩy tính cấp bách mạnh mẽ, phản xạ chốt đơn chuẩn từng giây.",
    sampleText: "Kho bên em vừa báo chỉ còn đúng 5 suất ưu đãi cuối cùng cho phiên live này thôi nha, anh chị nhanh tay đặt ngay kẻo hết quà xịn ạ!",
    edgePitch: "+8%",
    edgeRate: "+10%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 0.8,
      detune: 80,
      rate: 1.08,
      lowGain: 0.6,
      lowFreq: 250,
      midFreq: 1200,
      midGain: 2.6,
      presenceFreq: 3800,
      presenceGain: 5.4,
      highGain: 3.2,
      highFreq: 7200,
      reverb: 0.03,
      reverbDecay: 0.20,
      compressor: { threshold: -22, ratio: 4.6, attack: 0.003, release: 0.12 }
    },
    dna: {
      persona: { age: "25-32", personality: "thông minh, sắc sảo, chắc câu, quyết đoán" },
      acoustic: { f0: "190-225Hz", resonance: "mouth-chest", brightness: 68, warmth: 58, articulation: 97 }
    }
  },
  {
    id: "vn_f_dna_04_luxury_glamour",
    name: "04. Khánh Linh 👑 (Nữ 28-38t - Quyến Rũ Sang Trọng, Nước Hoa & Luxury [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "💎 Luxury VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "28-38",
    styleCategory: "doanhnhan",
    category: "Luxury Sang Trọng (28-38t) • Miền Bắc",
    pitch: 0.98,
    rate: 0.95,
    recommendedFor: "idol",
    desc: "Giọng nữ quý phái sang trọng, âm vực trầm ấm mượt mà, đẳng cấp thương hiệu cao cấp, quyến rũ người nghe từng nốt thở.",
    sampleText: "Một mùi hương tinh tế không chỉ khẳng định phong cách, mà còn là bản tuyên ngôn của sự sang trọng và tự tin bất tận.",
    edgePitch: "-3%",
    edgeRate: "-6%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -0.4,
      detune: -40,
      rate: 0.95,
      lowGain: 1.6,
      lowFreq: 200,
      midFreq: 1050,
      midGain: 2.2,
      presenceFreq: 3400,
      presenceGain: 4.8,
      highGain: 4.0,
      highFreq: 7800,
      reverb: 0.08,
      reverbDecay: 0.45,
      compressor: { threshold: -18, ratio: 3.5, attack: 0.008, release: 0.25 }
    },
    dna: {
      persona: { age: "28-38", personality: "quý phái, trầm mượt, sang trọng, tinh tế" },
      acoustic: { f0: "175-215Hz", resonance: "chest-mouth", brightness: 48, warmth: 88, articulation: 91 }
    }
  },
  {
    id: "vn_f_dna_05_media_mc",
    name: "05. Mai Phương 👑 (Nữ 25-35t - MC Truyền Thông & Sự Kiện Quốc Gia [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "🎙️ BTV Đài VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "25-35",
    styleCategory: "mc_btv",
    category: "MC Truyền Thông (25-35t) • Miền Bắc",
    pitch: 1.04,
    rate: 1.02,
    recommendedFor: "both",
    desc: "Giọng nữ MC sự kiện thanh lịch, phát âm tròn vành rõ chữ chuẩn quốc gia, phong thái đĩnh đạc và lôi cuốn.",
    sampleText: "Chào mừng quý vị đại biểu và toàn thể quý vị khách quý đang có mặt tại sự kiện ra mắt công nghệ đỉnh cao ngày hôm nay!",
    edgePitch: "+8%",
    edgeRate: "+2%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 0.9,
      detune: 90,
      rate: 1.02,
      lowGain: 0.8,
      lowFreq: 230,
      midFreq: 1250,
      midGain: 2.5,
      presenceFreq: 3700,
      presenceGain: 5.6,
      highGain: 3.4,
      highFreq: 7400,
      reverb: 0.05,
      reverbDecay: 0.30,
      compressor: { threshold: -20, ratio: 4.0, attack: 0.005, release: 0.16 }
    },
    dna: {
      persona: { age: "25-35", personality: "đĩnh đạc, thanh lịch, chuẩn mực, tỏa sáng sân khấu" },
      acoustic: { f0: "185-225Hz", resonance: "mouth-face", brightness: 72, warmth: 68, articulation: 98 }
    }
  },
  {
    id: "vn_f_dna_06_cinematic_story",
    name: "06. Hạ Vy 👑 (Nữ 30-42t - Kể Chuyện Điện Ảnh, Sâu Lắng & Truyền Cảm [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "🎬 Điện Ảnh VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "30-42",
    styleCategory: "tam_su",
    category: "Kể Chuyện Điện Ảnh (30-42t) • Miền Bắc",
    pitch: 0.95,
    rate: 0.92,
    recommendedFor: "idol",
    desc: "Giọng nữ kể chuyện điện ảnh sâu lắng, giàu chất thơ và không gian, từng câu nói chạm sâu vào trái tim người nghe.",
    sampleText: "Có những ngày ta chỉ muốn ngồi lại, lắng nghe thanh âm bình yên của cuộc sống và nhớ về những kỷ niệm đã qua...",
    edgePitch: "-8%",
    edgeRate: "-10%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -0.9,
      detune: -90,
      rate: 0.92,
      lowGain: 2.0,
      lowFreq: 180,
      midFreq: 980,
      midGain: 2.0,
      presenceFreq: 3200,
      presenceGain: 4.2,
      highGain: 3.8,
      highFreq: 7600,
      reverb: 0.10,
      reverbDecay: 0.55,
      compressor: { threshold: -17, ratio: 3.2, attack: 0.010, release: 0.30 }
    },
    dna: {
      persona: { age: "30-42", personality: "sâu lắng, giàu hình ảnh, truyền cảm, điện ảnh" },
      acoustic: { f0: "165-205Hz", resonance: "chest-head", brightness: 43, warmth: 90, articulation: 90 }
    }
  },
  {
    id: "vn_f_dna_07_inspirational",
    name: "07. Tuệ Lâm 👑 (Nữ 30-45t - Truyền Cảm Hứng, Giáo Dục & Động Lực [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "🌟 Truyền Cảm Hứng VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "30-45",
    styleCategory: "chuyengia",
    category: "Truyền Cảm Hứng (30-45t) • Miền Bắc",
    pitch: 1.01,
    rate: 1.00,
    recommendedFor: "both",
    desc: "Giọng nữ truyền cảm hứng ấm áp, kiên định, nâng đỡ tinh thần và thắp sáng niềm tin cho mọi người xung quanh.",
    sampleText: "Mỗi bước đi của bạn hôm nay, dù nhỏ bé đến đâu, đều đang kiến tạo nên phiên bản tuyệt vời nhất của chính bạn ngày mai!",
    edgePitch: "+2%",
    edgeRate: "0%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 0.2,
      detune: 20,
      rate: 1.00,
      lowGain: 1.2,
      lowFreq: 210,
      midFreq: 1150,
      midGain: 2.4,
      presenceFreq: 3600,
      presenceGain: 5.0,
      highGain: 3.0,
      highFreq: 7200,
      reverb: 0.05,
      reverbDecay: 0.28,
      compressor: { threshold: -20, ratio: 3.8, attack: 0.006, release: 0.18 }
    },
    dna: {
      persona: { age: "30-45", personality: "kiên định, ấm áp, thấu cảm, tràn đầy năng lượng tích cực" },
      acoustic: { f0: "180-220Hz", resonance: "chest-face", brightness: 58, warmth: 78, articulation: 94 }
    }
  },
  {
    id: "vn_f_dna_08_calm_ceo",
    name: "08. Minh Trang 👑 (Nữ 38-52t - Nữ CEO Điềm Tĩnh, Quyền Uy & Lãnh Đạo [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "💼 Doanh Nhân VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "35-45",
    styleCategory: "doanhnhan",
    category: "Nữ CEO Điềm Tĩnh (38-52t) • Miền Bắc",
    pitch: 0.92,
    rate: 0.92,
    recommendedFor: "manager",
    desc: "Giọng nữ lãnh đạo đĩnh đạc, tông trầm quyền lực nhưng không gắt, câu ngắn chắc nịch mang tầm vóc chiến lược.",
    sampleText: "Tầm nhìn của doanh nghiệp không nằm ở quy mô tức thời, mà nằm ở giá trị bền vững mang lại cho khách hàng và xã hội.",
    edgePitch: "-12%",
    edgeRate: "-10%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -1.3,
      detune: -130,
      rate: 0.92,
      lowGain: 2.4,
      lowFreq: 170,
      midFreq: 920,
      midGain: 2.0,
      presenceFreq: 3100,
      presenceGain: 4.5,
      highGain: 2.5,
      highFreq: 7000,
      reverb: 0.04,
      reverbDecay: 0.22,
      compressor: { threshold: -22, ratio: 4.2, attack: 0.004, release: 0.15 }
    },
    dna: {
      persona: { age: "38-52", personality: "quyền uy, bình tĩnh, đĩnh đạc, chiến lược" },
      acoustic: { f0: "155-195Hz", resonance: "chest", brightness: 45, warmth: 75, articulation: 96 }
    }
  },
  {
    id: "vn_f_dna_09_trusted_expert",
    name: "09. Bác Sĩ Lan Hương 👑 (Nữ 35-50t - Chuyên Gia Y Khoa & Dinh Dưỡng [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "🔬 Chuyên Gia VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "35-45",
    styleCategory: "chuyengia",
    category: "Chuyên Gia Tin Cậy (35-50t) • Miền Bắc",
    pitch: 0.96,
    rate: 0.96,
    recommendedFor: "both",
    desc: "Giọng nữ chuyên gia y tế, khoa học và dinh dưỡng chuẩn mực, chính xác, phân tích rành mạch tạo niềm tin tuyệt đối.",
    sampleText: "Việc bổ sung đầy đủ dưỡng chất mỗi ngày là nền tảng cốt lõi giúp tăng cường hệ miễn dịch và duy trì thể trạng khỏe mạnh.",
    edgePitch: "-6%",
    edgeRate: "-5%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -0.7,
      detune: -70,
      rate: 0.96,
      lowGain: 1.5,
      lowFreq: 200,
      midFreq: 1100,
      midGain: 2.3,
      presenceFreq: 3500,
      presenceGain: 5.0,
      highGain: 3.0,
      highFreq: 7200,
      reverb: 0.03,
      reverbDecay: 0.18,
      compressor: { threshold: -20, ratio: 3.8, attack: 0.005, release: 0.15 }
    },
    dna: {
      persona: { age: "35-50", personality: "chính xác, khoa học, điềm tĩnh, đáng tin cậy" },
      acoustic: { f0: "165-205Hz", resonance: "mouth-chest", brightness: 55, warmth: 72, articulation: 97 }
    }
  },
  {
    id: "vn_f_dna_10_ugc_review",
    name: "10. Bảo Trâm 👑 (Nữ 24-32t - Reviewer Đời Thường & TikTok UGC [Sài Gòn])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "young",
    ageRange: "20-28",
    styleCategory: "idol_genz",
    category: "Review Đời Thường (24-32t) • Miền Nam",
    pitch: 1.06,
    rate: 1.06,
    recommendedFor: "both",
    desc: "Giọng nữ review đời thường gần gũi như nói chuyện với bạn thân, tự nhiên, biểu cảm chân thật và cực kỳ hút mắt xem.",
    sampleText: "Mọi người ơi, đây là món đồ chân ái nhất mà em tìm được trong tháng này luôn á, dùng thử một lần là mê chữ ê kéo dài luôn nè!",
    edgePitch: "+12%",
    edgeRate: "+8%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 1.4,
      detune: 140,
      rate: 1.06,
      lowGain: 0.0,
      lowFreq: 230,
      midFreq: 1300,
      midGain: 2.7,
      presenceFreq: 4000,
      presenceGain: 5.5,
      highGain: 4.2,
      highFreq: 7600,
      reverb: 0.04,
      reverbDecay: 0.24,
      compressor: { threshold: -20, ratio: 4.0, attack: 0.004, release: 0.14 }
    },
    dna: {
      persona: { age: "24-32", personality: "gần gũi, chân thật, bạn thân, hào hứng" },
      acoustic: { f0: "190-235Hz", resonance: "face", brightness: 74, warmth: 70, articulation: 91 }
    }
  },
  {
    id: "vn_f_dna_11_comedy_commerce",
    name: "11. Bích Tuyền 👑 (Nữ 22-30t - Hài Hước Lầy Lội & Short Video Viral [Miền Tây])",
    provider: "system",
    tier: "pro",
    badge: "😂 Comedy VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "tay",
    ageGroup: "young",
    ageRange: "20-28",
    styleCategory: "idol_genz",
    category: "Hài Hước Lầy Lội (22-30t) • Miền Tây",
    pitch: 1.10,
    rate: 1.12,
    recommendedFor: "idol",
    desc: "Giọng nữ Miền Tây duyên dáng lầy lội, phản xạ nhanh nhạy, quẩy tung livestream mang lại tiếng cười giòn giã và chốt deal không ngừng nghỉ.",
    sampleText: "Trời đất ơi coi cái giá sốc tận nóc kìa mấy bà! Hổng chốt liền tay là tiếc hùi hụi gáng chịu nha, bấm giỏ hàng liền cho em nè!",
    edgePitch: "+20%",
    edgeRate: "+16%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 2.0,
      detune: 200,
      rate: 1.12,
      lowGain: -0.8,
      lowFreq: 220,
      midFreq: 1400,
      midGain: 3.0,
      presenceFreq: 4200,
      presenceGain: 5.8,
      highGain: 4.5,
      highFreq: 7800,
      reverb: 0.05,
      reverbDecay: 0.28,
      compressor: { threshold: -22, ratio: 4.4, attack: 0.003, release: 0.12 }
    },
    dna: {
      persona: { age: "22-30", personality: "hài hước, duyên dáng, vui nhộn, tràn đầy năng lượng" },
      acoustic: { f0: "195-245Hz", resonance: "face", brightness: 82, warmth: 65, articulation: 92 }
    }
  },
  {
    id: "vn_f_dna_12_whisper_premium",
    name: "12. Thanh Hằng 👑 (Nữ 25-38t - Thì Thầm Quyến Rũ, Mỹ Phẩm & Spa [TP.HCM])",
    provider: "system",
    tier: "pro",
    badge: "✨ Premium Whisper",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "tam_su",
    category: "Thì Thầm Quyến Rũ (25-38t) • Miền Nam",
    pitch: 0.96,
    rate: 0.90,
    recommendedFor: "idol",
    desc: "Giọng nữ thì thầm mềm mại, điện ảnh, độ mịn nhung sang chảnh, tạo cảm giác thư giãn và nâng niu giác quan khách hàng.",
    sampleText: "Hãy nhắm mắt lại và cảm nhận sự dịu nhẹ của từng giọt tinh chất thẩm thấu, đưa làn da về trạng thái tươi trẻ nguyên bản...",
    edgePitch: "-6%",
    edgeRate: "-14%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -0.6,
      detune: -60,
      rate: 0.90,
      lowGain: 1.8,
      lowFreq: 190,
      midFreq: 1000,
      midGain: 2.0,
      presenceFreq: 3300,
      presenceGain: 4.4,
      highGain: 5.2,
      highFreq: 8200,
      reverb: 0.12,
      reverbDecay: 0.60,
      compressor: { threshold: -16, ratio: 3.0, attack: 0.012, release: 0.35 }
    },
    dna: {
      persona: { age: "25-38", personality: "mềm mại, thì thầm, sang trọng, thư giãn" },
      acoustic: { f0: "175-215Hz", resonance: "head-face", brightness: 54, warmth: 84, articulation: 89 }
    }
  },
  {
    id: "vn_f_dna_13_genz_trendy",
    name: "13. Yến Nhi 👑 (Nữ 18-22t - Năng Động GenZ, Bắt Trend TikTok Shorts [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "⚡ GenZ Viral",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "young",
    ageRange: "18-24",
    styleCategory: "idol_genz",
    category: "Năng Động GenZ (18-22t) • Miền Bắc",
    pitch: 1.16,
    rate: 1.12,
    recommendedFor: "idol",
    desc: "Giọng nữ trẻ Gen Z tươi sáng, ríu rít bắt trend, nhịp nói nhanh giòn giã thu hút mọi bạn trẻ trên TikTok & Reels.",
    sampleText: "Hế lô cả nhà yêu! Trend này đang hot rần rần trên mạng nè, ai chưa thử là tối cổ luôn đó nha, xem hết clip nha!",
    edgePitch: "+28%",
    edgeRate: "+18%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 2.8,
      detune: 280,
      rate: 1.12,
      lowGain: -1.2,
      lowFreq: 220,
      midFreq: 1500,
      midGain: 3.4,
      presenceFreq: 4500,
      presenceGain: 6.2,
      highGain: 5.0,
      highFreq: 8200,
      reverb: 0.04,
      reverbDecay: 0.22,
      compressor: { threshold: -21, ratio: 4.2, attack: 0.003, release: 0.12 }
    },
    dna: {
      persona: { age: "18-22", personality: "lanh lợi, tươi sáng, GenZ, nhịp điệu nhanh" },
      acoustic: { f0: "220-270Hz", resonance: "face", brightness: 86, warmth: 55, articulation: 90 }
    }
  },
  {
    id: "vn_f_dna_14_confidante",
    name: "14. Quỳnh Anh 👑 (Nữ 23-30t - Bạn Thân Tâm Sự, Chữa Lành & Lắng Nghe [Đà Nẵng])",
    provider: "system",
    tier: "pro",
    badge: "🌿 Chữa Lành VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "trung",
    ageGroup: "young",
    ageRange: "20-28",
    styleCategory: "tam_su",
    category: "Bạn Thân Tâm Sự (23-30t) • Miền Trung",
    pitch: 1.02,
    rate: 0.98,
    recommendedFor: "idol",
    desc: "Giọng nữ miền Trung ngọt lành, dịu dàng như bạn thân bên cạnh, biết lắng nghe và xoa dịu mọi muộn phiền.",
    sampleText: "Nếu hôm nay bạn cảm thấy mệt mỏi, hãy để lại bình luận để mình cùng chia sẻ và trò chuyện với nhau bạn nhé.",
    edgePitch: "+4%",
    edgeRate: "-3%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 0.4,
      detune: 40,
      rate: 0.98,
      lowGain: 1.0,
      lowFreq: 210,
      midFreq: 1180,
      midGain: 2.2,
      presenceFreq: 3500,
      presenceGain: 4.6,
      highGain: 3.2,
      highFreq: 7400,
      reverb: 0.06,
      reverbDecay: 0.35,
      compressor: { threshold: -18, ratio: 3.5, attack: 0.007, release: 0.20 }
    },
    dna: {
      persona: { age: "23-30", personality: "dịu dàng, lắng nghe, thấu cảm, chữa lành" },
      acoustic: { f0: "185-225Hz", resonance: "face-mouth", brightness: 60, warmth: 88, articulation: 91 }
    }
  },
  {
    id: "vn_f_dna_15_warm_mother",
    name: "15. Mẹ Thu Thủy 👑 (Nữ 40-55t - Mẹ Hiền Ấm Áp, Gia Đình & Ẩm Thực [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "❤️ Gia Đình VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "40-70",
    styleCategory: "tam_su",
    category: "Mẹ Hiền Ấm Áp (40-55t) • Miền Bắc",
    pitch: 0.93,
    rate: 0.92,
    recommendedFor: "both",
    desc: "Giọng nữ mẹ hiền ấm áp, chan chứa yêu thương và chăm sóc, lý tưởng cho sản phẩm gia đình, dinh dưỡng và ẩm thực sum vầy.",
    sampleText: "Bữa cơm gia đình ấm cúng luôn là nơi bình yên nhất để trở về sau những bộn bề lo toan của cuộc sống.",
    edgePitch: "-10%",
    edgeRate: "-10%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -1.1,
      detune: -110,
      rate: 0.92,
      lowGain: 2.2,
      lowFreq: 175,
      midFreq: 950,
      midGain: 2.1,
      presenceFreq: 3200,
      presenceGain: 4.5,
      highGain: 2.8,
      highFreq: 7000,
      reverb: 0.05,
      reverbDecay: 0.30,
      compressor: { threshold: -19, ratio: 3.6, attack: 0.007, release: 0.22 }
    },
    dna: {
      persona: { age: "40-55", personality: "ấm áp, yêu thương, hiền hậu, chăm sóc" },
      acoustic: { f0: "160-200Hz", resonance: "chest-mouth", brightness: 42, warmth: 94, articulation: 93 }
    }
  },

  // =========================================================================
  // 🌟 NHÓM 2: 15 GIỌNG NỮ TRƯỞNG THÀNH, VÙNG MIỀN & BÁN HÀNG PRO (25 - 40 TUỔI)
  // Tông giọng: Thanh lịch, sắc sảo, đĩnh đạc, chốt đơn đỉnh cao
  // =========================================================================
  {
    id: "vn_f_dna_16_south_charm",
    name: "16. Cẩm Tiên 👑 (Nữ 28-40t - Miền Nam Duyên Dáng, Livestream Chốt Đơn [Sài Gòn])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "middle",
    ageRange: "28-40",
    styleCategory: "banhang",
    category: "Miền Nam Duyên Dáng (28-40t) • Miền Nam",
    pitch: 1.03,
    rate: 1.02,
    recommendedFor: "both",
    desc: "Giọng nữ miền Nam duyên dáng, ngọt lành tự nhiên, dẫn dắt câu chuyện cuốn hút tạo niềm tin cho người mua sắm.",
    sampleText: "Dạ em Cẩm Tiên xin kính chào quý bà con cô bác nha! Sản phẩm này nhà em bán cam kết chuẩn chất lượng, bao đổi trả thoải mái luôn nè!",
    edgePitch: "+6%",
    edgeRate: "+4%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 0.7,
      detune: 70,
      rate: 1.02,
      lowGain: 0.8,
      lowFreq: 220,
      midFreq: 1250,
      midGain: 2.6,
      presenceFreq: 3800,
      presenceGain: 5.2,
      highGain: 4.0,
      highFreq: 7600,
      reverb: 0.05,
      reverbDecay: 0.28,
      compressor: { threshold: -20, ratio: 4.0, attack: 0.005, release: 0.16 }
    },
    dna: {
      persona: { age: "28-40", personality: "duyên dáng, ngọt lành, thân thiện, bán hàng khéo léo" },
      acoustic: { f0: "175-220Hz", resonance: "mouth-face", brightness: 66, warmth: 86, articulation: 92 }
    }
  },
  {
    id: "vn_f_dna_17_north_elegance",
    name: "17. Thu Thảo 👑 (Nữ 28-40t - Miền Bắc Thanh Lịch, Thời Trang & Mỹ Phẩm [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "👗 Thời Trang VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "28-40",
    styleCategory: "doanhnhan",
    category: "Miền Bắc Thanh Lịch (28-40t) • Miền Bắc",
    pitch: 1.04,
    rate: 1.00,
    recommendedFor: "idol",
    desc: "Giọng nữ Hà Nội thanh lịch, chuẩn mực từng âm sắc, sang trọng quý phái, nâng tầm giá trị cho mọi bộ sưu tập thời trang.",
    sampleText: "Sự tinh tế trong từng đường kim mũi chỉ chính là yếu tố làm nên vẻ đẹp thanh lịch và đẳng cấp của quý cô hiện đại.",
    edgePitch: "+8%",
    edgeRate: "0%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 0.8,
      detune: 80,
      rate: 1.00,
      lowGain: 1.0,
      lowFreq: 230,
      midFreq: 1200,
      midGain: 2.4,
      presenceFreq: 3700,
      presenceGain: 5.4,
      highGain: 3.6,
      highFreq: 7500,
      reverb: 0.05,
      reverbDecay: 0.30,
      compressor: { threshold: -19, ratio: 3.8, attack: 0.006, release: 0.18 }
    },
    dna: {
      persona: { age: "28-40", personality: "thanh lịch, chuẩn mực, quý phái, tinh tế" },
      acoustic: { f0: "180-220Hz", resonance: "face-mouth", brightness: 70, warmth: 68, articulation: 97 }
    }
  },
  {
    id: "vn_f_dna_18_central_rustic",
    name: "18. Hoài Thương 👑 (Nữ 30-45t - Miền Trung Mộc Mạc, Ẩm Thực & Quê Hương [Huế])",
    provider: "system",
    tier: "pro",
    badge: "🌿 Mộc Mạc VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "trung",
    ageGroup: "middle",
    ageRange: "28-40",
    styleCategory: "tam_su",
    category: "Miền Trung Mộc Mạc (30-45t) • Miền Trung",
    pitch: 0.96,
    rate: 0.94,
    recommendedFor: "both",
    desc: "Giọng nữ Huế mộc mạc đậm tình xứ Trung, êm dịu sâu lắng, đưa người nghe trở về với hương vị quê nhà mộc mạc.",
    sampleText: "Mời bà con cùng thưởng thức món đặc sản đậm đà hương vị miền Trung, ăn một lần là vương vấn mãi không quên.",
    edgePitch: "-6%",
    edgeRate: "-8%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -0.7,
      detune: -70,
      rate: 0.94,
      lowGain: 1.8,
      lowFreq: 195,
      midFreq: 1020,
      midGain: 2.2,
      presenceFreq: 3300,
      presenceGain: 4.6,
      highGain: 3.0,
      highFreq: 7200,
      reverb: 0.07,
      reverbDecay: 0.40,
      compressor: { threshold: -18, ratio: 3.5, attack: 0.008, release: 0.24 }
    },
    dna: {
      persona: { age: "30-45", personality: "mộc mạc, đậm tình, chân thành, sâu lắng" },
      acoustic: { f0: "165-205Hz", resonance: "mouth-chest", brightness: 48, warmth: 91, articulation: 89 }
    }
  },
  {
    id: "vn_f_dna_19_gentle_consulting",
    name: "19. Ngọc Lan 👑 (Nữ 27-38t - Tư Vấn Nhẹ Nhàng, Spa & Chăm Sóc Sức Khỏe [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "🌸 Spa & Sức Khỏe",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "chuyengia",
    category: "Tư Vấn Nhẹ Nhàng (27-38t) • Miền Bắc",
    pitch: 1.02,
    rate: 0.98,
    recommendedFor: "idol",
    desc: "Giọng nữ tư vấn dịu dàng, khéo léo, không hề ép mua mà dẫn dắt khách hàng khám phá giải pháp chăm sóc bản thân tốt nhất.",
    sampleText: "Dạ chị yêu ơi, làn da của mình vào mùa này rất cần được cấp ẩm sâu, em xin chia sẻ bí quyết giữ ẩm hiệu quả nhất cho chị nhé.",
    edgePitch: "+4%",
    edgeRate: "-3%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 0.4,
      detune: 40,
      rate: 0.98,
      lowGain: 1.1,
      lowFreq: 215,
      midFreq: 1150,
      midGain: 2.3,
      presenceFreq: 3600,
      presenceGain: 5.0,
      highGain: 3.5,
      highFreq: 7400,
      reverb: 0.06,
      reverbDecay: 0.32,
      compressor: { threshold: -19, ratio: 3.6, attack: 0.006, release: 0.20 }
    },
    dna: {
      persona: { age: "27-38", personality: "dịu dàng, khéo léo, thấu hiểu, ân cần" },
      acoustic: { f0: "175-215Hz", resonance: "face-mouth", brightness: 62, warmth: 83, articulation: 95 }
    }
  },
  {
    id: "vn_f_dna_20_flash_sale_pro",
    name: "20. Diễm My 👑 (Nữ 25-34t - Đóng Đơn Siêu Tốc & Giục Mua Flash Sale [TP.HCM])",
    provider: "system",
    tier: "pro",
    badge: "⚡ Flash Sale VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "banhang",
    category: "Đóng Đơn Flash Sale (25-34t) • Miền Nam",
    pitch: 1.07,
    rate: 1.12,
    recommendedFor: "manager",
    desc: "Giọng nữ giục đơn tốc độ cao, đanh gọn dứt khoát, CTA cực kỳ rõ ràng, đẩy doanh số livestream chạm đỉnh.",
    sampleText: "Còn đúng 30 giây cuối cùng để chốt deal này! Ai chưa hoàn tất đơn hàng bấm ngay nút Mua Kẻo Hết Mã Giảm Giá nha cả nhà!",
    edgePitch: "+14%",
    edgeRate: "+16%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 1.5,
      detune: 150,
      rate: 1.12,
      lowGain: 0.4,
      lowFreq: 240,
      midFreq: 1320,
      midGain: 2.8,
      presenceFreq: 3900,
      presenceGain: 5.8,
      highGain: 3.4,
      highFreq: 7300,
      reverb: 0.03,
      reverbDecay: 0.18,
      compressor: { threshold: -23, ratio: 4.8, attack: 0.003, release: 0.10 }
    },
    dna: {
      persona: { age: "25-34", personality: "quyết liệt, đanh gọn, dứt khoát, đẩy tính cấp bách" },
      acoustic: { f0: "190-235Hz", resonance: "mouth-chest", brightness: 72, warmth: 60, articulation: 98 }
    }
  },
  {
    id: "vn_f_dna_21_luxury_director",
    name: "21. Trâm Anh 👑 (Nữ 35-48t - Giám Đốc Thương Hiệu Cao Cấp & Resort [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "💎 Brand Director",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "35-45",
    styleCategory: "doanhnhan",
    category: "Brand Director Luxury (35-48t) • Miền Bắc",
    pitch: 0.92,
    rate: 0.90,
    recommendedFor: "both",
    desc: "Giọng nữ tối giản, đắt giá, trầm sang chuẩn mực của giám đốc thương hiệu xa xỉ và nghỉ dưỡng đẳng cấp quốc tế.",
    sampleText: "Mỗi không gian được kiến tạo là một kiệt tác của nghệ thuật sống, nơi đẳng cấp và sự thư thái hòa quyện hoàn hảo.",
    edgePitch: "-12%",
    edgeRate: "-14%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -1.3,
      detune: -130,
      rate: 0.90,
      lowGain: 2.3,
      lowFreq: 175,
      midFreq: 940,
      midGain: 2.1,
      presenceFreq: 3200,
      presenceGain: 4.6,
      highGain: 3.8,
      highFreq: 7800,
      reverb: 0.08,
      reverbDecay: 0.48,
      compressor: { threshold: -19, ratio: 3.5, attack: 0.008, release: 0.26 }
    },
    dna: {
      persona: { age: "35-48", personality: "đắt giá, tối giản, sang trọng, đẳng cấp" },
      acoustic: { f0: "160-200Hz", resonance: "chest-head", brightness: 45, warmth: 82, articulation: 94 }
    }
  },
  {
    id: "vn_f_dna_22_night_podcast",
    name: "22. Hoàng Yến 👑 (Nữ 30-45t - Podcast Đêm Muộn, Ru Ngủ & Chữa Lành [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "🌙 Podcast Đêm VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "28-40",
    styleCategory: "tam_su",
    category: "Podcast Đêm Muộn (30-45t) • Miền Bắc",
    pitch: 0.88,
    rate: 0.88,
    recommendedFor: "idol",
    desc: "Giọng nữ podcast đêm sâu lắng, êm đềm như nhung, vỗ về tâm hồn và đưa người nghe vào giấc ngủ bình yên.",
    sampleText: "Đêm đã về khuya rồi, hãy thả lỏng cơ thể, gác lại mọi âu lo và chìm vào giấc ngủ thật êm đềm bạn nhé...",
    edgePitch: "-18%",
    edgeRate: "-16%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -1.8,
      detune: -180,
      rate: 0.88,
      lowGain: 2.8,
      lowFreq: 160,
      midFreq: 880,
      midGain: 1.9,
      presenceFreq: 3000,
      presenceGain: 4.0,
      highGain: 3.5,
      highFreq: 7500,
      reverb: 0.12,
      reverbDecay: 0.65,
      compressor: { threshold: -16, ratio: 3.0, attack: 0.012, release: 0.35 }
    },
    dna: {
      persona: { age: "30-45", personality: "êm đềm, sâu lắng, vỗ về, chữa lành" },
      acoustic: { f0: "150-190Hz", resonance: "chest", brightness: 38, warmth: 93, articulation: 88 }
    }
  },
  {
    id: "vn_f_dna_23_sharp_journalist",
    name: "23. Hải Yến 👑 (Nữ 27-40t - Phóng Viên Sắc Nét, Bản Tin Thời Sự & Explainer [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "📰 BTV Thời Sự",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "mc_btv",
    category: "Phóng Viên Sắc Nét (27-40t) • Miền Bắc",
    pitch: 1.02,
    rate: 1.04,
    recommendedFor: "both",
    desc: "Giọng nữ phóng viên sắc bén, nhịp điệu logic chuẩn xác, thông tin rõ ràng và mạch lạc trong từng câu chữ.",
    sampleText: "Theo ghi nhận mới nhất từ thị trường, xu hướng chuyển đổi số đang diễn ra mạnh mẽ trên khắp các lĩnh vực kinh tế.",
    edgePitch: "+4%",
    edgeRate: "+6%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 0.5,
      detune: 50,
      rate: 1.04,
      lowGain: 0.6,
      lowFreq: 240,
      midFreq: 1250,
      midGain: 2.5,
      presenceFreq: 3800,
      presenceGain: 5.6,
      highGain: 3.2,
      highFreq: 7300,
      reverb: 0.03,
      reverbDecay: 0.18,
      compressor: { threshold: -21, ratio: 4.2, attack: 0.004, release: 0.14 }
    },
    dna: {
      persona: { age: "27-40", personality: "sắc bén, logic, chính xác, đĩnh đạc" },
      acoustic: { f0: "175-215Hz", resonance: "mouth", brightness: 75, warmth: 55, articulation: 99 }
    }
  },
  {
    id: "vn_f_dna_24_clear_lecturer",
    name: "24. Cô Giáo Minh Anh 👑 (Nữ 32-48t - Giảng Viên Sư Phạm Dễ Hiểu [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "📚 Sư Phạm VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "28-40",
    styleCategory: "chuyengia",
    category: "Giảng Viên Dễ Hiểu (32-48t) • Miền Bắc",
    pitch: 0.96,
    rate: 0.95,
    recommendedFor: "both",
    desc: "Giọng nữ giảng viên sư phạm mẫu mực, phát âm rõ ràng, nhả chữ khoa học giúp người nghe tiếp thu kiến thức tức thì.",
    sampleText: "Bây giờ chúng ta sẽ cùng phân tích từng bước cụ thể để áp dụng phương pháp này một cách hiệu quả nhất nhé.",
    edgePitch: "-6%",
    edgeRate: "-6%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -0.6,
      detune: -60,
      rate: 0.95,
      lowGain: 1.4,
      lowFreq: 210,
      midFreq: 1100,
      midGain: 2.4,
      presenceFreq: 3500,
      presenceGain: 5.2,
      highGain: 3.0,
      highFreq: 7200,
      reverb: 0.04,
      reverbDecay: 0.22,
      compressor: { threshold: -19, ratio: 3.8, attack: 0.006, release: 0.18 }
    },
    dna: {
      persona: { age: "32-48", personality: "mẫu mực, dễ hiểu, tận tâm, khoa học" },
      acoustic: { f0: "165-205Hz", resonance: "mouth-face", brightness: 58, warmth: 75, articulation: 98 }
    }
  },
  {
    id: "vn_f_dna_25_fitness_coach",
    name: "25. Coach Thùy Dung 👑 (Nữ 25-38t - HLV Thể Thao, Gym & Năng Lượng Khỏe Khoắn [TP.HCM])",
    provider: "system",
    tier: "pro",
    badge: "💪 Fitness Coach",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "idol_genz",
    category: "HLV Thể Thao Khỏe Khoắn (25-38t) • Miền Nam",
    pitch: 1.05,
    rate: 1.06,
    recommendedFor: "both",
    desc: "Giọng nữ HLV thể hình khỏe khoắn, dứt khoát, truyền nhiệt huyết bùng nổ, thúc đẩy người tập vượt qua giới hạn bản thân.",
    sampleText: "Cố lên cả nhà ơi, chỉ còn 3 hiệp cuối cùng nữa thôi! Hít sâu, thở đều và cùng Dung đốt cháy mỡ thừa nào!",
    edgePitch: "+10%",
    edgeRate: "+8%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 1.2,
      detune: 120,
      rate: 1.06,
      lowGain: 1.0,
      lowFreq: 230,
      midFreq: 1280,
      midGain: 2.7,
      presenceFreq: 3800,
      presenceGain: 5.6,
      highGain: 3.4,
      highFreq: 7400,
      reverb: 0.04,
      reverbDecay: 0.20,
      compressor: { threshold: -22, ratio: 4.4, attack: 0.004, release: 0.12 }
    },
    dna: {
      persona: { age: "25-38", personality: "khỏe khoắn, tích cực, truyền lửa, dứt khoát" },
      acoustic: { f0: "180-225Hz", resonance: "chest-mouth", brightness: 65, warmth: 68, articulation: 95 }
    }
  },
  {
    id: "vn_f_dna_26_finance_expert",
    name: "26. Phương Thảo 👑 (Nữ 32-50t - Chuyên Gia Tài Chính, Đầu Tư & Bất Động Sản [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "📊 Tài Chính VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "35-45",
    styleCategory: "chuyengia",
    category: "Chuyên Gia Tài Chính (32-50t) • Miền Bắc",
    pitch: 0.93,
    rate: 0.94,
    recommendedFor: "manager",
    desc: "Giọng nữ chuyên gia tài chính điềm tĩnh, đọc số liệu sắc sảo, logic rõ ràng, tạo niềm tin cho nhà đầu tư chuyên nghiệp.",
    sampleText: "Việc đa dạng hóa danh mục đầu tư và kiểm soát rủi ro chính là chìa khóa then chốt để đạt lợi nhuận kỳ vọng bền vững.",
    edgePitch: "-10%",
    edgeRate: "-8%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -1.1,
      detune: -110,
      rate: 0.94,
      lowGain: 1.8,
      lowFreq: 185,
      midFreq: 1000,
      midGain: 2.2,
      presenceFreq: 3300,
      presenceGain: 4.8,
      highGain: 2.8,
      highFreq: 7100,
      reverb: 0.03,
      reverbDecay: 0.18,
      compressor: { threshold: -21, ratio: 4.0, attack: 0.005, release: 0.15 }
    },
    dna: {
      persona: { age: "32-50", personality: "thận trọng, chính xác, logic, phân tích sâu" },
      acoustic: { f0: "155-195Hz", resonance: "chest-mouth", brightness: 50, warmth: 67, articulation: 99 }
    }
  },
  {
    id: "vn_f_dna_27_leadership_mentor",
    name: "27. Diệu Hương 👑 (Nữ 38-55t - Doanh Nhân Truyền Cảm Hứng & Keynote Speaker [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "🌟 Keynote VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "35-45",
    styleCategory: "doanhnhan",
    category: "Doanh Nhân Truyền Cảm Hứng (38-55t) • Miền Bắc",
    pitch: 0.91,
    rate: 0.92,
    recommendedFor: "both",
    desc: "Giọng nữ diễn giả trưởng thành, nội lực mạnh mẽ, phong thái lãnh đạo truyền cảm hứng lan tỏa đến hàng ngàn khán giả.",
    sampleText: "Thành công thực sự không được đo bằng những gì bạn có, mà bằng những giá trị tốt đẹp bạn tạo ra cho cộng đồng.",
    edgePitch: "-14%",
    edgeRate: "-10%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -1.4,
      detune: -140,
      rate: 0.92,
      lowGain: 2.5,
      lowFreq: 170,
      midFreq: 920,
      midGain: 2.3,
      presenceFreq: 3200,
      presenceGain: 5.0,
      highGain: 3.0,
      highFreq: 7200,
      reverb: 0.05,
      reverbDecay: 0.28,
      compressor: { threshold: -22, ratio: 4.2, attack: 0.004, release: 0.16 }
    },
    dna: {
      persona: { age: "38-55", personality: "trưởng thành, nội lực, truyền cảm hứng, đĩnh đạc" },
      acoustic: { f0: "150-195Hz", resonance: "chest", brightness: 47, warmth: 78, articulation: 96 }
    }
  },
  {
    id: "vn_f_dna_28_life_mentor",
    name: "28. Bác Diệu Hiền 👑 (Nữ 45-60t - Mentor Đời Sống, Sâu Sắc & Từng Trải [Huế])",
    provider: "system",
    tier: "pro",
    badge: "📜 Mentor VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "trung",
    ageGroup: "senior",
    ageRange: "40-70",
    styleCategory: "tam_su",
    category: "Mentor Đời Sống (45-60t) • Miền Trung",
    pitch: 0.89,
    rate: 0.90,
    recommendedFor: "both",
    desc: "Giọng nữ từng trải, trầm ấm thấu hiểu, mang đậm triết lý sống và sự bình an cho bất cứ ai lắng nghe.",
    sampleText: "Học cách buông bỏ những điều không thuộc về mình chính là cách nhanh nhất để tìm lại sự an yên trong tâm hồn.",
    edgePitch: "-16%",
    edgeRate: "-14%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -1.6,
      detune: -160,
      rate: 0.90,
      lowGain: 2.6,
      lowFreq: 165,
      midFreq: 900,
      midGain: 2.0,
      presenceFreq: 3100,
      presenceGain: 4.2,
      highGain: 2.6,
      highFreq: 7000,
      reverb: 0.06,
      reverbDecay: 0.35,
      compressor: { threshold: -18, ratio: 3.5, attack: 0.008, release: 0.22 }
    },
    dna: {
      persona: { age: "45-60", personality: "từng trải, sâu sắc, dịu dàng, an yên" },
      acoustic: { f0: "145-185Hz", resonance: "chest", brightness: 40, warmth: 92, articulation: 94 }
    }
  },
  {
    id: "vn_f_dna_29_corporate_friendly",
    name: "29. Thùy Chi 👑 (Nữ 25-35t - Nữ Công Sở Thân Thiện & Đào Tạo Nhân Sự [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "🏢 Onboarding HR",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "mc_btv",
    category: "Công Sở Thân Thiện (25-35t) • Miền Bắc",
    pitch: 1.02,
    rate: 1.00,
    recommendedFor: "both",
    desc: "Giọng nữ công sở chuẩn mực, ấm áp thân thiện, lý tưởng cho video đào tạo nội bộ, onboarding và giới thiệu công ty.",
    sampleText: "Chào mừng bạn đã chính thức gia nhập đại gia đình chúng tôi! Cùng nhau kiến tạo những thành công mới nhé!",
    edgePitch: "+4%",
    edgeRate: "0%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 0.4,
      detune: 40,
      rate: 1.00,
      lowGain: 1.0,
      lowFreq: 220,
      midFreq: 1200,
      midGain: 2.3,
      presenceFreq: 3600,
      presenceGain: 5.2,
      highGain: 3.2,
      highFreq: 7300,
      reverb: 0.04,
      reverbDecay: 0.22,
      compressor: { threshold: -20, ratio: 3.8, attack: 0.005, release: 0.16 }
    },
    dna: {
      persona: { age: "25-35", personality: "chuyên nghiệp, ấm áp, thân thiện, đồng nghiệp" },
      acoustic: { f0: "180-220Hz", resonance: "mouth-face", brightness: 63, warmth: 73, articulation: 96 }
    }
  },
  {
    id: "vn_f_dna_30_customer_care",
    name: "30. Thảo Nhi 👑 (Nữ 23-32t - CSKH & Tư Vấn Khách Hàng Siêu Mềm Mại [Sài Gòn])",
    provider: "system",
    tier: "pro",
    badge: "🎧 CSKH VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "young",
    ageRange: "20-28",
    styleCategory: "chuyengia",
    category: "CSKH Siêu Mềm Mại (23-32t) • Miền Nam",
    pitch: 1.08,
    rate: 0.98,
    recommendedFor: "manager",
    desc: "Giọng nữ chăm sóc khách hàng siêu ngọt ngào, kiên nhẫn, luôn mang lại cảm giác được trân trọng và tận tâm phục vụ.",
    sampleText: "Dạ em Thảo Nhi xin chào quý khách ạ! Em luôn sẵn sàng hỗ trợ và giải đáp mọi thắc mắc của quý khách ngay lúc này ạ.",
    edgePitch: "+16%",
    edgeRate: "-3%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 1.6,
      detune: 160,
      rate: 0.98,
      lowGain: 0.5,
      lowFreq: 230,
      midFreq: 1350,
      midGain: 2.8,
      presenceFreq: 4000,
      presenceGain: 5.5,
      highGain: 4.2,
      highFreq: 7800,
      reverb: 0.05,
      reverbDecay: 0.28,
      compressor: { threshold: -18, ratio: 3.5, attack: 0.006, release: 0.18 }
    },
    dna: {
      persona: { age: "23-32", personality: "kiên nhẫn, siêu mềm mại, tận tâm, ngọt ngào" },
      acoustic: { f0: "195-235Hz", resonance: "face", brightness: 68, warmth: 88, articulation: 97 }
    }
  },

  // =========================================================================
  // 🌟 NHÓM 3: 20 GIỌNG NỮ ĐA LĨNH VỰC, TRUNG NIÊN & CAO NIÊN (30 - 75+ TUỔI)
  // Tông giọng: Công nghệ, Luxury, Ẩm thực, Trung niên, Lão niên 60-70+t
  // =========================================================================
  {
    id: "vn_f_dna_31_game_tech_host",
    name: "31. Bảo Vy 👑 (Nữ 20-28t - Host Game & Công Nghệ AI Năng Động [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "🎮 Game & Tech",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "young",
    ageRange: "20-28",
    styleCategory: "blv_game",
    category: "Host Game & Công Nghệ (20-28t) • Miền Bắc",
    pitch: 1.10,
    rate: 1.08,
    recommendedFor: "both",
    desc: "Giọng nữ host game và công nghệ sáng rõ, thông minh, hoạt ngôn bắt kịp nhịp đấu căng thẳng của esports và AI show.",
    sampleText: "Pha xử lý mãn nhãn đến từ vị trí tuyển thủ! Trận đấu đang nóng lên từng giây, anh em đừng rời mắt khỏi màn hình nha!",
    edgePitch: "+18%",
    edgeRate: "+10%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 1.9,
      detune: 190,
      rate: 1.08,
      lowGain: -0.5,
      lowFreq: 230,
      midFreq: 1400,
      midGain: 3.0,
      presenceFreq: 4200,
      presenceGain: 6.0,
      highGain: 4.4,
      highFreq: 7800,
      reverb: 0.04,
      reverbDecay: 0.22,
      compressor: { threshold: -22, ratio: 4.5, attack: 0.003, release: 0.12 }
    },
    dna: {
      persona: { age: "20-28", personality: "sáng, nhanh, hiện đại, thể thao điện tử" },
      acoustic: { f0: "200-250Hz", resonance: "face", brightness: 82, warmth: 58, articulation: 94 }
    }
  },
  {
    id: "vn_f_dna_32_ai_futuristic",
    name: "32. Ava Assistant 👑 (Nữ 24-32t - Trợ Lý Ảo Tương Lai, Công Nghệ AI [Toàn Quốc])",
    provider: "system",
    tier: "pro",
    badge: "🤖 AI Futuristic",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "young",
    ageRange: "20-28",
    styleCategory: "mc_btv",
    category: "AI Futuristic (24-32t) • Toàn Quốc",
    pitch: 1.04,
    rate: 1.02,
    recommendedFor: "manager",
    desc: "Giọng nữ trợ lý AI tương lai trong trẻo, sạch sẽ, chuẩn xác tuyệt đối từng mili-giây, biểu tượng công nghệ thông minh.",
    sampleText: "Hệ thống trí tuệ nhân tạo AVA LIVE đã sẵn sàng. Chúc bạn có một phiên livestream bùng nổ doanh số!",
    edgePitch: "+8%",
    edgeRate: "+4%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 0.8,
      detune: 80,
      rate: 1.02,
      lowGain: 0.2,
      lowFreq: 240,
      midFreq: 1300,
      midGain: 2.6,
      presenceFreq: 3900,
      presenceGain: 5.6,
      highGain: 4.2,
      highFreq: 7600,
      reverb: 0.03,
      reverbDecay: 0.18,
      compressor: { threshold: -20, ratio: 4.0, attack: 0.004, release: 0.14 }
    },
    dna: {
      persona: { age: "24-32", personality: "sạch sẽ, chính xác, tương lai, thông minh" },
      acoustic: { f0: "185-225Hz", resonance: "head-face", brightness: 70, warmth: 50, articulation: 98 }
    }
  },
  {
    id: "vn_f_dna_33_fashion_editorial",
    name: "33. Tú Hảo 👑 (Nữ 25-35t - Thời Trang Editorial & Tạp Chí Quốc Tế [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "👠 Editorial VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "doanhnhan",
    category: "Thời Trang Editorial (25-35t) • Miền Bắc",
    pitch: 0.97,
    rate: 0.92,
    recommendedFor: "idol",
    desc: "Giọng nữ thời trang editorial lạnh lùng tinh tế, câu ngắn sắc nét, chuẩn phong cách sàn diễn thời trang quốc tế.",
    sampleText: "Đường cắt tối giản kết hợp cùng chất liệu thượng hạng, tôn vinh khí chất độc bản của người mặc.",
    edgePitch: "-4%",
    edgeRate: "-10%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -0.5,
      detune: -50,
      rate: 0.92,
      lowGain: 1.4,
      lowFreq: 200,
      midFreq: 1050,
      midGain: 2.1,
      presenceFreq: 3400,
      presenceGain: 4.8,
      highGain: 3.8,
      highFreq: 7800,
      reverb: 0.07,
      reverbDecay: 0.40,
      compressor: { threshold: -19, ratio: 3.6, attack: 0.007, release: 0.22 }
    },
    dna: {
      persona: { age: "25-35", personality: "tinh tế, kiêu kỳ nhẹ, thời trang, sang trọng" },
      acoustic: { f0: "170-210Hz", resonance: "face-head", brightness: 58, warmth: 64, articulation: 93 }
    }
  },
  {
    id: "vn_f_dna_34_beauty_charm",
    name: "34. Thảo Tâm 👑 (Nữ 22-30t - Beauty Review Mê Hoặc, Skincare & Mỹ Phẩm [Sài Gòn])",
    provider: "system",
    tier: "pro",
    badge: "💄 Beauty Mê Hoặc",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "young",
    ageRange: "20-28",
    styleCategory: "idol_genz",
    category: "Beauty Review Mê Hoặc (22-30t) • Miền Nam",
    pitch: 1.08,
    rate: 1.02,
    recommendedFor: "idol",
    desc: "Giọng nữ beauty review mê hoặc, mỉm cười trong từng câu nói, truyền cảm hứng dưỡng da căng mọng và tự tin toả sáng.",
    sampleText: "Chỉ cần vài giọt serum mỗi sáng là da căng bóng mịn màng như sương mai luôn nè các nàng ơi, bấm săn ngay nha!",
    edgePitch: "+16%",
    edgeRate: "+4%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 1.6,
      detune: 160,
      rate: 1.02,
      lowGain: 0.2,
      lowFreq: 230,
      midFreq: 1380,
      midGain: 2.8,
      presenceFreq: 4100,
      presenceGain: 5.6,
      highGain: 4.5,
      highFreq: 7800,
      reverb: 0.06,
      reverbDecay: 0.32,
      compressor: { threshold: -19, ratio: 3.8, attack: 0.005, release: 0.16 }
    },
    dna: {
      persona: { age: "22-30", personality: "mềm mại, mê hoặc, mỉm cười, skincare" },
      acoustic: { f0: "195-240Hz", resonance: "face", brightness: 72, warmth: 78, articulation: 94 }
    }
  },
  {
    id: "vn_f_dna_35_culinary_food",
    name: "35. Út Lan 👑 (Nữ 30-45t - Ẩm Thực Miền Quê & Nấu Ăn Chân Thật [Miền Tây])",
    provider: "system",
    tier: "pro",
    badge: "🍲 Ẩm Thực VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "tay",
    ageGroup: "middle",
    ageRange: "28-40",
    styleCategory: "tam_su",
    category: "Ẩm Thực Miền Tây (30-45t) • Miền Tây",
    pitch: 0.98,
    rate: 1.00,
    recommendedFor: "both",
    desc: "Giọng nữ miền Tây hào sảng, chân chất, review đồ ăn nghe là thấy thèm, đậm đà phong vị đồng quê sông nước.",
    sampleText: "Cá lóc nướng trui cuốn bánh tráng rau sống, chấm mắm me cay cay chua chua là ngon nhức nách luôn bà con ơi!",
    edgePitch: "-3%",
    edgeRate: "0%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -0.3,
      detune: -30,
      rate: 1.00,
      lowGain: 1.6,
      lowFreq: 210,
      midFreq: 1100,
      midGain: 2.4,
      presenceFreq: 3500,
      presenceGain: 5.0,
      highGain: 3.5,
      highFreq: 7400,
      reverb: 0.05,
      reverbDecay: 0.28,
      compressor: { threshold: -20, ratio: 4.0, attack: 0.005, release: 0.18 }
    },
    dna: {
      persona: { age: "30-45", personality: "chân chất, ngon miệng, hào sảng, đậm đà" },
      acoustic: { f0: "165-210Hz", resonance: "mouth-chest", brightness: 58, warmth: 90, articulation: 93 }
    }
  },
  {
    id: "vn_f_dna_36_mom_life",
    name: "36. Mẹ Sóc 👑 (Nữ 30-40t - Mẹ Bỉm Trẻ Trung, Chăm Sóc Bé & Gia Đình [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "👶 Mẹ Bỉm VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "28-40",
    styleCategory: "banhang",
    category: "Mẹ Bỉm Trẻ Trung (30-40t) • Miền Bắc",
    pitch: 1.01,
    rate: 1.00,
    recommendedFor: "both",
    desc: "Giọng nữ mẹ bỉm sữa vui tươi, thực tế và chân thành, chia sẻ kinh nghiệm nuôi dạy con và đồ dùng mẹ bé chất lượng cao.",
    sampleText: "Từ ngày đổi qua dùng bình sữa này là bé nhà mình chịu ti liền, các mom nào đang đau đầu chuyện chọn bình thì thử ngay nha!",
    edgePitch: "+2%",
    edgeRate: "0%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 0.2,
      detune: 20,
      rate: 1.00,
      lowGain: 1.2,
      lowFreq: 220,
      midFreq: 1180,
      midGain: 2.4,
      presenceFreq: 3600,
      presenceGain: 5.2,
      highGain: 3.4,
      highFreq: 7300,
      reverb: 0.04,
      reverbDecay: 0.24,
      compressor: { threshold: -19, ratio: 3.8, attack: 0.006, release: 0.18 }
    },
    dna: {
      persona: { age: "30-40", personality: "thực tế, vui tươi, ấm áp, kinh nghiệm" },
      acoustic: { f0: "175-215Hz", resonance: "mouth-chest", brightness: 55, warmth: 92, articulation: 94 }
    }
  },
  {
    id: "vn_f_dna_37_mature_glamour",
    name: "37. Bích Hạnh 👑 (Nữ 40-52t - Trưởng Thành Quyến Rũ, Trang Sức & Kim Cương [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "💍 Trang Sức VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "35-45",
    styleCategory: "doanhnhan",
    category: "Trưởng Thành Quyến Rũ (40-52t) • Miền Bắc",
    pitch: 0.90,
    rate: 0.92,
    recommendedFor: "idol",
    desc: "Giọng nữ trung niên sang trọng quyến rũ, chất giọng trầm ấm viên mãn, đại diện cho những trang sức kim hoàn thượng hạng.",
    sampleText: "Ánh kim cương lấp lánh như lưu giữ trọn vẹn những khoảnh khắc huy hoàng và viên mãn nhất của cuộc đời người phụ nữ.",
    edgePitch: "-15%",
    edgeRate: "-10%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -1.5,
      detune: -150,
      rate: 0.92,
      lowGain: 2.6,
      lowFreq: 170,
      midFreq: 920,
      midGain: 2.2,
      presenceFreq: 3200,
      presenceGain: 4.8,
      highGain: 3.5,
      highFreq: 7600,
      reverb: 0.08,
      reverbDecay: 0.45,
      compressor: { threshold: -19, ratio: 3.6, attack: 0.007, release: 0.24 }
    },
    dna: {
      persona: { age: "40-52", personality: "viên mãn, quyến rũ trưởng thành, sâu sắc, quý phái" },
      acoustic: { f0: "150-190Hz", resonance: "chest-head", brightness: 43, warmth: 90, articulation: 92 }
    }
  },
  {
    id: "vn_f_dna_38_authoritative_50",
    name: "38. Cô Ánh Tuyết 👑 (Nữ 50-60t - Uy Tín & Dày Dặn Kinh Nghiệm Sống [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "👵 Uy Tín 50+ VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "46-65+",
    styleCategory: "tam_su",
    category: "Uy Tín & Trải Nghiệm (50-60t) • Miền Bắc",
    pitch: 0.86,
    rate: 0.88,
    recommendedFor: "both",
    desc: "Giọng nữ 50+ đôn hậu vững vàng, giàu uy tín và trải nghiệm thực tế, chuyên tư vấn thảo dược, sức khỏe dưỡng sinh cao niên.",
    sampleText: "Ở tuổi này rồi, giữ được sức khỏe dẻo dai và tinh thần thảnh thơi chính là món quà quý giá nhất gửi tặng con cháu.",
    edgePitch: "-20%",
    edgeRate: "-16%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -2.0,
      detune: -200,
      rate: 0.88,
      lowGain: 3.0,
      lowFreq: 155,
      midFreq: 860,
      midGain: 2.0,
      presenceFreq: 3000,
      presenceGain: 4.2,
      highGain: 2.5,
      highFreq: 6800,
      reverb: 0.05,
      reverbDecay: 0.30,
      compressor: { threshold: -18, ratio: 3.5, attack: 0.008, release: 0.22 }
    },
    dna: {
      persona: { age: "50-60", personality: "đôn hậu, uy tín, từng trải, an dưỡng" },
      acoustic: { f0: "140-180Hz", resonance: "chest", brightness: 38, warmth: 95, articulation: 93 }
    }
  },
  {
    id: "vn_f_dna_39_wise_elder_60",
    name: "39. Bà Giáo Diệu Liên 👑 (Nữ 60-70t - Trí Tuệ & Triết Lý Sống Di Sản [Huế])",
    provider: "system",
    tier: "pro",
    badge: "📜 Trí Tuệ 60+ VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "trung",
    ageGroup: "senior",
    ageRange: "46-65+",
    styleCategory: "tam_su",
    category: "Trí Tuệ & Di Sản (60-70t) • Miền Trung",
    pitch: 0.83,
    rate: 0.85,
    recommendedFor: "both",
    desc: "Giọng nữ 60+ thông tuệ, trầm ấm sâu xa như ký ức của thời gian, lưu giữ văn hóa truyền thống và cội nguồn dân tộc.",
    sampleText: "Cuộc đời như một dòng sông, đi qua bao thác ghềnh rồi cũng tìm về với biển lớn tĩnh lặng và bao dung...",
    edgePitch: "-24%",
    edgeRate: "-20%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -2.4,
      detune: -240,
      rate: 0.85,
      lowGain: 3.4,
      lowFreq: 150,
      midFreq: 820,
      midGain: 1.9,
      presenceFreq: 2900,
      presenceGain: 3.8,
      highGain: 2.2,
      highFreq: 6600,
      reverb: 0.07,
      reverbDecay: 0.40,
      compressor: { threshold: -17, ratio: 3.2, attack: 0.010, release: 0.25 }
    },
    dna: {
      persona: { age: "60-70", personality: "trí tuệ, thong thả, ký ức, di sản" },
      acoustic: { f0: "125-165Hz", resonance: "chest", brightness: 32, warmth: 96, articulation: 90 }
    }
  },
  {
    id: "vn_f_dna_40_benevolent_70",
    name: "40. Cụ Bà Ngọc Cầm 👑 (Nữ 65-75t - Nhân Hậu & Tình Cảm Gia Đình Cội Nguồn [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "👵 Nhân Hậu 70+ VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "40-70",
    styleCategory: "tam_su",
    category: "Nhân Hậu Cội Nguồn (65-75t) • Miền Bắc",
    pitch: 0.80,
    rate: 0.82,
    recommendedFor: "both",
    desc: "Giọng bà cụ nhân hậu, đầm ấm hiền từ như lời ru của bà, đong đầy tình cảm gia đình thiêng liêng ấm áp.",
    sampleText: "Các cháu nhớ nhé, đi đâu về đâu thì tình cảm gia đình và đạo nghĩa làm người vẫn luôn là gốc rễ bền chặt nhất.",
    edgePitch: "-28%",
    edgeRate: "-24%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -2.8,
      detune: -280,
      rate: 0.82,
      lowGain: 3.6,
      lowFreq: 145,
      midFreq: 800,
      midGain: 1.8,
      presenceFreq: 2800,
      presenceGain: 3.6,
      highGain: 2.0,
      highFreq: 6400,
      reverb: 0.08,
      reverbDecay: 0.45,
      compressor: { threshold: -16, ratio: 3.0, attack: 0.012, release: 0.30 }
    },
    dna: {
      persona: { age: "65-75", personality: "nhân hậu, hiền từ, đạo nghĩa, cội nguồn" },
      acoustic: { f0: "115-155Hz", resonance: "chest", brightness: 28, warmth: 98, articulation: 86 }
    }
  },
  {
    id: "vn_f_dna_41_morning_radio",
    name: "41. Thảo Nguyên 👑 (Nữ 28-42t - Radio Buổi Sáng, Đánh Thức Năng Lượng Mới [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "☀️ Radio Sáng VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "28-40",
    styleCategory: "mc_btv",
    category: "Radio Buổi Sáng (28-42t) • Miền Bắc",
    pitch: 1.05,
    rate: 1.05,
    recommendedFor: "both",
    desc: "Giọng nữ radio buổi sáng rộn rã, đánh thức mọi nguồn năng lượng hứng khởi đón chào ngày mới tươi đẹp.",
    sampleText: "Chào buổi sáng quý thính giả! Chúc mọi người một ngày làm việc thật hiệu quả, tràn ngập may mắn và thành công nhé!",
    edgePitch: "+10%",
    edgeRate: "+8%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 1.2,
      detune: 120,
      rate: 1.05,
      lowGain: 0.5,
      lowFreq: 230,
      midFreq: 1300,
      midGain: 2.6,
      presenceFreq: 3900,
      presenceGain: 5.6,
      highGain: 4.0,
      highFreq: 7600,
      reverb: 0.04,
      reverbDecay: 0.22,
      compressor: { threshold: -21, ratio: 4.0, attack: 0.004, release: 0.14 }
    },
    dna: {
      persona: { age: "28-42", personality: "sáng rỡ, mở rộng, năng lượng mới, lạc quan" },
      acoustic: { f0: "185-225Hz", resonance: "face-mouth", brightness: 76, warmth: 74, articulation: 96 }
    }
  },
  {
    id: "vn_f_dna_42_midnight_radio",
    name: "42. Dạ Nguyệt 👑 (Nữ 32-48t - Radio Đêm Sâu, Lắng Đọng & Tự Sự [Sài Gòn])",
    provider: "system",
    tier: "pro",
    badge: "🌙 Radio Đêm VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "middle",
    ageRange: "28-40",
    styleCategory: "tam_su",
    category: "Radio Đêm Sâu (32-48t) • Miền Nam",
    pitch: 0.87,
    rate: 0.86,
    recommendedFor: "idol",
    desc: "Giọng nữ miền Nam tự sự đêm khuya, mộc mạc sâu lắng, đưa người nghe vào cõi bình yên và hoài niệm.",
    sampleText: "Đêm nay, hãy để những bản tình ca dịu dàng này đồng hành cùng bạn đi qua những khoảng lặng của tâm hồn...",
    edgePitch: "-18%",
    edgeRate: "-18%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -1.9,
      detune: -190,
      rate: 0.86,
      lowGain: 3.0,
      lowFreq: 160,
      midFreq: 870,
      midGain: 1.9,
      presenceFreq: 2950,
      presenceGain: 4.0,
      highGain: 3.6,
      highFreq: 7600,
      reverb: 0.14,
      reverbDecay: 0.70,
      compressor: { threshold: -16, ratio: 3.0, attack: 0.012, release: 0.35 }
    },
    dna: {
      persona: { age: "32-48", personality: "sâu, gần, yên tĩnh, tự sự" },
      acoustic: { f0: "145-185Hz", resonance: "chest-head", brightness: 35, warmth: 94, articulation: 88 }
    }
  },
  {
    id: "vn_f_dna_43_documentary_narrator",
    name: "43. Thu Hà 👑 (Nữ 35-50t - Thuyết Minh Khoa Học & Lịch Sử [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "🌍 Thuyết Minh VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "35-45",
    styleCategory: "mc_btv",
    category: "Thuyết Minh Phim (35-50t) • Miền Bắc",
    pitch: 0.92,
    rate: 0.92,
    recommendedFor: "both",
    desc: "Giọng nữ thuyết minh phim tài liệu khách quan, điện ảnh, nhả chữ tròn đầy mang chiều sâu của lịch sử và tự nhiên.",
    sampleText: "Hàng triệu năm kiến tạo địa chất đã tạo nên những kỳ quan thiên nhiên hùng vĩ và tráng lệ bậc nhất hành tinh.",
    edgePitch: "-12%",
    edgeRate: "-10%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -1.2,
      detune: -120,
      rate: 0.92,
      lowGain: 2.2,
      lowFreq: 180,
      midFreq: 960,
      midGain: 2.2,
      presenceFreq: 3300,
      presenceGain: 4.8,
      highGain: 3.0,
      highFreq: 7200,
      reverb: 0.06,
      reverbDecay: 0.32,
      compressor: { threshold: -20, ratio: 3.8, attack: 0.006, release: 0.18 }
    },
    dna: {
      persona: { age: "35-50", personality: "khách quan, điện ảnh, sâu sắc, chuẩn xác" },
      acoustic: { f0: "150-195Hz", resonance: "chest-mouth", brightness: 47, warmth: 78, articulation: 98 }
    }
  },
  {
    id: "vn_f_dna_44_youth_story",
    name: "44. Thảo My 👑 (Nữ 20-27t - Kể Chuyện Giới Trẻ, Sách Nói & Tiểu Thuyết [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "📖 Sách Nói VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "young",
    ageRange: "18-24",
    styleCategory: "tam_su",
    category: "Kể Chuyện Trẻ (20-27t) • Miền Bắc",
    pitch: 1.11,
    rate: 1.04,
    recommendedFor: "idol",
    desc: "Giọng nữ kể chuyện trẻ trung, biến hóa cảm xúc tài tình, vẽ nên thế giới tiểu thuyết sống động và lôi cuốn từng chương.",
    sampleText: "Ánh nắng ban mai rọi qua khung cửa sổ, khẽ đánh thức những giấc mơ thanh xuân còn đang ấp ủ...",
    edgePitch: "+20%",
    edgeRate: "+6%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 2.0,
      detune: 200,
      rate: 1.04,
      lowGain: -0.2,
      lowFreq: 220,
      midFreq: 1400,
      midGain: 3.0,
      presenceFreq: 4200,
      presenceGain: 5.8,
      highGain: 4.4,
      highFreq: 7800,
      reverb: 0.06,
      reverbDecay: 0.35,
      compressor: { threshold: -19, ratio: 3.6, attack: 0.006, release: 0.18 }
    },
    dna: {
      persona: { age: "20-27", personality: "hình ảnh, biến hóa, thanh xuân, cảm xúc" },
      acoustic: { f0: "205-250Hz", resonance: "face", brightness: 78, warmth: 70, articulation: 92 }
    }
  },
  {
    id: "vn_f_dna_45_anchor_trust",
    name: "45. Thanh Trúc 👑 (Nữ 35-50t - Giọng Điểm Tựa Niềm Tin & Thương Hiệu [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "🛡️ Điểm Tựa VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "35-45",
    styleCategory: "chuyengia",
    category: "Điểm Tựa Niềm Tin (35-50t) • Miền Bắc",
    pitch: 0.94,
    rate: 0.94,
    recommendedFor: "manager",
    desc: "Giọng nữ bình ổn vững chãi, tạo cảm giác an tâm tuyệt đối, khiến từng cam kết thương hiệu đều có trọng lượng thép.",
    sampleText: "Chúng tôi cam kết đồng hành cùng bạn trên mọi chặng đường, mang đến sự an tâm và giá trị vượt trội nhất.",
    edgePitch: "-8%",
    edgeRate: "-8%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -0.9,
      detune: -90,
      rate: 0.94,
      lowGain: 2.0,
      lowFreq: 190,
      midFreq: 1050,
      midGain: 2.3,
      presenceFreq: 3400,
      presenceGain: 5.0,
      highGain: 3.0,
      highFreq: 7200,
      reverb: 0.04,
      reverbDecay: 0.22,
      compressor: { threshold: -21, ratio: 4.0, attack: 0.005, release: 0.15 }
    },
    dna: {
      persona: { age: "35-50", personality: "bình ổn, an tâm, vững chãi, trọng lượng" },
      acoustic: { f0: "155-200Hz", resonance: "chest-face", brightness: 50, warmth: 91, articulation: 96 }
    }
  },
  {
    id: "vn_f_dna_46_sales_storyteller",
    name: "46. Kim Chi 👑 (Nữ 27-38t - Bán Hàng Bằng Câu Chuyện & KOC Review [Sài Gòn])",
    provider: "system",
    tier: "pro",
    badge: "🛍️ Story Seller",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "banhang",
    category: "Storyteller Bán Hàng (27-38t) • Miền Nam",
    pitch: 1.02,
    rate: 1.00,
    recommendedFor: "both",
    desc: "Giọng nữ bán hàng bằng nghệ thuật kể chuyện, đưa khách hàng đi từ sự đồng cảm, cảm xúc đến hành động mua sắm tự nhiên.",
    sampleText: "Trước đây mình cũng từng rất tự ti về làn da, cho đến khi tìm được bí quyết này và cuộc đời mình đã thay đổi hoàn toàn.",
    edgePitch: "+4%",
    edgeRate: "0%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 0.4,
      detune: 40,
      rate: 1.00,
      lowGain: 1.2,
      lowFreq: 215,
      midFreq: 1200,
      midGain: 2.5,
      presenceFreq: 3700,
      presenceGain: 5.2,
      highGain: 3.8,
      highFreq: 7500,
      reverb: 0.05,
      reverbDecay: 0.28,
      compressor: { threshold: -20, ratio: 3.8, attack: 0.005, release: 0.16 }
    },
    dna: {
      persona: { age: "27-38", personality: "đồng cảm, câu chuyện, thuyết phục, cảm xúc" },
      acoustic: { f0: "175-220Hz", resonance: "face-chest", brightness: 64, warmth: 82, articulation: 94 }
    }
  },
  {
    id: "vn_f_dna_47_best_friend_commerce",
    name: "47. Lan Anh 👑 (Nữ 24-34t - Bạn Thân Chốt Deal, UGC & Affiliate Khủng [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "young",
    ageRange: "20-28",
    styleCategory: "banhang",
    category: "Bạn Thân Chốt Deal (24-34t) • Miền Bắc",
    pitch: 1.06,
    rate: 1.04,
    recommendedFor: "idol",
    desc: "Giọng nữ KOC bạn thân chia sẻ deal hời, nói chuyện có tâm, giới thiệu sản phẩm chân thật khiến khách hàng chốt đơn rầm rộ.",
    sampleText: "Các bà ơi, canh mãi mới được đợt sale kịch sàn này đó, mua một được hai hời dã man luôn nè, bấm giỏ hàng liền nha!",
    edgePitch: "+12%",
    edgeRate: "+6%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 1.3,
      detune: 130,
      rate: 1.04,
      lowGain: 0.3,
      lowFreq: 230,
      midFreq: 1300,
      midGain: 2.7,
      presenceFreq: 4000,
      presenceGain: 5.5,
      highGain: 4.2,
      highFreq: 7700,
      reverb: 0.04,
      reverbDecay: 0.24,
      compressor: { threshold: -20, ratio: 4.0, attack: 0.004, release: 0.14 }
    },
    dna: {
      persona: { age: "24-34", personality: "chân thật, bạn thân, nhiệt tình, chốt đơn đỉnh" },
      acoustic: { f0: "190-235Hz", resonance: "face", brightness: 70, warmth: 86, articulation: 93 }
    }
  },
  {
    id: "vn_f_dna_48_brand_film_premium",
    name: "48. Linh Nga 👑 (Nữ 30-45t - TVC Phim Quảng Cáo & Nhãn Hàng Quốc Tế [Hà Nội])",
    provider: "system",
    tier: "pro",
    badge: "🎬 TVC Phim VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "28-40",
    styleCategory: "doanhnhan",
    category: "TVC Phim Cao Cấp (30-45t) • Miền Bắc",
    pitch: 0.93,
    rate: 0.92,
    recommendedFor: "both",
    desc: "Giọng nữ TVC quảng cáo sang trọng, ít chữ nhưng giàu không gian, tôn vinh đẳng cấp thượng hạng cho các thương hiệu hàng đầu.",
    sampleText: "Khơi nguồn cảm hứng vô tận, nơi đam mê và đẳng cấp kiến tạo nên những giá trị trường tồn cùng thời gian.",
    edgePitch: "-10%",
    edgeRate: "-10%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: -1.1,
      detune: -110,
      rate: 0.92,
      lowGain: 2.2,
      lowFreq: 180,
      midFreq: 960,
      midGain: 2.2,
      presenceFreq: 3300,
      presenceGain: 4.8,
      highGain: 4.2,
      highFreq: 7900,
      reverb: 0.08,
      reverbDecay: 0.46,
      compressor: { threshold: -19, ratio: 3.6, attack: 0.007, release: 0.24 }
    },
    dna: {
      persona: { age: "30-45", personality: "tối giản, đắt giá, điện ảnh, trường tồn" },
      acoustic: { f0: "160-205Hz", resonance: "chest-head", brightness: 46, warmth: 87, articulation: 94 }
    }
  },
  {
    id: "vn_f_dna_49_mega_event_host",
    name: "49. Hoàng Oanh 👑 (Nữ 27-40t - Host Đại Sự Kiện & Mega Show Trực Tiếp [Sài Gòn])",
    provider: "system",
    tier: "pro",
    badge: "🎤 Mega Show Host",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "mc_btv",
    category: "Mega Show Trực Tiếp (27-40t) • Miền Nam",
    pitch: 1.07,
    rate: 1.06,
    recommendedFor: "both",
    desc: "Giọng nữ host đại sự kiện năng lượng bùng nổ, làm chủ sân khấu hàng vạn khán giả, chuyển nhịp mạnh mẽ và dứt khoát.",
    sampleText: "Khoảnh khắc tuyệt vời nhất của đêm đại nhạc hội chính thức bắt đầu ngay bây giờ! Quý vị đã sẵn sàng chưa nào!",
    edgePitch: "+14%",
    edgeRate: "+8%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 1.4,
      detune: 140,
      rate: 1.06,
      lowGain: 1.0,
      lowFreq: 230,
      midFreq: 1300,
      midGain: 2.8,
      presenceFreq: 3900,
      presenceGain: 6.0,
      highGain: 3.8,
      highFreq: 7500,
      reverb: 0.06,
      reverbDecay: 0.32,
      compressor: { threshold: -23, ratio: 4.6, attack: 0.003, release: 0.12 }
    },
    dna: {
      persona: { age: "27-40", personality: "bùng nổ, làm chủ sân khấu, hoành tráng, cuốn hút" },
      acoustic: { f0: "190-235Hz", resonance: "mouth-face-chest", brightness: 74, warmth: 64, articulation: 99 }
    }
  },
  {
    id: "vn_f_dna_50_signature_universal",
    name: "50. Ngọc Nhi Signature 👑 (Nữ 26-38t - Giọng Nữ Toàn Năng Quốc Dân Chuẩn Mực [Toàn Quốc])",
    provider: "system",
    tier: "pro",
    badge: "👑 Signature VIP",
    gender: "Female",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "young",
    ageRange: "20-28",
    styleCategory: "idol_genz",
    category: "Signature Toàn Năng (26-38t) • Toàn Quốc",
    pitch: 1.03,
    rate: 1.02,
    recommendedFor: "idol",
    desc: "Giọng nữ Signature toàn năng mặc định cho AVA LIVE: Tự nhiên, linh hoạt, đa dụng hoàn hảo cho cả bán hàng, tư vấn, kể chuyện và xây dựng thương hiệu.",
    sampleText: "Dạ em Ngọc Nhi xin chào mừng tất cả quý vị và các bạn đã đến với không gian livestream chuyên nghiệp của AVA LIVE!",
    edgePitch: "+6%",
    edgeRate: "+4%",
    neuralVoice: "vi-VN-HoaiMyNeural",
    dspProfile: {
      semitones: 0.7,
      detune: 70,
      rate: 1.02,
      lowGain: 0.8,
      lowFreq: 225,
      midFreq: 1250,
      midGain: 2.6,
      presenceFreq: 3800,
      presenceGain: 5.4,
      highGain: 4.0,
      highFreq: 7600,
      reverb: 0.05,
      reverbDecay: 0.28,
      compressor: { threshold: -20, ratio: 4.0, attack: 0.005, release: 0.16 }
    },
    dna: {
      persona: { age: "26-38", personality: "toàn năng, tự nhiên, nụ cười rạng rỡ, chuẩn mực" },
      acoustic: { f0: "175-220Hz", resonance: "face-mouth-chest", brightness: 64, warmth: 80, articulation: 96 }
    }
  }
];
