/**
 * 👑 MASTER DNA 40 GIỌNG NAM VIỆT NAM ĐỘC BẢN TOÀN DIỆN (18 - 65+ TUỔI)
 * Thiết kế chuẩn xác từng dải tần số (Pitch / Rate / Formant / Presence EQ / Cảm xúc)
 * Phân hóa triệt để 100% không trùng lặp: 
 *  - 10 Giọng Nam Trẻ GenZ (18-24t)
 *  - 10 Giọng Nam Trưởng Thành (25-34t)
 *  - 10 Giọng Nam Trung Niên (35-45t)
 *  - 10 Giọng Nam Cao Niên / Già Dặn (46-65+t)
 */

export const MASTER_DNA_MALE_VIETNAMESE_40_VOICES = [
  // =========================================================================
  // 🌟 NHÓM 1: 10 GIỌNG NAM TRẺ GEN Z & BẮT TREND (18 - 24 TUỔI)
  // Tông giọng: Tươi sáng, cao ráo, trẻ trung, nhịp nhanh, hoạt ngôn, bắt trend TikTok
  // =========================================================================
  {
    id: "vn_m_genz_south_energetic_01",
    name: "01. Duy Phong 👑 (Nam Trẻ Sài Gòn Năng Động - TikTok Shorts & Bán Hàng GenZ [18-24t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "young",
    ageRange: "18-24",
    styleCategory: "idol_genz",
    category: "Nam Trẻ GenZ • Miền Nam",
    pitch: 1.08,
    rate: 1.16,
    recommendedFor: "both",
    desc: "Giọng nam trẻ Sài Gòn 18-24t siêu năng động, tươi sáng, nói nhanh bắt tai, chuyên trị video ngắn TikTok và livestream chốt deal GenZ.",
    sampleText: "Hello cả nhà mình ơi! Mẫu áo hoodie này mặc lên bao ngầu luôn nè, nhanh tay nhấn giỏ hàng săn deal độc quyền nha anh em!",
    edgePitch: "+15%",
    edgeRate: "+16%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 1.8,
      detune: 180,
      rate: 1.16,
      lowGain: -1.0,
      midFreq: 1350,
      midGain: 2.4,
      presenceFreq: 4000,
      presenceGain: 5.5,
      highGain: 3.5,
      reverb: 0.03,
      reverbDecay: 0.22,
      compressor: { threshold: -20, ratio: 4.5, attack: 0.003, release: 0.1 }
    },
    dna: {
      persona: { age: "18-24", personality: "năng động, tươi vui, hoạt ngôn, bắt trend" },
      acoustic: { pitch_range: "high-bright", clarity: 96, speed: 88, intonation: "energetic" }
    }
  },
  {
    id: "vn_m_genz_north_hype_02",
    name: "02. Minh Triết 👑 (Nam Trẻ Hà Nội Hoạt Ngôn - Review Công Nghệ & Giục Đơn [18-24t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "young",
    ageRange: "18-24",
    styleCategory: "banhang",
    category: "Nam Trẻ GenZ • Miền Bắc",
    pitch: 1.06,
    rate: 1.18,
    recommendedFor: "both",
    desc: "Giọng nam trẻ Hà Nội sắc sảo, tốc độ dồn dập, nhả chữ thông minh, chuyên review công nghệ và đẩy nhịp chốt đơn thần tốc.",
    sampleText: "Dừng lại 3 giây anh em ơi! Chiếc tai nghe chống ồn chủ động này vừa về kho với giá không tưởng, bấm mua ngay kẻo lỡ nhé!",
    edgePitch: "+12%",
    edgeRate: "+18%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 1.4,
      detune: 140,
      rate: 1.18,
      lowGain: -0.5,
      midFreq: 1300,
      midGain: 2.6,
      presenceFreq: 3900,
      presenceGain: 5.2,
      highGain: 3.2,
      reverb: 0.02,
      reverbDecay: 0.2,
      compressor: { threshold: -22, ratio: 4.8, attack: 0.002, release: 0.09 }
    },
    dna: {
      persona: { age: "18-24", personality: "sắc sảo, dồn dập, tự tin, công nghệ" },
      acoustic: { pitch_range: "bright-sharp", clarity: 98, speed: 90, intonation: "urgent" }
    }
  },
  {
    id: "vn_m_genz_central_fresh_03",
    name: "03. Hoàng Long 👑 (Nam Trẻ Đà Nẵng Duyên Dáng - Du Lịch, Ẩm Thực & Review [18-24t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "trung",
    ageGroup: "young",
    ageRange: "18-24",
    styleCategory: "sales_services",
    category: "Nam Trẻ GenZ • Miền Trung",
    pitch: 1.05,
    rate: 1.12,
    recommendedFor: "both",
    desc: "Giọng nam trẻ Đà Nẵng mộc mạc, tươi tắn, duyên dáng, lôi cuốn người nghe theo từng thước phim review ẩm thực và trải nghiệm du lịch.",
    sampleText: "Hôm nay mình sẽ dắt các bạn đi ăn hết những món đặc sản ngon quên lối về ở Đà Nẵng với giá cực kỳ sinh viên nè!",
    edgePitch: "+10%",
    edgeRate: "+14%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 1.1,
      detune: 110,
      rate: 1.12,
      lowGain: 0.0,
      midFreq: 1250,
      midGain: 2.2,
      presenceFreq: 3800,
      presenceGain: 5.0,
      highGain: 3.0,
      reverb: 0.04,
      reverbDecay: 0.25,
      compressor: { threshold: -19, ratio: 4.0, attack: 0.004, release: 0.12 }
    },
    dna: {
      persona: { age: "18-24", personality: "duyên dáng, chân thành, tươi mới" },
      acoustic: { pitch_range: "melodic-fresh", clarity: 95, speed: 84, intonation: "friendly" }
    }
  },
  {
    id: "vn_m_genz_gamer_caster_04",
    name: "04. Tuấn Kiệt 👑 (Nam BLV Game Sôi Động - PK Đỉnh Cao & Thách Đấu [18-24t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "young",
    ageRange: "18-24",
    styleCategory: "blv_game",
    category: "BLV Game PK • GenZ",
    pitch: 1.10,
    rate: 1.24,
    recommendedFor: "game",
    desc: "Giọng caster thể thao điện tử cực cháy, nhịp combat thần tốc, tạo không khí nghẹt thở và khuấy đảo toàn bộ khán phòng livestream.",
    sampleText: "Pha xử lý không thể tin nổi anh em ơi! Một mình cân bốn và lật kèo ngoạn mục, thả tim liên tục cổ vũ thần tượng nào!",
    edgePitch: "+14%",
    edgeRate: "+24%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 1.6,
      detune: 160,
      rate: 1.24,
      lowGain: -0.5,
      midFreq: 1400,
      midGain: 3.2,
      presenceFreq: 4100,
      presenceGain: 5.8,
      highGain: 3.6,
      reverb: 0.02,
      reverbDecay: 0.18,
      compressor: { threshold: -24, ratio: 5.5, attack: 0.001, release: 0.07 }
    },
    dna: {
      persona: { age: "18-24", personality: "bùng nổ, tốc độ, nhiệt huyết, chiến binh" },
      acoustic: { pitch_range: "high-punchy", clarity: 97, speed: 96, intonation: "explosive" }
    }
  },
  {
    id: "vn_m_genz_vlog_lifestyle_05",
    name: "05. Gia Huy 👑 (Nam Vlog Đời Sống - Thân Thiện, Hài Hước & Viral [18-24t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "young",
    ageRange: "18-24",
    styleCategory: "idol_genz",
    category: "Vlog & Lifestyle • GenZ",
    pitch: 1.04,
    rate: 1.12,
    recommendedFor: "both",
    desc: "Giọng nam vlogger đối thoại gần gũi như bạn thân, pha chút hài hước dí dỏm, giữ chân người xem từ đầu đến cuối clip.",
    sampleText: "Hôm nay mình quyết định thử thách 24 giờ sống theo yêu cầu của các bạn fan, cùng xem kết quả bất ngờ này nha!",
    edgePitch: "+11%",
    edgeRate: "+12%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 1.2,
      detune: 120,
      rate: 1.12,
      lowGain: 0.0,
      midFreq: 1280,
      midGain: 2.4,
      presenceFreq: 3850,
      presenceGain: 4.8,
      highGain: 3.0,
      reverb: 0.03,
      reverbDecay: 0.22,
      compressor: { threshold: -20, ratio: 4.2, attack: 0.004, release: 0.12 }
    },
    dna: {
      persona: { age: "18-24", personality: "thân thiện, hài hước, tự nhiên" },
      acoustic: { pitch_range: "conversational", clarity: 95, speed: 85, intonation: "playful" }
    }
  },
  {
    id: "vn_m_genz_fashion_beauty_06",
    name: "06. Bảo Nam 👑 (Nam Stylist Thời Trang - Tươi Sáng & Tư Vấn Outfit [18-24t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "young",
    ageRange: "18-24",
    styleCategory: "sales_services",
    category: "Thời Trang & Outfit • GenZ",
    pitch: 1.07,
    rate: 1.14,
    recommendedFor: "both",
    desc: "Giọng nam tư vấn phong cách sành điệu, trẻ trung, nhạy bén xu hướng, chuyên livestream bán quần áo, giày sneaker và phụ kiện.",
    sampleText: "Set đồ này phối lên là tôn dáng chuẩn chỉnh, đi học đi chơi đều cực kỳ cuốn hút, mấy bạn nhanh tay lấy mã giảm giá nha!",
    edgePitch: "+13%",
    edgeRate: "+15%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 1.5,
      detune: 150,
      rate: 1.14,
      lowGain: -0.5,
      midFreq: 1320,
      midGain: 2.5,
      presenceFreq: 3950,
      presenceGain: 5.0,
      highGain: 3.4,
      reverb: 0.03,
      reverbDecay: 0.24,
      compressor: { threshold: -21, ratio: 4.4, attack: 0.003, release: 0.11 }
    },
    dna: {
      persona: { age: "18-24", personality: "sành điệu, tươi sáng, tư vấn khéo" },
      acoustic: { pitch_range: "stylish-bright", clarity: 96, speed: 86, intonation: "convincing" }
    }
  },
  {
    id: "vn_m_genz_unboxing_tech_07",
    name: "07. Khôi Nguyên 👑 (Nam Reviewer Đập Hộp - Nhạy Bén & Tinh Tế [18-24t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "young",
    ageRange: "18-24",
    styleCategory: "sales_services",
    category: "Đập Hộp & Gadget • GenZ",
    pitch: 1.05,
    rate: 1.15,
    recommendedFor: "both",
    desc: "Giọng nam mở hộp đồ chơi công nghệ, mô hình, phụ kiện với ngữ điệu háo hức, từng chi tiết được mô tả sinh động và chân thực.",
    sampleText: "Cảm giác bóc seal chiếc máy này quá đã luôn các bạn! Độ hoàn thiện tỉ mỉ vượt xa kỳ vọng trong tầm giá này!",
    edgePitch: "+9%",
    edgeRate: "+16%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 1.0,
      detune: 100,
      rate: 1.15,
      lowGain: -0.2,
      midFreq: 1260,
      midGain: 2.3,
      presenceFreq: 3750,
      presenceGain: 4.9,
      highGain: 3.1,
      reverb: 0.03,
      reverbDecay: 0.22,
      compressor: { threshold: -20, ratio: 4.2, attack: 0.004, release: 0.12 }
    },
    dna: {
      persona: { age: "18-24", personality: "tinh tế, háo hức, khách quan" },
      acoustic: { pitch_range: "crisp-curious", clarity: 97, speed: 87, intonation: "engaging" }
    }
  },
  {
    id: "vn_m_genz_west_cheerful_08",
    name: "08. Quốc Bảo 👑 (Nam Miền Tây Xởi Lởi - Nông Sản, Trái Cây & Ẩm Thực [18-24t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "tay",
    ageGroup: "young",
    ageRange: "18-24",
    styleCategory: "banhang",
    category: "Nông Sản Miền Tây • GenZ",
    pitch: 1.04,
    rate: 1.14,
    recommendedFor: "both",
    desc: "Giọng nam miền Tây sông nước 18-24t hào sảng, xởi lởi, thật thà, tạo cảm giác thân thuộc như người nhà, chốt đơn hoa quả ngọt lịm.",
    sampleText: "Dạ em chào cô chú anh chị nha! Sầu riêng vườn nhà em bao cơm vàng hạt lép, ăn không ngon em hoàn tiền tận tay liền ạ!",
    edgePitch: "+8%",
    edgeRate: "+14%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 0.9,
      detune: 90,
      rate: 1.14,
      lowGain: 0.2,
      midFreq: 1220,
      midGain: 2.4,
      presenceFreq: 3700,
      presenceGain: 5.2,
      highGain: 2.8,
      reverb: 0.04,
      reverbDecay: 0.26,
      compressor: { threshold: -21, ratio: 4.5, attack: 0.003, release: 0.13 }
    },
    dna: {
      persona: { age: "18-24", personality: "thật thà, xởi lởi, dân dã, ấm áp" },
      acoustic: { pitch_range: "warm-rustic", clarity: 95, speed: 86, intonation: "sincere" }
    }
  },
  {
    id: "vn_m_genz_acoustic_chill_09",
    name: "09. Hải Đăng 👑 (Nam Acoustic Thư Thái - Podcast Tâm Sự & Âm Nhạc Chill [18-24t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "standard",
    ageGroup: "young",
    ageRange: "18-24",
    styleCategory: "tam_su",
    category: "Chill & Podcast • GenZ",
    pitch: 1.03,
    rate: 1.06,
    recommendedFor: "both",
    desc: "Giọng nam trẻ êm đềm, thư thái, mộc mạc như tiếng đàn guitar đêm muộn, vỗ về tâm hồn và dẫn dắt câu chuyện sâu lắng.",
    sampleText: "Khép lại một ngày bận rộn, hãy để bản thân được nghỉ ngơi và lắng nghe những giai điệu bình yên này bạn nhé.",
    edgePitch: "+7%",
    edgeRate: "+8%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 0.8,
      detune: 80,
      rate: 1.06,
      lowGain: 0.5,
      midFreq: 1180,
      midGain: 2.2,
      presenceFreq: 3600,
      presenceGain: 4.6,
      highGain: 2.6,
      reverb: 0.05,
      reverbDecay: 0.35,
      compressor: { threshold: -18, ratio: 3.8, attack: 0.005, release: 0.16 }
    },
    dna: {
      persona: { age: "18-24", personality: "thư thái, ấm áp, nghệ sĩ, chữa lành" },
      acoustic: { pitch_range: "smooth-mellow", clarity: 94, speed: 78, intonation: "calming" }
    }
  },
  {
    id: "vn_m_genz_podcast_smart_10",
    name: "10. Tuấn Anh 👑 (Nam Tri Thức Trẻ - Sách Nói, Tư Duy & Phát Triển Bản Thân [18-24t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "young",
    ageRange: "18-24",
    styleCategory: "mc_btv",
    category: "Tri Thức & Sách Nói • GenZ",
    pitch: 1.02,
    rate: 1.08,
    recommendedFor: "both",
    desc: "Giọng nam sinh viên đại học chuẩn phát âm, mạch lạc, thông minh, chia sẻ bài học kỹ năng và đúc kết sách nói lôi cuốn.",
    sampleText: "Kỷ luật bản thân không phải là sự gò bó, mà chính là chiếc chìa khóa đầu tiên mở ra sự tự do đích thực cho tương lai của bạn.",
    edgePitch: "+6%",
    edgeRate: "+10%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 0.7,
      detune: 70,
      rate: 1.08,
      lowGain: 0.2,
      midFreq: 1200,
      midGain: 2.3,
      presenceFreq: 3550,
      presenceGain: 4.7,
      highGain: 2.7,
      reverb: 0.03,
      reverbDecay: 0.24,
      compressor: { threshold: -19, ratio: 4.0, attack: 0.004, release: 0.14 }
    },
    dna: {
      persona: { age: "18-24", personality: "thông minh, điềm đạm, tri thức, tự tin" },
      acoustic: { pitch_range: "articulate-smart", clarity: 98, speed: 82, intonation: "inspiring" }
    }
  },

  // =========================================================================
  // 👔 NHÓM 2: 10 GIỌNG NAM THANH NIÊN & TRƯỞNG THÀNH (25 - 34 TUỔI)
  // Tông giọng: Tự tin, ấm áp, hiện đại, đĩnh đạc, chốt deal sắc bén, MC sự kiện
  // =========================================================================
  {
    id: "vn_m_adult_north_sales_pro_11",
    name: "11. Mạnh Dũng 👑 (Nam Chốt Sale Hà Nội - Quyết Đoán & Uy Quyền [25-34t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "banhang",
    category: "Chốt Sale Quyết Đoán • Miền Bắc",
    pitch: 1.02,
    rate: 1.10,
    recommendedFor: "manager",
    desc: "Giọng nam trưởng thành Hà Nội 25-34t đanh thép, chắc nịch, phân tích sắc bén, đẩy tính cấp bách khiến khách hàng tin tưởng tuyệt đối.",
    sampleText: "Đây là giải pháp toàn diện và tối ưu nhất trên thị trường hiện nay. Anh chị bấm đặt ngay bây giờ để nhận trọn gói ưu đãi độc quyền!",
    edgePitch: "+3%",
    edgeRate: "+12%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 0.3,
      detune: 30,
      rate: 1.10,
      lowGain: 0.5,
      midFreq: 1100,
      midGain: 2.6,
      presenceFreq: 3600,
      presenceGain: 5.2,
      highGain: 2.8,
      reverb: 0.03,
      reverbDecay: 0.22,
      compressor: { threshold: -21, ratio: 4.6, attack: 0.003, release: 0.12 }
    },
    dna: {
      persona: { age: "25-34", personality: "quyết đoán, sắc bén, chuyên nghiệp, uy lực" },
      acoustic: { pitch_range: "authoritative", clarity: 99, speed: 85, intonation: "commanding" }
    }
  },
  {
    id: "vn_m_adult_south_sales_pro_12",
    name: "12. Hữu Thắng 👑 (Nam Chốt Sale Sài Gòn - Thuyết Phục & Cuốn Hút [25-34t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "banhang",
    category: "Chốt Deal Cuốn Hút • Miền Nam",
    pitch: 1.03,
    rate: 1.12,
    recommendedFor: "both",
    desc: "Giọng nam kinh doanh Sài Gòn linh hoạt, cuốn hút, chốt đơn mượt mà với kỹ năng xử lý từ chối và nghệ thuật bán hàng hiện đại.",
    sampleText: "Dạ đúng rồi anh em ơi! Số lượng quà tặng có hạn trong phiên live này thôi, nhanh tay chốt đơn kẻo hệ thống tự đóng cổng khuyến mãi nha!",
    edgePitch: "+4%",
    edgeRate: "+14%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 0.4,
      detune: 40,
      rate: 1.12,
      lowGain: 0.4,
      midFreq: 1150,
      midGain: 2.5,
      presenceFreq: 3650,
      presenceGain: 5.0,
      highGain: 2.9,
      reverb: 0.03,
      reverbDecay: 0.24,
      compressor: { threshold: -20, ratio: 4.4, attack: 0.004, release: 0.12 }
    },
    dna: {
      persona: { age: "25-34", personality: "thuyết phục, cuốn hút, hoạt bát, đĩnh đạc" },
      acoustic: { pitch_range: "persuasive", clarity: 97, speed: 87, intonation: "dynamic" }
    }
  },
  {
    id: "vn_m_adult_mc_event_13",
    name: "13. Trọng Tấn 👑 (Nam MC Sự Kiện Trực Tiếp - Hào Sảng & Sang Trọng [25-34t])",
    provider: "system",
    tier: "pro",
    badge: "👑 Studio VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "mc_btv",
    category: "MC Sự Kiện Sang Trọng • 25-34t",
    pitch: 1.01,
    rate: 1.06,
    recommendedFor: "both",
    desc: "Giọng MC sự kiện trực tiếp hào sảng, tròn vành rõ chữ, âm vang sang trọng, tôn vinh thương hiệu và dẫn dắt chương trình đẳng cấp.",
    sampleText: "Kính thưa toàn thể quý vị đại biểu và quý khách hàng, chào mừng quý vị đến với buổi dạ tiệc vinh danh những bước tiến vượt bậc của năm nay!",
    edgePitch: "+2%",
    edgeRate: "+8%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 0.2,
      detune: 20,
      rate: 1.06,
      lowGain: 0.8,
      midFreq: 1050,
      midGain: 2.7,
      presenceFreq: 3500,
      presenceGain: 5.0,
      highGain: 2.8,
      reverb: 0.04,
      reverbDecay: 0.28,
      compressor: { threshold: -20, ratio: 4.2, attack: 0.005, release: 0.15 }
    },
    dna: {
      persona: { age: "25-34", personality: "hào sảng, đĩnh đạc, sang trọng, uy nghi" },
      acoustic: { pitch_range: "grand-resonant", clarity: 99, speed: 82, intonation: "ceremonial" }
    }
  },
  {
    id: "vn_m_adult_trainer_expert_14",
    name: "14. Thế Vinh 👑 (Nam Chuyên Gia Đào Tạo - Truyền Động Lực & Bản Lĩnh [25-34t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "sales_services",
    category: "Đào Tạo & Động Lực • 25-34t",
    pitch: 1.01,
    rate: 1.08,
    recommendedFor: "both",
    desc: "Giọng diễn giả truyền cảm hứng mạnh mẽ, từng câu chữ thắp lửa ý chí, truyền tải kiến thức kinh doanh và tư duy chiến lược sâu sắc.",
    sampleText: "Không có giới hạn nào ngoài những rào cản bạn tự đặt ra trong tâm trí. Hãy hành động ngay từ hôm nay để làm chủ vận mệnh của chính mình!",
    edgePitch: "+1%",
    edgeRate: "+10%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 0.1,
      detune: 10,
      rate: 1.08,
      lowGain: 0.6,
      midFreq: 1080,
      midGain: 2.6,
      presenceFreq: 3450,
      presenceGain: 4.8,
      highGain: 2.7,
      reverb: 0.03,
      reverbDecay: 0.25,
      compressor: { threshold: -21, ratio: 4.5, attack: 0.004, release: 0.14 }
    },
    dna: {
      persona: { age: "25-34", personality: "truyền lửa, bản lĩnh, sâu sắc, lôi cuốn" },
      acoustic: { pitch_range: "motivational", clarity: 98, speed: 84, intonation: "empowering" }
    }
  },
  {
    id: "vn_m_adult_finance_crypto_15",
    name: "15. Tiến Đạt 👑 (Nam Tài Chính & Đầu Tư - Chuẩn Xác & Đáng Tin Cậy [25-34t])",
    provider: "system",
    tier: "pro",
    badge: "👑 Studio VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "mc_btv",
    category: "Tài Chính & Đầu Tư • 25-34t",
    pitch: 1.00,
    rate: 1.06,
    recommendedFor: "both",
    desc: "Giọng nam tài chính sắc bén, điềm đạm, minh bạch, phân tích dữ liệu thị trường và xu hướng kinh tế với độ tin cậy tuyệt đối.",
    sampleText: "Phân bổ danh mục thông minh và quản trị rủi ro chặt chẽ là nền tảng vững chắc nhất giúp bạn bảo toàn và gia tăng tài sản bền vững.",
    edgePitch: "+0%",
    edgeRate: "+8%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 0.0,
      detune: 0,
      rate: 1.06,
      lowGain: 0.5,
      midFreq: 1000,
      midGain: 2.5,
      presenceFreq: 3400,
      presenceGain: 4.8,
      highGain: 2.6,
      reverb: 0.02,
      reverbDecay: 0.2,
      compressor: { threshold: -20, ratio: 4.2, attack: 0.005, release: 0.15 }
    },
    dna: {
      persona: { age: "25-34", personality: "minh bạch, chuẩn xác, điềm đạm, tài chính" },
      acoustic: { pitch_range: "analytical", clarity: 99, speed: 82, intonation: "authoritative" }
    }
  },
  {
    id: "vn_m_adult_cinema_trailer_16",
    name: "16. Hoàng Nam 👑 (Nam Thuyết Minh Phim Bom Tấn - Hùng Tráng & Kịch Tính [25-34t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "standard",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "tam_su",
    category: "Thuyết Minh Phim & Trailer • 25-34t",
    pitch: 0.99,
    rate: 1.05,
    recommendedFor: "both",
    desc: "Giọng nam thuyết minh điện ảnh Hollywood, âm vực dày dặn, giàu kịch tính, lôi kéo người xem vào những cuộc phiêu lưu sử thi kỳ vĩ.",
    sampleText: "Khi định mệnh gọi tên, người anh hùng sẽ đứng lên vượt qua mọi giới hạn để bảo vệ những gì quý giá nhất.",
    edgePitch: "-1%",
    edgeRate: "+6%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.1,
      detune: 0,
      rate: 1.05,
      lowGain: 1.2,
      midFreq: 950,
      midGain: 2.8,
      presenceFreq: 3350,
      presenceGain: 5.2,
      highGain: 2.5,
      reverb: 0.05,
      reverbDecay: 0.35,
      compressor: { threshold: -22, ratio: 4.8, attack: 0.003, release: 0.14 }
    },
    dna: {
      persona: { age: "25-34", personality: "hùng tráng, kịch tính, điện ảnh, nội lực" },
      acoustic: { pitch_range: "cinematic-deep", clarity: 97, speed: 80, intonation: "dramatic" }
    }
  },
  {
    id: "vn_m_adult_central_warm_17",
    name: "17. Thanh Bình 👑 (Nam Miền Trung Truyền Cảm - Giàu Cảm Xúc & Tự Nhiên [25-34t])",
    provider: "system",
    tier: "pro",
    badge: "👑 Studio VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "trung",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "tam_su",
    category: "Truyền Cảm Miền Trung • 25-34t",
    pitch: 1.01,
    rate: 1.05,
    recommendedFor: "both",
    desc: "Giọng nam miền Trung ấm áp, trầm lắng, chân thành, chạm đến trái tim người nghe trong các video tâm sự và chia sẻ cuộc sống.",
    sampleText: "Có những điều giản dị quanh ta mà đôi khi vội vã ta đã lãng quên, dừng lại một chút để cảm nhận trọn vẹn sự yêu thương này nhé.",
    edgePitch: "+2%",
    edgeRate: "+8%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 0.2,
      detune: 20,
      rate: 1.05,
      lowGain: 0.6,
      midFreq: 1100,
      midGain: 2.4,
      presenceFreq: 3500,
      presenceGain: 4.7,
      highGain: 2.6,
      reverb: 0.04,
      reverbDecay: 0.3,
      compressor: { threshold: -19, ratio: 4.0, attack: 0.005, release: 0.15 }
    },
    dna: {
      persona: { age: "25-34", personality: "chân thành, sâu lắng, mộc mạc, ấm áp" },
      acoustic: { pitch_range: "heartfelt", clarity: 96, speed: 80, intonation: "sincere" }
    }
  },
  {
    id: "vn_m_adult_bds_luxury_18",
    name: "18. Anh Quân 👑 (Nam Tư Vấn Bất Động Sản - Lịch Thiệp & Đẳng Cấp [25-34t])",
    provider: "system",
    tier: "pro",
    badge: "👑 Studio VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "sales_services",
    category: "Bất Động Sản Luxury • 25-34t",
    pitch: 1.00,
    rate: 1.05,
    recommendedFor: "manager",
    desc: "Giọng nam tư vấn biệt thự và căn hộ hạng sang, lịch thiệp, đĩnh đạc, ngôn từ trau chuốt, định vị đẳng cấp thượng lưu cho khách hàng VIP.",
    sampleText: "Tọa lạc tại vị trí độc tôn với tầm nhìn ôm trọn sông Hồng, mỗi căn biệt thự tại đây là một tuyệt tác kiến trúc khẳng định vị thế chủ nhân.",
    edgePitch: "+0%",
    edgeRate: "+6%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 0.0,
      detune: 0,
      rate: 1.05,
      lowGain: 0.8,
      midFreq: 1020,
      midGain: 2.5,
      presenceFreq: 3400,
      presenceGain: 4.9,
      highGain: 2.7,
      reverb: 0.04,
      reverbDecay: 0.28,
      compressor: { threshold: -20, ratio: 4.2, attack: 0.005, release: 0.15 }
    },
    dna: {
      persona: { age: "25-34", personality: "lịch thiệp, đẳng cấp, sang trọng, uy tín" },
      acoustic: { pitch_range: "refined-luxury", clarity: 99, speed: 80, intonation: "gentleman" }
    }
  },
  {
    id: "vn_m_adult_story_night_19",
    name: "19. Đình Phong 👑 (Nam Kể Chuyện Đêm Khuya - Trầm Ấm & Vỗ Về [25-34t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "standard",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "tam_su",
    category: "Kể Chuyện Đêm Khuya • 25-34t",
    pitch: 0.98,
    rate: 1.02,
    recommendedFor: "both",
    desc: "Giọng nam radio đêm khuya ấm áp như tách trà gừng, đưa người nghe vào không gian thư thái, xua tan mọi âu lo mệt mỏi của một ngày dài.",
    sampleText: "Đêm đã về khuya rồi, mong rằng bạn sẽ tìm thấy sự nhẹ nhõm trong tâm hồn và có một giấc ngủ thật ngon, thật an lành nhé.",
    edgePitch: "-2%",
    edgeRate: "+4%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.2,
      detune: 0,
      rate: 1.02,
      lowGain: 1.4,
      midFreq: 900,
      midGain: 2.6,
      presenceFreq: 3300,
      presenceGain: 4.5,
      highGain: 2.3,
      reverb: 0.06,
      reverbDecay: 0.4,
      compressor: { threshold: -18, ratio: 3.8, attack: 0.006, release: 0.18 }
    },
    dna: {
      persona: { age: "25-34", personality: "trầm ấm, vỗ về, chữa lành, tinh tế" },
      acoustic: { pitch_range: "deep-soothing", clarity: 95, speed: 76, intonation: "hypnotic" }
    }
  },
  {
    id: "vn_m_adult_fitness_coach_20",
    name: "20. Việt Hùng 👑 (Nam HLV Thể Thao - Khỏe Khoắn & Tràn Đầy Sức Sống [25-34t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "middle",
    ageRange: "25-34",
    styleCategory: "sales_services",
    category: "Thể Thao & Năng Lượng • 25-34t",
    pitch: 1.02,
    rate: 1.15,
    recommendedFor: "both",
    desc: "Giọng nam huấn luyện viên thể hình cường tráng, thúc giục vận động, bán thực phẩm bổ sung, gym và đồ tập năng lượng cao.",
    sampleText: "Chỉ còn 30 giây cuối cùng thôi anh em! Giữ vững nhịp thở và bứt phá giới hạn để chinh phục mục tiêu vóc dáng lý tưởng nào!",
    edgePitch: "+3%",
    edgeRate: "+15%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: 0.3,
      detune: 30,
      rate: 1.15,
      lowGain: 0.6,
      midFreq: 1150,
      midGain: 2.8,
      presenceFreq: 3600,
      presenceGain: 5.3,
      highGain: 2.9,
      reverb: 0.03,
      reverbDecay: 0.22,
      compressor: { threshold: -22, ratio: 4.8, attack: 0.002, release: 0.1 }
    },
    dna: {
      persona: { age: "25-34", personality: "khỏe khoắn, thôi thúc, dứt khoát, thể thao" },
      acoustic: { pitch_range: "athletic-strong", clarity: 98, speed: 89, intonation: "driven" }
    }
  },

  // =========================================================================
  // 🏢 NHÓM 3: 10 GIỌNG NAM TRUNG NIÊN & DOANH NHÂN (35 - 45 TUỔI)
  // Tông giọng: Đĩnh đạc, chững chạc, uy quyền, dõng dạc, nội lực, đầm chắc
  // =========================================================================
  {
    id: "vn_m_middle_ceo_authority_21",
    name: "21. Quang Minh 👑 (Nam CEO Doanh Nhân - Đĩnh Đạc, Vững Vàng & Tầm Vóc [35-45t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "35-45",
    styleCategory: "banhang",
    category: "CEO & Lãnh Đạo VIP • 35-45t",
    pitch: 0.98,
    rate: 1.05,
    recommendedFor: "manager",
    desc: "Giọng nam lãnh đạo doanh nghiệp 35-45t dõng dạc, uy lực, đĩnh đạc, phong thái quyết đoán của người cầm lái con thuyền kinh doanh lớn.",
    sampleText: "Bản lĩnh của doanh nghiệp được khẳng định qua khả năng vượt bão và tiên phong đổi mới để tạo ra những giá trị phụng sự cộng đồng.",
    edgePitch: "-3%",
    edgeRate: "+6%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.3,
      detune: 0,
      rate: 1.05,
      lowGain: 1.2,
      midFreq: 850,
      midGain: 2.8,
      presenceFreq: 3300,
      presenceGain: 5.0,
      highGain: 2.4,
      reverb: 0.03,
      reverbDecay: 0.25,
      compressor: { threshold: -21, ratio: 4.4, attack: 0.005, release: 0.15 }
    },
    dna: {
      persona: { age: "35-45", personality: "lãnh đạo, uy quyền, vững vàng, tầm vóc" },
      acoustic: { pitch_range: "executive-baritone", clarity: 99, speed: 80, intonation: "authoritative" }
    }
  },
  {
    id: "vn_m_middle_btv_vtv_22",
    name: "22. Trần Hưng 👑 (Nam BTV Thời Sự Quốc Gia - Chuẩn Mực, Tròn Vành Rõ Chữ [35-45t])",
    provider: "system",
    tier: "pro",
    badge: "👑 Studio VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "35-45",
    styleCategory: "mc_btv",
    category: "Thời Sự & Truyền Hình • 35-45t",
    pitch: 0.99,
    rate: 1.04,
    recommendedFor: "both",
    desc: "Giọng nam phát thanh viên thời sự truyền hình quốc gia, phát âm mẫu mực từng phụ âm, trang trọng và đáng tin cậy tuyệt đối.",
    sampleText: "Kính chào quý vị và các bạn đang theo dõi bản tin truyền hình thời sự đặc biệt phát sóng trực tiếp hôm nay.",
    edgePitch: "-2%",
    edgeRate: "+6%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.2,
      detune: 0,
      rate: 1.04,
      lowGain: 1.0,
      midFreq: 900,
      midGain: 2.8,
      presenceFreq: 3400,
      presenceGain: 5.2,
      highGain: 2.5,
      reverb: 0.02,
      reverbDecay: 0.2,
      compressor: { threshold: -20, ratio: 4.2, attack: 0.005, release: 0.16 }
    },
    dna: {
      persona: { age: "35-45", personality: "chuẩn mực, trang trọng, tròn trịa, chuẩn quốc gia" },
      acoustic: { pitch_range: "broadcast-news", clarity: 100, speed: 80, intonation: "official" }
    }
  },
  {
    id: "vn_m_middle_sales_iron_23",
    name: "23. Bá Cường 👑 (Nam Chốt Deal Tiền Tỷ - Đanh Thép, Chắc Nịch & Sắc Bén [35-45t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "35-45",
    styleCategory: "banhang",
    category: "Chốt Deal Bất Động Sản & Dự Án • 35-45t",
    pitch: 0.97,
    rate: 1.07,
    recommendedFor: "manager",
    desc: "Giọng nam chốt dự án tiền tỷ, đanh thép, chắc nịch từng con số, nắm bắt tâm lý khách hàng siêu phàm và dứt điểm nhanh gọn.",
    sampleText: "Cơ hội sinh lời vượt trội đã hiện hữu rõ ràng trước mắt. Quyết định đầu tư hôm nay sẽ khẳng định vị thế tương lai của các bác!",
    edgePitch: "-4%",
    edgeRate: "+8%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.4,
      detune: 0,
      rate: 1.07,
      lowGain: 1.3,
      midFreq: 800,
      midGain: 3.0,
      presenceFreq: 3250,
      presenceGain: 5.1,
      highGain: 2.3,
      reverb: 0.03,
      reverbDecay: 0.22,
      compressor: { threshold: -22, ratio: 4.6, attack: 0.003, release: 0.12 }
    },
    dna: {
      persona: { age: "35-45", personality: "đanh thép, chắc nịch, chốt deal, tiền tỷ" },
      acoustic: { pitch_range: "iron-closer", clarity: 99, speed: 83, intonation: "uncompromising" }
    }
  },
  {
    id: "vn_m_middle_doc_history_24",
    name: "24. Khắc Việt 👑 (Nam Phóng Sự Lịch Sử - Trầm Hùng & Sâu Sắc [35-45t])",
    provider: "system",
    tier: "pro",
    badge: "👑 Studio VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "standard",
    ageGroup: "middle",
    ageRange: "35-45",
    styleCategory: "tam_su",
    category: "Phóng Sự & Sử Thi • 35-45t",
    pitch: 0.96,
    rate: 1.03,
    recommendedFor: "both",
    desc: "Giọng nam thuyết minh phim tài liệu lịch sử, trầm hùng, sâu sắc, dẫn dắt người nghe qua những thăng trầm vẻ vang của dân tộc.",
    sampleText: "Dưới bóng cờ khởi nghĩa, những đoàn quân áo vải đã làm nên những chiến công lẫy lừng, tạc ghi muôn đời vào sử sách.",
    edgePitch: "-5%",
    edgeRate: "+4%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.5,
      detune: 0,
      rate: 1.03,
      lowGain: 1.6,
      midFreq: 750,
      midGain: 3.0,
      presenceFreq: 3200,
      presenceGain: 4.8,
      highGain: 2.2,
      reverb: 0.05,
      reverbDecay: 0.38,
      compressor: { threshold: -20, ratio: 4.2, attack: 0.006, release: 0.18 }
    },
    dna: {
      persona: { age: "35-45", personality: "trầm hùng, sâu sắc, sử thi, tự hào" },
      acoustic: { pitch_range: "epic-historic", clarity: 98, speed: 78, intonation: "monumental" }
    }
  },
  {
    id: "vn_m_middle_south_master_25",
    name: "25. Thanh Tùng 👑 (Nam Miền Nam Bản Lĩnh - Hào Sảng, Tin Cậy & Thân Tình [35-45t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "middle",
    ageRange: "35-45",
    styleCategory: "banhang",
    category: "Doanh Nhân Sài Gòn • 35-45t",
    pitch: 0.99,
    rate: 1.06,
    recommendedFor: "both",
    desc: "Giọng nam doanh nhân Sài Gòn phong trần, cởi mở, chân tình, chữ tín hàng đầu, tạo sự gắn kết bền chặt với đối tác và khách hàng.",
    sampleText: "Làm ăn với nhau quan trọng nhất là cái tâm và sự tử tế. Anh em cứ tin tưởng ở chất lượng sản phẩm bên mình nha!",
    edgePitch: "-2%",
    edgeRate: "+7%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.2,
      detune: 0,
      rate: 1.06,
      lowGain: 1.1,
      midFreq: 880,
      midGain: 2.7,
      presenceFreq: 3350,
      presenceGain: 4.9,
      highGain: 2.5,
      reverb: 0.03,
      reverbDecay: 0.25,
      compressor: { threshold: -20, ratio: 4.3, attack: 0.004, release: 0.14 }
    },
    dna: {
      persona: { age: "35-45", personality: "hào sảng, uy tín, chân thành, phong trần" },
      acoustic: { pitch_range: "southern-baritone", clarity: 97, speed: 81, intonation: "trustworthy" }
    }
  },
  {
    id: "vn_m_middle_lawyer_legal_26",
    name: "26. Luật Sư Trí Dũng 👑 (Nam Tư Vấn Pháp Lý - Nghiêm Cẩn, Chắc Chắn & Trọng Lượng [35-45t])",
    provider: "system",
    tier: "pro",
    badge: "👑 Studio VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "35-45",
    styleCategory: "sales_services",
    category: "Pháp Lý & Luật Sư • 35-45t",
    pitch: 0.98,
    rate: 1.04,
    recommendedFor: "manager",
    desc: "Giọng luật sư doanh nghiệp sắc bén, khúc chiết, chuẩn từng điều khoản pháp luật, đem lại sự an tâm tuyệt đối trong mọi giao dịch.",
    sampleText: "Căn cứ theo quy định của pháp luật hiện hành, quyền và lợi ích hợp pháp của thân chủ sẽ luôn được bảo vệ tối đa và toàn diện.",
    edgePitch: "-3%",
    edgeRate: "+5%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.3,
      detune: 0,
      rate: 1.04,
      lowGain: 1.1,
      midFreq: 860,
      midGain: 2.7,
      presenceFreq: 3300,
      presenceGain: 4.7,
      highGain: 2.4,
      reverb: 0.02,
      reverbDecay: 0.2,
      compressor: { threshold: -20, ratio: 4.0, attack: 0.005, release: 0.16 }
    },
    dna: {
      persona: { age: "35-45", personality: "nghiêm cẩn, khúc chiết, pháp lý, vững chắc" },
      acoustic: { pitch_range: "legal-precise", clarity: 100, speed: 79, intonation: "formal" }
    }
  },
  {
    id: "vn_m_middle_doctor_health_27",
    name: "27. Bác Sĩ Hoài Nam 👑 (Nam Bác Sĩ Chuyên Khoa - Tận Tâm, Điềm Tĩnh & Uy Tín [35-45t])",
    provider: "system",
    tier: "pro",
    badge: "👑 Studio VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "35-45",
    styleCategory: "sales_services",
    category: "Y Tế & Sức Khỏe • 35-45t",
    pitch: 0.99,
    rate: 1.03,
    recommendedFor: "both",
    desc: "Giọng bác sĩ chuyên khoa điềm tĩnh, ấm áp, giải thích khoa học dễ hiểu, tạo niềm tin lớn trong tư vấn dược phẩm và thực phẩm chức năng.",
    sampleText: "Sức khỏe là tài sản vô giá nhất. Việc duy trì chế độ dinh dưỡng lành mạnh và tầm soát định kỳ sẽ giúp bạn phòng ngừa bệnh hiệu quả.",
    edgePitch: "-2%",
    edgeRate: "+5%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.2,
      detune: 0,
      rate: 1.03,
      lowGain: 1.0,
      midFreq: 920,
      midGain: 2.6,
      presenceFreq: 3400,
      presenceGain: 4.6,
      highGain: 2.5,
      reverb: 0.03,
      reverbDecay: 0.26,
      compressor: { threshold: -19, ratio: 3.9, attack: 0.005, release: 0.16 }
    },
    dna: {
      persona: { age: "35-45", personality: "điềm tĩnh, tận tâm, y khoa, ấm áp" },
      acoustic: { pitch_range: "medical-reassuring", clarity: 98, speed: 78, intonation: "caring" }
    }
  },
  {
    id: "vn_m_middle_car_review_28",
    name: "28. Hùng Xe 👑 (Nam Đánh Giá Ô Tô & Siêu Xe - Am Hiểu & Đậm Chất Đàn Ông [35-45t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "35-45",
    styleCategory: "sales_services",
    category: "Ô Tô & Xe Sang • 35-45t",
    pitch: 0.98,
    rate: 1.06,
    recommendedFor: "both",
    desc: "Giọng nam am hiểu cơ khí và cảm giác lái, trầm đầm nam tính, đánh giá chi tiết động cơ, khung gầm và trải nghiệm đường dài.",
    sampleText: "Khối động cơ V8 tăng áp kép cho phản hồi chân ga cực kỳ bốc, hệ thống treo khí nén dập tắt hoàn toàn dao động trên cung đường xấu.",
    edgePitch: "-3%",
    edgeRate: "+8%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.3,
      detune: 0,
      rate: 1.06,
      lowGain: 1.3,
      midFreq: 820,
      midGain: 2.8,
      presenceFreq: 3300,
      presenceGain: 5.0,
      highGain: 2.4,
      reverb: 0.03,
      reverbDecay: 0.24,
      compressor: { threshold: -21, ratio: 4.5, attack: 0.004, release: 0.13 }
    },
    dna: {
      persona: { age: "35-45", personality: "nam tính, cơ khí, am hiểu, trải nghiệm" },
      acoustic: { pitch_range: "automotive-punchy", clarity: 98, speed: 82, intonation: "expert" }
    }
  },
  {
    id: "vn_m_middle_fengshui_gold_29",
    name: "29. Thầy Hoàng Kim 👑 (Nam Chuyên Gia Phong Thủy - An Tâm & Chiêu Tài Lộc [35-45t])",
    provider: "system",
    tier: "pro",
    badge: "👑 Studio VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "middle",
    ageRange: "35-45",
    styleCategory: "sales_services",
    category: "Phong Thủy & Tài Lộc • 35-45t",
    pitch: 0.97,
    rate: 1.03,
    recommendedFor: "both",
    desc: "Giọng chuyên gia phong thủy trầm ấm, an yên, mang lại nguồn năng lượng tích cực, chiêu tài đón lộc và giải tỏa băn khoăn cho gia chủ.",
    sampleText: "Khai quang vật phẩm đúng ngày giờ hoàng đạo sẽ kích hoạt cung tài lộc, mang lại vượng khí và hanh thông cho cả gia đình.",
    edgePitch: "-4%",
    edgeRate: "+4%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.4,
      detune: 0,
      rate: 1.03,
      lowGain: 1.5,
      midFreq: 780,
      midGain: 2.8,
      presenceFreq: 3200,
      presenceGain: 4.8,
      highGain: 2.3,
      reverb: 0.05,
      reverbDecay: 0.35,
      compressor: { threshold: -19, ratio: 4.0, attack: 0.006, release: 0.17 }
    },
    dna: {
      persona: { age: "35-45", personality: "an tâm, uyên bác, phong thủy, trầm ấm" },
      acoustic: { pitch_range: "spiritual-calm", clarity: 97, speed: 77, intonation: "reverent" }
    }
  },
  {
    id: "vn_m_middle_drama_cinema_30",
    name: "30. Hùng Cường 👑 (Nam Diễn Viên Điện Ảnh - Đầy Nội Lực & Lôi Cuốn [35-45t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "standard",
    ageGroup: "middle",
    ageRange: "35-45",
    styleCategory: "tam_su",
    category: "Diễn Xuất & Drama • 35-45t",
    pitch: 0.97,
    rate: 1.04,
    recommendedFor: "both",
    desc: "Giọng nam diễn viên kịch nghệ, chuyển đổi cảm xúc linh hoạt từ trầm hùng đến kịch tính, phù hợp video ngắn triệu view và review phim.",
    sampleText: "Mỗi bước đi trong cuộc đời đều để lại dấu ấn. Hãy ngẩng cao đầu và bước tiếp với tất cả sự kiêu hãnh của bản thân.",
    edgePitch: "-4%",
    edgeRate: "+6%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.4,
      detune: 0,
      rate: 1.04,
      lowGain: 1.4,
      midFreq: 800,
      midGain: 2.9,
      presenceFreq: 3250,
      presenceGain: 5.2,
      highGain: 2.4,
      reverb: 0.04,
      reverbDecay: 0.3,
      compressor: { threshold: -21, ratio: 4.5, attack: 0.004, release: 0.14 }
    },
    dna: {
      persona: { age: "35-45", personality: "kịch nghệ, nội lực, cảm xúc, cuốn hút" },
      acoustic: { pitch_range: "theatrical-baritone", clarity: 98, speed: 80, intonation: "expressive" }
    }
  },

  // =========================================================================
  // 👴 NHÓM 4: 10 GIỌNG NAM CAO NIÊN & GIÀ DẶN TỪNG TRẢI (46 - 65+ TUỔI)
  // Tông giọng: Đầm ấm, trầm khàn nhẹ tự nhiên phong trần, sâu sắc, chắc nịch
  // =========================================================================
  {
    id: "vn_m_senior_elder_statesman_31",
    name: "31. Bác Hoàng Triều 👑 (Nam Lão Thành Cách Mạng - Đĩnh Đạc, Vang Dội & Uy Nghi [46-65+t])",
    provider: "system",
    tier: "pro",
    badge: "👑 Studio VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "46-65+",
    styleCategory: "mc_btv",
    category: "Lão Thành & Uy Nghi • 46-65+t",
    pitch: 0.95,
    rate: 1.02,
    recommendedFor: "both",
    desc: "Giọng nam cao niên đĩnh đạc, âm vang hào sảng, chất chứa bề dày lịch sử và khí phách kiên trung của thế hệ đi trước.",
    sampleText: "Những bài học xương máu của thế hệ cha anh sẽ mãi là ngọn đuốc soi đường cho các thế hệ con cháu vững bước xây dựng tương lai.",
    edgePitch: "-6%",
    edgeRate: "+3%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.6,
      detune: 0,
      rate: 1.02,
      lowGain: 1.8,
      midFreq: 700,
      midGain: 3.0,
      presenceFreq: 3100,
      presenceGain: 4.8,
      highGain: 2.0,
      reverb: 0.04,
      reverbDecay: 0.3,
      compressor: { threshold: -20, ratio: 4.2, attack: 0.006, release: 0.18 }
    },
    dna: {
      persona: { age: "46-65+", personality: "uy nghi, đĩnh đạc, hào khí, lão thành" },
      acoustic: { pitch_range: "venerable-baritone", clarity: 97, speed: 76, intonation: "monumental" }
    }
  },
  {
    id: "vn_m_senior_doctor_oriental_32",
    name: "32. Lương Y Nguyễn Đức 👑 (Nam Lương Y Đông Y - Trầm Ấm, Đôn Hậu & Khuyên Răn [46-65+t])",
    provider: "system",
    tier: "pro",
    badge: "👑 Studio VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "46-65+",
    styleCategory: "sales_services",
    category: "Đông Y & Y Dược Cổ Truyền • 46-65+t",
    pitch: 0.96,
    rate: 1.02,
    recommendedFor: "both",
    desc: "Giọng thầy thuốc đông y lão làng đôn hậu, từ tốn, lời khuyên chân tình, tạo niềm tin y đức tuyệt đối khi tư vấn thảo dược và sức khỏe.",
    sampleText: "Bệnh tật gốc từ tạng phủ mà ra. Dùng thảo dược tự nhiên kết hợp dưỡng tâm an thần mới là phép trị bệnh tận gốc bền vững nhất.",
    edgePitch: "-5%",
    edgeRate: "+2%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.5,
      detune: 0,
      rate: 1.02,
      lowGain: 1.6,
      midFreq: 750,
      midGain: 2.8,
      presenceFreq: 3150,
      presenceGain: 4.6,
      highGain: 2.1,
      reverb: 0.04,
      reverbDecay: 0.32,
      compressor: { threshold: -19, ratio: 3.9, attack: 0.006, release: 0.18 }
    },
    dna: {
      persona: { age: "46-65+", personality: "đôn hậu, từ tốn, y đức, trầm ấm" },
      acoustic: { pitch_range: "elder-healer", clarity: 96, speed: 75, intonation: "benevolent" }
    }
  },
  {
    id: "vn_m_senior_story_folk_33",
    name: "33. Nghệ Nhân Ba Trầm 👑 (Nam Kể Chuyện Cổ Tích Nam Bộ - Mộc Mạc, Phong Trần [46-65+t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "nam",
    ageGroup: "senior",
    ageRange: "46-65+",
    styleCategory: "tam_su",
    category: "Kể Chuyện Dân Gian Nam Bộ • 46-65+t",
    pitch: 0.94,
    rate: 1.03,
    recommendedFor: "both",
    desc: "Giọng nghệ nhân già Nam Bộ khàn nhẹ phong trần, đậm đà tình sông nước, kể chuyện cổ tích, dã sử và văn hóa dân gian cực kỳ lôi cuốn.",
    sampleText: "Hồi đó vùng đất phương Nam này còn hoang vu lắm bây ơi, bao nhiêu tiền nhân đã đổ mồ hôi và máu xương để khai hoang mở cõi.",
    edgePitch: "-7%",
    edgeRate: "+3%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.7,
      detune: 0,
      rate: 1.03,
      lowGain: 2.0,
      midFreq: 650,
      midGain: 3.0,
      presenceFreq: 3050,
      presenceGain: 4.7,
      highGain: 1.9,
      reverb: 0.05,
      reverbDecay: 0.36,
      compressor: { threshold: -20, ratio: 4.2, attack: 0.005, release: 0.17 }
    },
    dna: {
      persona: { age: "46-65+", personality: "mộc mạc, phong trần, già dặn, Nam Bộ" },
      acoustic: { pitch_range: "rustic-storyteller", clarity: 95, speed: 76, intonation: "folklore" }
    }
  },
  {
    id: "vn_m_senior_teacher_master_34",
    name: "34. Thầy Giáo Ưu Tú Văn Khoa 👑 (Nam Nhà Giáo Lão Thành - Trầm Lắng, Uyên Bác [46-65+t])",
    provider: "system",
    tier: "pro",
    badge: "👑 Studio VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "46-65+",
    styleCategory: "mc_btv",
    category: "Giáo Dục & Uyên Bác • 46-65+t",
    pitch: 0.95,
    rate: 1.02,
    recommendedFor: "both",
    desc: "Giọng người thầy giáo già mẫu mực, từng lời khuyên răn đều chan chứa tình thương và tri thức sâu rộng đúc kết qua nửa đời người.",
    sampleText: "Học tập là hạt giống của tự do và nhân phẩm. Hãy luôn giữ cho mình một tấm lòng hiếu học và sự khiêm nhường trước biển học mênh mông.",
    edgePitch: "-6%",
    edgeRate: "+2%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.6,
      detune: 0,
      rate: 1.02,
      lowGain: 1.7,
      midFreq: 680,
      midGain: 2.8,
      presenceFreq: 3100,
      presenceGain: 4.5,
      highGain: 2.0,
      reverb: 0.04,
      reverbDecay: 0.3,
      compressor: { threshold: -19, ratio: 4.0, attack: 0.006, release: 0.18 }
    },
    dna: {
      persona: { age: "46-65+", personality: "uyên bác, mẫu mực, từ tốn, nhân ái" },
      acoustic: { pitch_range: "scholarly-deep", clarity: 98, speed: 75, intonation: "didactic" }
    }
  },
  {
    id: "vn_m_senior_farm_tea_35",
    name: "35. Bác Sáu Trà 👑 (Nam Nghệ Nhân Trà Thái Nguyên - Khàn Nhẹ Phong Trần, Đậm Đà [46-65+t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "46-65+",
    styleCategory: "banhang",
    category: "Nghệ Nhân Trà & Đặc Sản • 46-65+t",
    pitch: 0.93,
    rate: 1.03,
    recommendedFor: "both",
    desc: "Giọng lão nghệ nhân sao trà truyền thống, trầm khàn tự nhiên, mộc mạc, giới thiệu trà ngon và đặc sản quê hương với độ chân thật 100%.",
    sampleText: "Búp trà một tôm hai lá này được hái từ sáng sớm tinh sương, sao lửa thủ công giữ trọn vị chát thanh ngọt hậu đậm đà của đất trời.",
    edgePitch: "-8%",
    edgeRate: "+3%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.8,
      detune: 0,
      rate: 1.03,
      lowGain: 2.2,
      midFreq: 620,
      midGain: 3.0,
      presenceFreq: 3000,
      presenceGain: 4.8,
      highGain: 1.8,
      reverb: 0.04,
      reverbDecay: 0.28,
      compressor: { threshold: -21, ratio: 4.4, attack: 0.005, release: 0.16 }
    },
    dna: {
      persona: { age: "46-65+", personality: "nghệ nhân, phong trần, đậm đà, mộc mạc" },
      acoustic: { pitch_range: "tea-artisan", clarity: 96, speed: 76, intonation: "authentic" }
    }
  },
  {
    id: "vn_m_senior_general_warrior_36",
    name: "36. Tướng Lĩnh Chiến Trường 👑 (Nam Lão Tướng Hào Khí - Hùng Hồn, Thép Gang [46-65+t])",
    provider: "system",
    tier: "pro",
    badge: "👑 Studio VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "46-65+",
    styleCategory: "tam_su",
    category: "Lão Tướng & Khí Phách • 46-65+t",
    pitch: 0.94,
    rate: 1.05,
    recommendedFor: "both",
    desc: "Giọng lão tướng dạn dày sương gió, hùng hồn, đanh thép, âm vang như tiếng chuông đồng thúc giục ý chí chiến đấu quật cường.",
    sampleText: "Toàn quân nghe lệnh! Giữ vững trận địa, quyết không lùi một bước để bảo vệ từng tấc đất thiêng liêng của tổ quốc!",
    edgePitch: "-7%",
    edgeRate: "+5%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.7,
      detune: 0,
      rate: 1.05,
      lowGain: 2.0,
      midFreq: 650,
      midGain: 3.2,
      presenceFreq: 3100,
      presenceGain: 5.2,
      highGain: 2.0,
      reverb: 0.04,
      reverbDecay: 0.28,
      compressor: { threshold: -22, ratio: 4.8, attack: 0.003, release: 0.14 }
    },
    dna: {
      persona: { age: "46-65+", personality: "hùng hồn, thép gang, lão tướng, khí phách" },
      acoustic: { pitch_range: "martial-general", clarity: 98, speed: 79, intonation: "commanding" }
    }
  },
  {
    id: "vn_m_senior_south_elder_37",
    name: "37. Ông Năm Miền Tây 👑 (Nam Trưởng Bối Đồng Bằng - Giàu Tình Cảm & Chân Chất [46-65+t])",
    provider: "system",
    tier: "pro",
    badge: "🔥 Hot Trend VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "tay",
    ageGroup: "senior",
    ageRange: "46-65+",
    styleCategory: "tam_su",
    category: "Trưởng Bối Miền Tây • 46-65+t",
    pitch: 0.95,
    rate: 1.03,
    recommendedFor: "both",
    desc: "Giọng người bác già Nam Bộ hiền hậu, thơm thảo, tiếng nói ấm lòng chan chứa nghĩa tình đồng hương miệt vườn.",
    sampleText: "Mấy đứa tụi con về chơi là tía mừng dữ lắm, cây trái trong vườn chín rộ rồi, cứ hái ăn tự nhiên cho đã thèm nha con.",
    edgePitch: "-6%",
    edgeRate: "+3%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.6,
      detune: 0,
      rate: 1.03,
      lowGain: 1.8,
      midFreq: 700,
      midGain: 2.8,
      presenceFreq: 3100,
      presenceGain: 4.6,
      highGain: 2.1,
      reverb: 0.04,
      reverbDecay: 0.3,
      compressor: { threshold: -19, ratio: 4.0, attack: 0.005, release: 0.16 }
    },
    dna: {
      persona: { age: "46-65+", personality: "hiền hậu, thảo thơm, nghĩa tình, miền Tây" },
      acoustic: { pitch_range: "loving-elder", clarity: 95, speed: 76, intonation: "affectionate" }
    }
  },
  {
    id: "vn_m_senior_central_sage_38",
    name: "38. Cụ Đồ Xứ Quảng 👑 (Nam Trí Thức Miền Trung - Sâu Lắng & Uy Nghi [46-65+t])",
    provider: "system",
    tier: "pro",
    badge: "👑 Studio VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "trung",
    ageGroup: "senior",
    ageRange: "46-65+",
    styleCategory: "mc_btv",
    category: "Trí Thức Xứ Quảng • 46-65+t",
    pitch: 0.94,
    rate: 1.02,
    recommendedFor: "both",
    desc: "Giọng nhà nho xứ Quảng uy nghi, từng trải, âm sắc trầm lắng đượm vị mặn mòi gió biển và truyền thống hiếu học ngàn đời.",
    sampleText: "Đạo làm người lấy chữ nhân nghĩa làm gốc, sống giữa đời phải giữ lấy sự ngay thẳng và cái tâm trong sạch như trăng rằm.",
    edgePitch: "-7%",
    edgeRate: "+2%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.7,
      detune: 0,
      rate: 1.02,
      lowGain: 1.9,
      midFreq: 660,
      midGain: 2.9,
      presenceFreq: 3000,
      presenceGain: 4.5,
      highGain: 1.9,
      reverb: 0.05,
      reverbDecay: 0.34,
      compressor: { threshold: -19, ratio: 4.0, attack: 0.006, release: 0.18 }
    },
    dna: {
      persona: { age: "46-65+", personality: "ngay thẳng, uy nghiêm, nho nhã, sâu sắc" },
      acoustic: { pitch_range: "central-sage", clarity: 96, speed: 75, intonation: "philosophical" }
    }
  },
  {
    id: "vn_m_senior_herbal_zen_39",
    name: "39. Thiền Sư Tuệ Giác 👑 (Nam Đạo Sĩ Thanh Tịnh - Thư Thái, An Nhiên & Đầm Ấm [46-65+t])",
    provider: "system",
    tier: "pro",
    badge: "👑 Studio VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "standard",
    ageGroup: "senior",
    ageRange: "46-65+",
    styleCategory: "tam_su",
    category: "Thiền Định & An Nhiên • 46-65+t",
    pitch: 0.95,
    rate: 1.01,
    recommendedFor: "both",
    desc: "Giọng thiền định thanh thoát, an nhiên, dẫn lối người nghe buông bỏ phiền muộn, tìm lại sự tĩnh lặng và an lạc trong tâm hồn.",
    sampleText: "Hãy thở vào một hơi thật sâu và mỉm cười với thực tại, vạn sự đến rồi đi tự nhiên như mây trôi trên bầu trời thênh thang.",
    edgePitch: "-6%",
    edgeRate: "+1%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.6,
      detune: 0,
      rate: 1.01,
      lowGain: 1.6,
      midFreq: 720,
      midGain: 2.7,
      presenceFreq: 3150,
      presenceGain: 4.4,
      highGain: 2.2,
      reverb: 0.06,
      reverbDecay: 0.45,
      compressor: { threshold: -18, ratio: 3.8, attack: 0.007, release: 0.2 }
    },
    dna: {
      persona: { age: "46-65+", personality: "an nhiên, thanh tịnh, buông bỏ, từ bi" },
      acoustic: { pitch_range: "zen-peaceful", clarity: 96, speed: 73, intonation: "meditative" }
    }
  },
  {
    id: "vn_m_senior_patriarch_heritage_40",
    name: "40. Tộc Trưởng Đại Gia Tộc 👑 (Nam Gia Trưởng Quyền Uy - Vững Như Bàn Thạch [46-65+t])",
    provider: "system",
    tier: "pro",
    badge: "👑 Studio VIP",
    gender: "Male",
    lang: "vi-VN",
    region: "vi",
    dialect: "bac",
    ageGroup: "senior",
    ageRange: "46-65+",
    styleCategory: "banhang",
    category: "Tộc Trưởng & Quyền Lực • 46-65+t",
    pitch: 0.93,
    rate: 1.04,
    recommendedFor: "manager",
    desc: "Giọng vị tộc trưởng gia tộc quyền uy, âm lượng vang dội, lời nói chắc như đinh đóng cột, biểu tượng của sự che chở và vững chãi.",
    sampleText: "Gia phong và danh dự là báu vật truyền đời của dòng họ. Hãy giữ vững ý chí và sự đồng lòng để đời đời con cháu hưng vượng.",
    edgePitch: "-8%",
    edgeRate: "+4%",
    neuralVoice: "vi-VN-NamMinhNeural",
    dspProfile: {
      semitones: -0.8,
      detune: 0,
      rate: 1.04,
      lowGain: 2.2,
      midFreq: 600,
      midGain: 3.2,
      presenceFreq: 3000,
      presenceGain: 5.0,
      highGain: 1.8,
      reverb: 0.04,
      reverbDecay: 0.28,
      compressor: { threshold: -21, ratio: 4.6, attack: 0.004, release: 0.15 }
    },
    dna: {
      persona: { age: "46-65+", personality: "quyền uy, tộc trưởng, vững chãi, gia phong" },
      acoustic: { pitch_range: "patriarchal-deep", clarity: 98, speed: 78, intonation: "sovereign" }
    }
  }
];
